(PC-8272) Avoid potential crash if no offerRules
pass-culture/pass-culture-app-native pull request #1185
Opened 2021-06-01 11:33 UTC by antoinewg

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8272

## Checklist

I have:

- [x] Made sure the title of my PR follows the convention `[PC-XXX] <summary>`.
- [ ] Made sure my feature is working on the relevant real / virtual devices.
- [ ] Written **unit tests** for my feature.

2021-06-01 15:34 UTC, AnoukHello approved these changes
:clap: :clap:

2021-06-01 15:34 UTC, AnoukHello commented on src/features/bookings/components/ThreeShapesTicket.constants.ts
> +//      TICKET_WIDTH
Excellente idée :ok_hand:

2021-06-01 15:34 UTC, AnoukHello commented on src/features/bookings/components/ThreeShapesTicket.tsx
> +  const contentWidth = width - 5
C'est pour quoi le - 5 ?

2021-06-01 15:35 UTC, antoinewg commented on src/features/bookings/components/ThreeShapesTicket.constants.ts
> +//      TICKET_WIDTH
en soi ça sert pas à grand chose mais ça m'a amusé :)

2021-06-01 15:36 UTC, antoinewg commented on src/features/bookings/components/ThreeShapesTicket.tsx
> +  const contentWidth = width - 5
ouais c'est le seul hack que j'ai pas réussi à enlever. En gros le ticket footer et header sont plus petits en largeur même quand je la fixe. Je pense que c'est à cause de l'aspectRatio mais je suis pas sûr

2021-06-01 15:59 UTC, AnoukHello commented on src/features/bookings/components/ThreeShapesTicket.constants.ts
> +//      TICKET_WIDTH
Ahah oui mais au moins on capte en un coup d'oeil comment c'est fichu

2021-06-01 16:21 UTC, marionnousvalentin commented on src/features/bookings/pages/Bookings.test.tsx
> +    expect(useBookings).toBeCalledTimes(1)
✅ pourquoi pas toBeCalledWith() ?

2021-06-01 16:22 UTC, marionnousvalentin commented on src/features/bookings/components/OnGoingBookingsList.tsx
> +        <EndedBookingsSection endedBookings={props.endedBookings} />
❓  pourquoi enlever cette props ??

2021-06-01 16:26 UTC, marionnousvalentin commented on src/features/cheatcodes/pages/AppComponents.tsx
> -            color={Platform.select({
❓ on ne veut pas garder le switch de couleur ?

2021-06-01 16:34 UTC, marionnousvalentin commented on src/features/bookings/pages/BookingDetails.tsx
>            <Spacer.Column numberOfSpaces={22} />
Je crois que le ticket n'était pas clair :)
on se fait un brief demain pour que je te montre ce que j'avais en tete ? 
(le but était de supprimer les onlayout de src/features/bookings/pages/BookingDetails.tsx) cf le TODO
Pour éviter que ça ne clignote quand on affiche l'offre et fixer les bugs de rendu design à cause du re-rendu qui n'est pas systématique

2021-06-01 16:34 UTC, marionnousvalentin requested changes
cf comm

2021-06-01 17:21 UTC, antoinewg commented on src/features/bookings/pages/Bookings.test.tsx
> +    expect(useBookings).toBeCalledTimes(1)
parce que ce serait `toBeCalledWith()` sans rien, et je trouve que `toBeCalledTimes` apporte plus d'info dans ce cas.

2021-06-01 17:22 UTC, antoinewg commented on src/features/bookings/components/OnGoingBookingsList.tsx
> +        <EndedBookingsSection endedBookings={props.endedBookings} />
pour éviter de faire l'appel à /bookings. (on l'a déjà dans le composant parent, autant le passer en props)

2021-06-01 17:22 UTC, antoinewg commented on src/features/bookings/components/OnGoingBookingsList.tsx
> +        <EndedBookingsSection endedBookings={props.endedBookings} />
je l'enlève pas, je la rajoute

2021-06-01 17:23 UTC, antoinewg commented on src/features/cheatcodes/pages/AppComponents.tsx
> -            color={Platform.select({
la props color est utilisé uniquement dans AppComponents => inutile donc, je simplifie

2021-06-01 17:28 UTC, antoinewg commented on src/features/bookings/pages/BookingDetails.tsx
>            <Spacer.Column numberOfSpaces={22} />
je vois plus de onLayout dans `src/features/bookings` ;) et y'a plus de blinks non plus.
Le reste c'est de la 'boy scout rule': je nettoie par où je passe ^^.
on peut s'appeler ouais.

2021-06-03 08:49 UTC, marionnousvalentin commented on src/features/bookings/pages/Bookings.test.tsx
> +    expect(useBookings).toBeCalledTimes(1)
ça apport moins d'info car tu sais juste que ta fonction a été appelée, mais pas avec quoi ;)

2021-06-03 08:50 UTC, marionnousvalentin commented on src/features/bookings/pages/BookingDetails.tsx
>            <Spacer.Column numberOfSpaces={22} />
Vu avec toi, tu as validé avec Gabriel que le changement de design est OK

2021-06-03 08:50 UTC, marionnousvalentin approved these changes
Petit détail sur le test, sinon OK !

2021-06-03 11:06 UTC, merged