🐛 [PC-8688] filter button - delete extra whitespace
pass-culture/pass-culture-app-native pull request #1506
Opened 2021-08-16 15:59 UTC by yorickeando

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8688

## Checklist

I have:

- [x] Made sure the title of my PR follows the convention `[PC-XXX] <summary>`.
- [x] Made sure my feature is working on the relevant real / virtual devices.
- [x] Written **unit tests** for my feature.
- [ ] Written **documentation on Notion** for my feature.
- [ ] Added new reusable components to the AppComponents page and communicate to the team on slack
- [x] Added a **screenshot** for UI tickets.
- [ ] Attached a **ticket number** for any added TODO/FIXME \
       (for tech tasks, give the best context about the TODO resolution: what/who/when).

## Screenshots

| \*iOS - [Phone name] | \*Android - [Phone name] | Tablet - [Phone name] | Little - [Phone name] |
| -------------------- | :----------------------: | --------------------: | --------------------: |
|          <img width="331" alt="Capture d’écran 2021-08-16 à 17 26 00" src="https://user-images.githubusercontent.com/44037911/129588566-2372fb63-330f-4b23-b4f5-77380fa48eaa.png">            |      <img width="331" alt="Capture d’écran 2021-08-16 à 17 19 15" src="https://user-images.githubusercontent.com/44037911/129588248-6f4b26c2-d6a0-4238-8fc6-be8725d44cc7.png"> |                       |                       |
                    

## Deploy hard

If native code (ios/android) was modified, **after** the PR is merged, on the master branch, upgrade the **app version** (+1 patch):

- if you want an hard deployment of the testing environment, use `yarn trigger:testing:deploy`

2021-08-16 16:10 UTC, Lucasbeneston commented on __snapshots__/features/search/atoms/Buttons/__tests__/Filter.native.test.tsx.native-snap
>  `;
Super cet ajout dans le screen shot ! Mais attention la CI fail car il faut aussi update le snapshot web avec la commander `yarn test:unit:web -u`

2021-08-16 16:12 UTC, Lucasbeneston commented
Un commentaire plus général, il faudrait ajouter le numéro de ticket sur les commits du style "(PC-8688) Filter-button : Delete ...". Ça permet de mieux retrouver les commits quand on cherry pick par exemple. 
Mais sinon c'est top ;)

2021-08-16 16:34 UTC, antoinewg requested changes

2021-08-16 16:34 UTC, antoinewg commented on src/features/search/atoms/Buttons/Filter.tsx
>                <Typo.ButtonText color={ColorsEnum.PRIMARY}>{filterCount}</Typo.ButtonText>
le `<Spacer.Row numberOfSpaces={0.5} />` était un peu hacky mais à la base c'était justement pour centrer le nombre dans la bulle blanche. Si tu regardes mtn (en tout cas sur iOS), ce n'est plus centré

2021-08-17 07:42 UTC, antoinewg commented on src/features/search/atoms/Buttons/Filter.tsx
>                <Typo.ButtonText color={ColorsEnum.PRIMARY}>{filterCount}</Typo.ButtonText>
bon après c'est toujours mieux sans le hack, à voir avec les UX si ça leur convient

2021-08-17 07:43 UTC, antoinewg reviewed
À voir avec les UX et le PO qui a fait le ticket (avec un screenshot sur chaque device)

2021-08-17 07:44 UTC, antoinewg approved these changes

2021-08-17 08:25 UTC, merged