(PC-4913): signup first page
pass-culture/pass-culture-app-native pull request #159
Opened 2020-11-24 09:44 UTC by DanielBaudry

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4913
## Checklist

I have:

- [ ] Made sure the title of my PR follows the convention `[PC-XXX] <summary>`.
- [ ] Made sure my feature is working on the relevant real / virtual devices.
- [ ] Written **unit tests** for my feature.
- [ ] Added new reusable components to the AppComponents page and communicate to the team on slack
- [ ] Added a **screenshot** for UI tickets.

## Screenshots

Android Pixel 2
![image](https://user-images.githubusercontent.com/607176/100076829-ee423380-2e41-11eb-9c2e-bc7693f242eb.png)

IOS (incoming)

## Deploy hard

If native code (ios/android) was modified, **after** the PR is merged, on the master branch, upgrade the **app version** (+1 patch):

- if you want an hard deployment of the testing environment, use `yarn version:testing` (this will create a commit with a tag)
- then run `git push --follow-tags`

2020-11-24 14:32 UTC, blixit approved these changes

2020-11-24 14:32 UTC, blixit commented on src/features/auth/pages/Signup.test.tsx
> +      expect(disabledButtonSnapshot).toMatchDiffSnapshot(enabledButtonSnapshot)
ici tu fais un snapshot de la page alors que le test annonce une vérification que l'input est rempli.

est-ce qu'on ne scinderait pas le test en 2 ?
- snapshot de la diff sur la page
- test qui vérifie que l'input est rempli

2020-11-24 14:32 UTC, blixit commented on src/features/auth/pages/Signup.tsx
> +    return
tu peux préciser avec un TODO quand la fonction sera implémenter:

`// TODO: PC-XXXX`

2020-11-24 14:32 UTC, blixit commented on src/features/auth/pages/Signup.tsx
> +    return
idem TODO

2020-11-24 14:32 UTC, blixit commented on src/features/auth/pages/Signup.tsx
> +            disabled={shouldDisableValidateButton}
la props isLoading pour l'animation du bouton est manquante. on pourrait la définir à false et ajouter un commentaire TODO pour le mettre à jour

2020-11-24 15:23 UTC, BenStirrup requested changes
Le snapshot du CheckBoxInput est beaucoup trop grand^^ (+ 10,000 lignes). Tel quel, le test n'est pas utilisable, et le navigateur plante en essayant d'ouvrir le fichier^^.
Je pense que tu peux remplacer ce test par autre chose qu'un snapshot. Par exemple, vérifier qu'un test id s'affiche ou quelque chose du genre.

2020-11-24 15:32 UTC, AnoukHello reviewed
Ça me va, par contre au niveau de la structure des commits je suis un peu confuse. Je verrais bien 4 commits: un premier qui introduit le composant `CheckboxInput` + ses tests + la demo dans `AppComponents`, un deuxième qui introduit la page `Signup` + ses tests, un troisième sur le refacto de l'enum, un quatrième sur l'update des trad (qui ne contient que les changements dans `messages.po`. Pour moi les deux commits de mise à jour des tests sont "fusionnables" dans les autres :)

2020-11-24 15:32 UTC, AnoukHello commented on src/features/auth/pages/Signup.test.tsx
> +      expect(disabledButtonSnapshot).toMatchDiffSnapshot(enabledButtonSnapshot)
Ou alors tu vérifies juste que la couleur du bouton a changé ?

2020-11-24 15:32 UTC, AnoukHello commented on src/features/auth/pages/Signup.test.tsx
> +}
Tu peux peut-être mettre un TODO pour ne pas oublier de tester la redirection vers le formulaire du mdp, l'abandon de l'inscription et la gestion du storage de l'email ?

2020-11-24 15:32 UTC, AnoukHello commented on src/features/auth/pages/Signup.tsx
>  import { _ } from 'libs/i18n'
Typo dans le message de commit: `Add newsletter...`

2020-11-24 15:32 UTC, AnoukHello commented on src/features/auth/pages/Signup.tsx
> +import { CheckBoxInput } from 'ui/components/inputs/CheckBoxInput'
Suggestion de naming: `CheckboxInput` (`checkbox` est un seul mot en anglais il me semble)

2020-11-25 11:08 UTC, AnoukHello commented on src/features/auth/pages/Signup.tsx
> +    return
J'ai mergé le formulaire de mot de passe tout à l'heure, tu pourrais peut-être juste implémenter la navigation ? Ou alors c'est prévu dans un autre ticket ?

2020-11-25 11:21 UTC, BenStirrup commented on src/ui/theme/grid.ts
> +export enum BorderRadiusEnum {
C'est pas une mauvaise pratique de suffixer les enums par `Enum` ?
```suggestion
export enum BorderRadius {
```
En voyant les membres de ton enums, je ne suis pas sûr que `CHECKBOX_RADIUS` soit utilisé.
Tu pourrais juste créer une constante BORDER_RADIUS et l'exporter.

2020-11-25 11:22 UTC, BenStirrup commented on src/ui/svg/icons/types.ts
> +export interface RectangleIconInterface {
```suggestion
export interface RectangleIcon {
```
Même commentaire que l'enum du coup^^

2020-11-25 11:23 UTC, BenStirrup commented on src/ui/components/inputs/CheckboxInput.tsx
> +/* eslint-disable react-native/no-inline-styles */
Tu n'as pas de inline style dans ce fichier, donc pas besoin de disable la règle.

2020-11-25 11:35 UTC, DanielBaudry commented on src/ui/theme/grid.ts
> +export enum BorderRadiusEnum {
Un oublie de ma part le checkbox_radius est bien utilisé maintenant !
Pour le nommage, je me suis basé sur ColorsEnum qui existe comme ça

2020-11-25 12:02 UTC, blixit commented on src/features/auth/pages/Signup.tsx
> +            disabled={shouldDisableValidateButton}
bonne question !

ma crainte c'était de perdre l'info entre le merge de ta PR actuelle et le moment où un dev implémentera le call api.

est-ce qu'une commentaire TODO dans la fonction validateEmail serait plus approprié ? je te laisse juger

2020-11-25 12:06 UTC, blixit commented on src/ui/svg/icons/types.ts
> +export interface RectangleIconInterface {
interface IconSharedProperties {
  color?: ColorsEnum
  testID?: string
}

export interface IconInterface extends IconSharedProperties {
  size?: number | string
}

export interface RectangleIconInterface extends IconSharedProperties {
  width?: number | string
   height?: number | string
}

2020-11-25 12:08 UTC, DanielBaudry commented on src/features/auth/pages/Signup.tsx
> +            disabled={shouldDisableValidateButton}
Yes c'est ce que j'ai fait !

2020-11-25 12:54 UTC, merged