[PC-11741] feat(IdentityCheck): Add styled page Stepper
pass-culture/pass-culture-app-native pull request #2013
Opened 2021-11-10 17:26 UTC by antoinewg

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11741

## Checklist

I have:

- [x] Made sure the title of my PR follows the convention `[PC-XXXXX] <summary>`.
- [x] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [x] Written **unit tests** native (and web when implementation is different) for my feature.
- [x] Added a **screenshot** for UI tickets.
- [x] Made sure translations file is up to date (`yarn translations:extract`)

## Screenshots

| iOS | Android | Mobile - Chrome | Desktop - Chrome |
| --: | ------: | --------------: | ---------------: | 
|  <img width="315" alt="iphone 13" src="https://user-images.githubusercontent.com/10118284/141162486-24e6c510-d2cc-4bc2-bc2d-96b762107d9a.png">  |    None     |     ![mobile web](https://user-images.githubusercontent.com/10118284/141162512-a9c5df3a-3ee6-4c3f-a712-31c359e1c109.png)        |          ![web](https://user-images.githubusercontent.com/10118284/141162557-bd2a8a1d-76ec-4f95-be7d-e90dfdd841b1.png)        | 

<img width="302" alt="icons" src="https://user-images.githubusercontent.com/10118284/141162475-377606e7-e72e-4177-8c78-73b39c6659d8.png">

2021-11-10 18:36 UTC, Lucasbeneston commented on src/features/identityCheck/pages/Stepper.tsx
J'aurais vraiment gardé la même structure que sur id-check avec les Flex plutôt que Spacer.Column car sur petit device ça cache le titre ou le bouton "Abandonner". Je n'aurais pas utlisé le GenericInfoPage aussi car sont padding est trop important par défaut et son design n'est pas vraiment le même. Sur la maquette, il y a moins de bordure. Puis j'aurais adapté un design plus sympa pour le web ? 

```
import { t } from '@lingui/macro'
import React from 'react'
import styled, { useTheme } from 'styled-components/native'

import { StepButton } from 'features/identityCheck/atoms/StepButton'
import { useIdentityCheckSteps } from 'features/identityCheck/useIdentityCheckSteps'
import { homeNavConfig } from 'features/navigation/TabBar/helpers'
import { useGoBack } from 'features/navigation/useGoBack'
import { ButtonTertiaryWhite } from 'ui/components/buttons/ButtonTertiaryWhite'
import { Background } from 'ui/svg/Background'
import { Spacer, Typo, ColorsEnum, getSpacing } from 'ui/theme'

export const IdentityCheckStepper = () => {
  const theme = useTheme()
  const { goBack } = useGoBack(...homeNavConfig)
  const steps = useIdentityCheckSteps()

  return (
    <CenteredContainer>
      <Background />
      <Container>
        <Spacer.TopScreen />
        {theme.isDesktopViewport ? <Spacer.Column numberOfSpaces={2} /> : <Spacer.Flex />}
        <Title>{t`C’est très rapide !`}</Title>
        <Spacer.Column numberOfSpaces={2} />
        <StyledBody>{t`Voici les 3 étapes que tu vas devoir suivre.`}</StyledBody>
        {theme.isDesktopViewport ? <Spacer.Column numberOfSpaces={2} /> : <Spacer.Flex />}
        {/* TODO(antoinewg) dehardcode state. This is temporary for design purposes */}
        <StepButton key={steps[0].name} step={steps[0]} state="completed" />
        <StepButton key={steps[1].name} step={steps[1]} state="current" />
        <StepButton key={steps[2].name} step={steps[2]} state="disabled" />
        {theme.isDesktopViewport ? <Spacer.Column numberOfSpaces={10} /> : <Spacer.Flex flex={2} />}
        <ButtonTertiaryWhite title={t`Abandonner`} onPress={goBack} />
      </Container>
    </CenteredContainer>
  )
}

const Title = styled(Typo.Title3).attrs({ color: ColorsEnum.WHITE })({
  textAlign: 'center',
})

const StyledBody = styled(Typo.Body).attrs({ color: ColorsEnum.WHITE })({
  textAlign: 'center',
})

const CenteredContainer = styled.View({
  flex: 1,
  alignItems: 'center',
})

const Container = styled.View({
  flex: 1,
  justifyContent: 'center',
  padding: getSpacing(5),
  width: '100%',
  maxWidth: getSpacing(125),
}) 
```

2021-11-10 18:36 UTC, Lucasbeneston commented on src/features/identityCheck/pages/Stepper.tsx
Le rendu des deux : 
<img width="381" alt="Capture d’écran 2021-11-10 à 19 21 22" src="https://user-images.githubusercontent.com/62059034/141172921-c931177c-df65-4a71-a2dc-c2ea695dadb1.png">
![Capture d’écran 2021-11-10 à 19 34 08](https://user-images.githubusercontent.com/62059034/141172911-1ae259d0-4687-475c-9659-d5ed1586330c.png)

2021-11-10 19:00 UTC, antoinewg commented on src/features/identityCheck/pages/Stepper.tsx
okey ! C'était pour simplifier au max, mais le design est pas mal je vais prendre le tien. Je me suis qu'en utilisant GenericInfoPage, au moins l'utilisateur pouvait scroller.

2021-11-11 08:45 UTC, yorickeando commented on src/ui/svg/icons/IdentityCheck/ProfileIcon.tsx
> +export const ProfileIcon = React.memo(Profile)
Est-ce que le nommage en `...Icon` est judicieux ? C'est pas forcément mal mais ça détone surtout avec l'ensemble des autres icônes qui n'a pas ce suffixe. 

Le mieux (mais encore une fois, je n'ai pas présenté le modop), ça serait de déprécier Profile en `ProfileDeprecated` dans un fichier renommé `Profile_deprecated.tsx` dans un premier commit, puis de réécrire un fichier Profile.tsx avec le nouveau code que tu as écrit.

2021-11-11 08:46 UTC, yorickeando requested changes
Si tu as l'énergie de découper en commits et renommer les fichiers dépréciés, ça serait top !

2021-11-11 08:46 UTC, yorickeando commented on src/ui/svg/icons/IdentityCheck/ProfileIcon.tsx
> +export const ProfileIcon = React.memo(Profile)
ça permet de suivre les icônes qui ont déjà leur pendant "à jour" et celles qui ne l'ont pas. Plus difficile de s'en rendre compte si le fichier n'est pas déprécié.

2021-11-12 09:29 UTC, antoinewg commented on src/features/identityCheck/pages/Stepper.tsx
J'ai pris ton code :)

2021-11-12 09:33 UTC, yorickeando commented on src/ui/svg/icons/IdentityCheck/Profil.tsx
Tu ne l'appelles pas `Profile` parce qu'il y a déjà une icône Profile ? Est-ce que ça n'est pas justement l'icône à déprécier pour que celle-ci puisse les remplacer à terme ? Typiquement je pense que c'est la même que dans la page Profil de l'utilisateur.

2021-11-12 09:36 UTC, yorickeando approved these changes
S'il n'y a effectivement rien à déprécier, c'est bon pour moi, mais à checker

2021-11-12 09:36 UTC, yorickeando commented on src/ui/svg/icons/IdentityCheck/Profil.tsx
> +  color = ColorsEnum.BLACK,
Tu ne l'appelles pas `Profile` parce qu'il y a déjà une icône Profile ? Est-ce que ça n'est pas justement l'icône à déprécier pour que celle-ci puisse les remplacer à terme ? Typiquement je pense que c'est la même que dans la page Profil de l'utilisateur.

2021-11-12 09:36 UTC, yorickeando commented on src/ui/svg/icons/IdentityCheck/Profil.tsx
> +  color = ColorsEnum.BLACK,
Ou bien l'ancienne icône Profile est déjà au bon format ? Je n'ai pas regardé précisément.

2021-11-12 09:54 UTC, merged