(PC-12556) feat(accessibility): Add aria-hidden, role img and aria-label for all svg
pass-culture/pass-culture-app-native pull request #2420
Opened 2022-01-04 16:10 UTC by Lucasbeneston

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX

## Checklist

I have:

- [ ] Made sure the title of my PR follows the [convention](1) `($jira) $type($scope): $summary`.
- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets.

## Screenshots

| iOS | Android | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
| --: | ------: | --------------: | ---------------: | ---------------: |
|     |         |                 |                  |                  |

[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/doc/standards/pr-title.md
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-01-06 11:04 UTC, bruno-ebstein-pass-culture approved these changes

2022-01-06 11:04 UTC, bruno-ebstein-pass-culture commented on src/ui/svg/icons/ExternalSite.tsx
> +    accessibilityRole="image">
pourquoi le label ne se situe pas sur le bouton entier ?

2022-01-06 11:04 UTC, bruno-ebstein-pass-culture commented on src/ui/svg/icons/ExternalSite.tsx
> +    accessibilityRole="image">
meme question pour les icons dans le meme cas

2022-01-06 11:04 UTC, bruno-ebstein-pass-culture commented on src/ui/svg/icons/EyeSophisticated.tsx
> -  accessibilityLabel,
meme question pour les icons dans le meme cas

2022-01-06 12:09 UTC, Lucasbeneston commented on src/ui/svg/icons/ExternalSite.tsx
> +    accessibilityRole="image">
Car c'est l'icon qui est porteur de l'information "C'est un lien externe". Sur le bouton, il faut faire apparaitre le texte de description. J'ai ajouté directement les accessibilityLabel et role sur les icons qui ont cette fonction de décrire une action ou autre. Car comme ça les developpeurs n'auront pas se soucier de mettre ces éléments d'accessibilité. 

Dans le cas ou un icon peut être utilisé comme illustration OU comme porteur d'une information, je viens de faire une proposition avec les logo "Eye" et "EyeSlash". 

L'icon : https://github.com/pass-culture/pass-culture-app-native/pull/2420/files#diff-f27429226cff1069e5d6d780511af1f48ba36ec7dec355faf7aea588cedf11bd

Son utilisation : https://github.com/pass-culture/pass-culture-app-native/pull/2420/files#diff-f796ae3626739dda5d3f60ccaaae98944441c9014912d678cbfcec25bf277f0f

2022-01-06 13:12 UTC, bruno-ebstein-pass-culture commented on src/ui/components/inputs/PasswordInput.tsx
> +            />
pourquoi ne pas mettre l'`accessibilityLabel` sur `IconTouchableOpacity` ?

```ts
        <IconTouchableOpacity
          {...accessibilityAndTestId(t`Basculer l'affichage du mot de passe`)}
          onPress={togglePasswordDisplay}
          accessibilityLabel={shouldHidePassword ? "Mot de passe caché" : "Mot de passe visible" }>
          {shouldHidePassword ? (
            <EyeSlash size={getSpacing(6)} />
          ) : (
            <Eye size={getSpacing(6)} />
          )}
       </IconTouchableOpacity>
```

2022-01-06 13:12 UTC, bruno-ebstein-pass-culture commented on src/ui/svg/icons/types.ts
> +  accessibilityRole?: AccessibilityRole
toutes les icones ne supportent pas ces propriétés, le type me semble un peu trompeur

2022-01-06 17:02 UTC, bruno-ebstein-pass-culture requested changes

2022-01-07 08:30 UTC, bruno-ebstein-pass-culture approved these changes

2022-01-07 08:32 UTC, merged