(PC-13023) fix(shadows): Update shadows for offer images, booking images and main header
pass-culture/pass-culture-app-native pull request #2606
Opened 2022-02-09 15:18 UTC by WendyPassculture

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13023

## Checklist

I have:

- [x] Made sure the title of my PR follows the [convention](1) `($jira) $type($scope): $summary`.
- [x] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [x] Added a **screenshot** for UI tickets.
- [ ] Attached a **ticket number** or **github dev name** for any added TODO / FIXME.
- [ ] Added new reusable components to **AppComponents** page and communicate to the team on slack.
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](2)
- [ ] Made sure translations file is up to date (`yarn translations:extract`)

## Screenshots

<img width="1680" alt="Capture d’écran 2022-02-17 à 12 05 19" src="https://user-images.githubusercontent.com/90036171/154468731-bab80f10-060e-4848-861c-5a9ec845e1e6.png">
<img width="1680" alt="Capture d’écran 2022-02-17 à 12 05 05" src="https://user-images.githubusercontent.com/90036171/154468773-e94d3f1b-7564-4070-9eb7-fa1563f4a742.png">
<img width="1680" alt="Capture d’écran 2022-02-17 à 12 04 53" src="https://user-images.githubusercontent.com/90036171/154468802-81107a12-cff4-4c55-8bb6-c22a9789b582.png">

[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/doc/standards/pr-title.md
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-02-14 11:06 UTC, yorickeando commented
Est-ce que tu peux découper en commits les actions que tu fais indépendamment pour chaque composant ? J'ai l'impression que plusieurs choses sont traitées à la fois dans ce grand commit et j'ai du mal à relire. 

Il y a de l'usage d'ombres dans un cas et l'intégration d'une nouvelle couleur de thème dans l'autre notamment. Si tu vois des découpages encore plus mono-fonctionnels, n'hésite pas.

2022-02-15 09:21 UTC, yorickeando commented on src/ui/theme/colors.ts
> +  GREY_DARK_SHADOW = 'rgba(105,106,111,0.34)',
Est-il possible d'avoir un format semblable à ceux du reste du thème ?

2022-02-15 09:23 UTC, yorickeando commented on src/features/navigation/RootNavigator/Header/Header.web.tsx
> +      shadowColor: theme.colors.greyDarkShadow,
Les gris actuels du thème ne sont pas suffisants ? Il n'y a pas moyen de jouer sur l'opacité des gris déjà existant plutôt que d'ajouter un autre gris au thème ? Il risque de n'être utilisé nulle part ailleurs et ne fait pas partie (je crois) de la palette graphique du pass (à confirmer auprès d'un UI)

2022-02-15 09:26 UTC, yorickeando commented on src/ui/components/hero/Hero.tsx
>    }),
Par exemple, ici je serais davantage partisan de modifier l'opacité en fonction de la plateforme, plutôt que de mettre une autre couleur dans le thème général.

Donc plutôt du genre `shadowOpacity: Platform.OS === 'web' ? 0.5 : 0.2` (ou quelque que soit la valeur qui fonctionne le mieux)

2022-02-15 09:27 UTC, yorickeando requested changes
Quelques petits commentaires sur la gestion de la couleur.

2022-02-15 09:28 UTC, WendyPassculture commented on src/ui/components/hero/Hero.tsx
>    }),
Non sur le web le shadowOpacity n'est pas pris en compte. tu dois gérer avec la couleur

2022-02-15 09:29 UTC, WendyPassculture commented on src/features/navigation/RootNavigator/Header/Header.web.tsx
> +      shadowColor: theme.colors.greyDarkShadow,
ShadowOpacity n'est pas géré sur le web, justement c'est pour ca que sur le Web les ombres étaient plus foncé, j'ai rajotué l'alpha directement dans la couleur de l'ombre.

2022-02-15 09:31 UTC, WendyPassculture commented on src/ui/theme/colors.ts
> +  GREY_DARK_SHADOW = 'rgba(105,106,111,0.34)',
Alors pour la représentation de l'alpha en effet je peux rajouter en hex mais ca peut porter à confusion, pour les couleurs avec alpha 'est bien d'avoir un visu plus direct.

2022-02-17 14:39 UTC, merged