(PC-13963) feat(storybook): add Icons stories - part 1
pass-culture/pass-culture-app-native pull request #2840
Opened 2022-03-24 16:46 UTC by Lucasbeneston

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13963

## Checklist

I have:

- [ ] Made sure the title of my PR follows the [convention](1) `($jira) $type($scope): $summary`.
- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets.
- [ ] Attached a **ticket number** or **github dev name** for any added TODO / FIXME.
- [ ] Added new reusable components to **AppComponents** page and communicate to the team on slack.
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](2)
- [ ] Made sure translations file is up to date (`yarn translations:extract`)

## Screenshots

| iOS | Android | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
| --: | ------: | --------------: | ---------------: | ---------------: |
|     |         |                 |                  |                  |

[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/doc/standards/pr-title.md
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-03-25 10:28 UTC, aliraiki commented on src/features/cheatcodes/pages/AppComponents/Icons.stories.tsx
> +    icon: Record<string, React.ComponentType<IconInterface>>
J'aurai plutôt renommé en `icons`

2022-03-25 10:31 UTC, aliraiki approved these changes

2022-03-25 10:35 UTC, Lucasbeneston commented on src/features/cheatcodes/pages/AppComponents/Icons.stories.tsx
> +    icon: Record<string, React.ComponentType<IconInterface>>
Ouais carrément je vais faire ça !

2022-03-25 10:41 UTC, WendyPassculture commented on src/features/cheatcodes/pages/AppComponents/iconsExports.ts
> +import { Again } from 'ui/svg/icons/Again'
Pourquoi tu laisses l'export des icons dans cheatscode et non dans ui/svg ???

2022-03-25 10:41 UTC, WendyPassculture commented on src/features/cheatcodes/pages/AppComponents/Icons.stories.tsx
> +  </React.Fragment>
Tu ne peux pas créer un Composant IconsCategoryView ?

2022-03-25 10:41 UTC, WendyPassculture commented on src/features/cheatcodes/pages/AppComponents/Icons.tsx
> +)
Duplicate code, tu l'as déjà mis dans la stories, crée un composant pour ca.

2022-03-25 10:53 UTC, Lucasbeneston commented on src/features/cheatcodes/pages/AppComponents/iconsExports.ts
> +import { Again } from 'ui/svg/icons/Again'
Est-ce que c'est une bonne pratique d'avoir des imports / exports (problème d'import circulaire) de ce genre dans notre code ? 
Je voulais juste l'avoir dans les cheatcodes / storybook car c'était dupliqué.

2022-03-25 10:55 UTC, Lucasbeneston commented on src/features/cheatcodes/pages/AppComponents/Icons.tsx
> +)
Il y a une petite différence entre les deux qui est qu'on a besoin de ` ComponentStory` dans les stories pour pouvoir utiliser `.args = {}`
Je vais voir ce que je peux faire

2022-03-25 15:03 UTC, WendyPassculture requested changes

2022-03-25 15:04 UTC, Lucasbeneston commented on src/features/cheatcodes/pages/AppComponents/IconsContainer.tsx
> +    {Array.from(Object.entries(icons)).map(([name, icon]) => {
Je peux retirer Array.from(...) c'est ça ?

2022-03-25 15:09 UTC, WendyPassculture commented on src/features/cheatcodes/pages/AppComponents/IconsContainer.tsx
> +          {isBicolor ? <IconComponentBicolor /> : null}
J'aurai mis { isBicolor && <IconComponentBicolor /> }

2022-03-25 15:14 UTC, WendyPassculture commented on src/features/cheatcodes/pages/AppComponents/IconsContainer.tsx
> +          {!!isBicolor && <IconComponentBicolor />}
isBicolor est déjà boolean ca sert à rien de mettre !!

2022-03-25 15:17 UTC, Lucasbeneston commented on src/features/cheatcodes/pages/AppComponents/IconsContainer.tsx
> +          {!!isBicolor && <IconComponentBicolor />}
J'ai un warning  si je ne met pas `!!`  et test lint ne passeront pas :D 
<img width="317" alt="Capture d’écran 2022-03-25 à 16 15 38" src="https://user-images.githubusercontent.com/62059034/160148817-61858f9e-cc64-4264-8591-bb0ae17654e6.png">
<img width="997" alt="Capture d’écran 2022-03-25 à 16 16 59" src="https://user-images.githubusercontent.com/62059034/160148966-72cdadfa-528a-4ae4-93d2-d342f6c452eb.png">

2022-03-25 15:20 UTC, WendyPassculture commented on src/features/cheatcodes/pages/AppComponents/IconsContainer.tsx
> +          {!!isBicolor && <IconComponentBicolor />}
ah oui étrange, ok bon bien j'accepte, je n'ai rien vu d'autre je valide

2022-03-25 15:20 UTC, WendyPassculture approved these changes

2022-03-25 15:42 UTC, merged

2022-03-28 08:01 UTC, bruno-ebstein-pass-culture commented on src/features/cheatcodes/pages/AppComponents/Icons.stories.tsx
> +export default {
je trouve ça surprenant que les stories des icons soient dans le dossier des cheatcodes, je me serais attendu que ça soit dans `ui/svg/icons/`