(PC-13349) feat(CulturalSurvey): Create Thanks page
pass-culture/pass-culture-app-native pull request #2900
Opened 2022-04-13 16:14 UTC by WendyPassculture

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13349

## Checklist

I have:

- [ ] Made sure the title of my PR follows the [convention](1) `($jira) $type($scope): $summary`.
- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets.
- [ ] Attached a **ticket number** or **github dev name** for any added TODO / FIXME.
- [ ] Added new reusable components to **AppComponents** page and communicate to the team on slack.
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](2)
- [ ] Made sure translations file is up to date (`yarn translations:extract`)

## Screenshots

<img width="1800" alt="Capture d’écran 2022-04-13 à 18 13 50" src="https://user-images.githubusercontent.com/90036171/163224551-d180e5bf-27a2-4562-8054-ccf1893a6a01.png">
<img width="367" alt="Capture d’écran 2022-04-13 à 18 02 31" src="https://user-images.githubusercontent.com/90036171/163224558-2d7d78bf-3e55-4f7b-b330-d9c660781e4a.png">
<img width="400" alt="Capture d’écran 2022-04-13 à 18 02 13" src="https://user-images.githubusercontent.com/90036171/163224563-95054328-5ae8-4299-8dd9-6f51684723ce.png">
<img width="414" alt="Capture d’écran 2022-04-13 à 18 02 07" src="https://user-images.githubusercontent.com/90036171/163224564-5b10fdb1-0d11-41af-b3b7-d6b2238277eb.png">
<img width="385" alt="Capture d’écran 2022-04-13 à 18 00 58" src="https://user-images.githubusercontent.com/90036171/163224565-6c621529-a055-432c-85bf-7d482432fac8.png">

[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/doc/standards/pr-title.md
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-04-14 08:38 UTC, yorickeando commented on src/features/culturalSurvey/pages/CulturalSurveyThanks.tsx
> +      paddingBottom={theme.isDesktopViewport ? undefined : 0.01}>
Je ne pense pas que passer des props de style au composant soit tout à fait une bonne idée. 

Cette condition `isDesktopViewport` tu peux tout à fait la calculer directement dans le `GenericInfoPageWhite` et faire le calcul dedans, pas du tout besoin de passer par le composant parent pour générer du style condtionnel

2022-04-14 08:41 UTC, yorickeando commented on src/ui/components/GenericInfoPageWhite.tsx
> +    <Container fluid={props.fluid as boolean}>
J'ai du mal à comprendre le nom de cette variable, je ne vois pas du tout à quoi ça fait référence. 

Si c'est pour gérer la largeur totale, est-ce que réutiliser ce qui est fait dans GenerifInfoPage ne fonctionne pas ?
Je crois qu'il y a un `maxWidth: getSpacing(90)` . Si tu pars là-dessus, il faut juste vérifier la non-régression sur les endroits où cette page est utilisée avec des illustrations !

2022-04-14 08:42 UTC, yorickeando requested changes
Quelques petits trucs. Jolie page !!

2022-04-14 08:53 UTC, yorickeando commented
Sur les screenshots le texte est un peu loin du bouton, je pense qu'il y aura un retour graphique. Tu vois comment faire sur figma pour voir les marges attendues ?

2022-04-14 09:24 UTC, anoukhello commented on src/features/culturalSurvey/pages/__tests__/CulturalSurveyTanks.web.test.tsx
> +  it('should navigate to home when pressing Plus tard', () => {
C'est un copier-coller ce titre de test non ? Je vois pas le bouton plus tard sur la page

2022-04-14 09:24 UTC, anoukhello commented on src/features/culturalSurvey/pages/__tests__/CulturalSurveyThanks.native.test.tsx
> +    const CulturalSurveyIntroPage = render(<CulturalSurveyThanks />)
`CulturalSurveyIntroPage ` pareil c'est un cc ?

2022-04-14 09:24 UTC, anoukhello commented on src/features/culturalSurvey/pages/__tests__/CulturalSurveyThanks.native.test.tsx
> +    expect(navigateToHome).toHaveBeenCalled()
Pareil, renommer le "Plus tard" et le "LaterButton"

2022-04-14 12:27 UTC, WendyPassculture commented on src/ui/components/GenericInfoPageWhite.tsx
> +    <Container fluid={props.fluid as boolean}>
Je vais revoir un peu mais justement j'ai rajouté cette variable pour éviter d'avoir une regression, ainsi le container devient fluid (stretch) uniquement si je passe cette valeur, parce que par défaut c'est centré et il n'y avait rien pour proposer une alternative dans le cas ou on ne le veut pas centré

2022-04-14 12:28 UTC, WendyPassculture commented on src/features/culturalSurvey/pages/__tests__/CulturalSurveyTanks.web.test.tsx
> +  it('should navigate to home when pressing Plus tard', () => {
Ah oui je n'ai pas changé les titres. Je m'en charge

2022-04-15 06:13 UTC, WendyPassculture commented on src/ui/components/GenericInfoPageWhite.tsx
> +    <Container fluid={props.fluid as boolean}>
Après avoir bien investigué et testé plusieurs solution, finalement, celle que j'ai faite est mieux car dans les autres pages qui utilise GenericInfoPageWhite, le contenu est assez fourni ce qui fait que ca pousse assez facilement les marges afin que le bouton puisse prendre toute la largeur de la page. Un max-width bloque pour que ca ne s'elargisse pas trop. Mais si on met peu de texte, le contenu reste centré et le bouton s'adapte à la taille de son container.

2022-04-15 08:26 UTC, WendyPassculture commented on src/features/culturalSurvey/pages/__tests__/CulturalSurveyThanks.native.test.tsx
> +    expect(navigateToHome).toHaveBeenCalled()
Ah oui, ca c'est un oubli monumentale :D

2022-04-15 08:26 UTC, WendyPassculture commented on src/features/culturalSurvey/pages/__tests__/CulturalSurveyThanks.native.test.tsx
> +    const CulturalSurveyIntroPage = render(<CulturalSurveyThanks />)
Bien vu!

2022-04-15 08:36 UTC, yorickeando commented on src/ui/components/GenericInfoPageWhite.tsx
> +    <Container fluid={props.fluid as boolean}>
C'est juste pour baisser le bouton cette nécessité de mettre cette prop ? Est-ce que tu peux pas plutôt faire un travail sur le bouton dans le composant générique, pour qu'il soit toujours en bas à sa bonne place ?

2022-04-15 08:38 UTC, yorickeando commented on src/ui/components/GenericInfoPageWhite.tsx
> +    <Container fluid={props.fluid as boolean}>
Peut-être partiellement basé sur ce qui est fait dans ce BottomContainer dans GenericInfoPage 

<img width="628" alt="Capture d’écran 2022-04-15 à 10 37 39" src="https://user-images.githubusercontent.com/44037911/163547620-88415122-cf9d-4bc9-ad2d-3692c6a18cb9.png">

2022-04-15 14:13 UTC, yorickeando commented
Attention tu as 3 code smells relevés par SonarCloud

2022-04-19 11:42 UTC, anoukhello approved these changes

2022-04-20 07:28 UTC, merged