(PC-14454) feat(Stepper): Create Stepper V2 for identitycheck
pass-culture/pass-culture-app-native pull request #2999
Opened 2022-05-17 10:11 UTC by WendyPassculture

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14454

## Checklist

I have:

- [ ] Made sure the title of my PR follows the [convention](1) `($jira) $type($scope): $summary`.
- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets.
- [ ] Attached a **ticket number** or **github dev name** for any added TODO / FIXME.
- [ ] Added new reusable components to **AppComponents** page and communicate to the team on slack.
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](2)
- [ ] Made sure translations file is up to date (`yarn translations:extract`)

## Screenshots

<img width="365" alt="Capture d’écran 2022-05-17 à 12 05 17" src="https://user-images.githubusercontent.com/90036171/168787732-ade05f6d-091e-4637-baea-a4a0eb1bc249.png">
<img width="400" alt="Capture d’écran 2022-05-17 à 12 05 04" src="https://user-images.githubusercontent.com/90036171/168787750-ecbe7142-d329-4947-bc4f-458a7c2fa9a1.png">
<img width="380" alt="Capture d’écran 2022-05-17 à 12 04 56" src="https://user-images.githubusercontent.com/90036171/168787755-426295bb-1f43-4912-8089-fbca4b3b261d.png">
<img width="1800" alt="Capture d’écran 2022-05-17 à 12 04 46" src="https://user-images.githubusercontent.com/90036171/168787761-5e0fe922-6fbc-4e0f-88ea-9ccbbe6629d1.png">

[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/doc/standards/pr-title.md
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-05-17 13:35 UTC, anoukhello reviewed
Je veux bien savoir pourquoi la stratégie tech du ticket n'était pas adaptée :)

2022-05-17 13:35 UTC, anoukhello commented on src/features/navigation/RootNavigator/identityCheckRoutes.ts
> +  },
Les 2 versions du stepper seront identiques en testing non ? Je comprends pas l'intérêt d'avoir 2 versions si on dit qu'on affiche le bouton seulement en testing pour le moment.

2022-05-17 13:42 UTC, anoukhello commented on src/features/navigation/RootNavigator/identityCheckRoutes.ts
> +  },
Je trouve ça plus complexe que ce qui était proposé dans la stratégie tech

2022-05-17 13:43 UTC, anoukhello requested changes
Il manque le changement du titre en fonction "Voici les X étapes que tu vas devoir suivre" dans le stepper en fonction du nombre d'étapes retournées par `useIdentityCheckSteps`

2022-05-17 13:47 UTC, WendyPassculture commented on src/features/identityCheck/pages/Stepper.tsx
> +  const steps = useIdentityCheckSteps(stepsIncludePhoneValidation)
Je dois pouvoir concerver pour les 2 affichages, et j'ai créé 2 routes en concervant le même composant, c'était pour pouvoir prendre ca en considération.

2022-05-17 13:49 UTC, WendyPassculture commented on src/features/navigation/RootNavigator/identityCheckRoutes.ts
> +  },
Mais comment veux-tu conserver les deux versions sur le même build sachant que la variable d'environnement sera toujours à true pour les deux versions.

2022-05-17 14:03 UTC, anoukhello commented on src/features/identityCheck/pages/Stepper.tsx
> +  const steps = useIdentityCheckSteps(stepsIncludePhoneValidation)
Ok j'avais pas saisi qu'il fallait absolument conserver les 2 affichages en testing, sachant qu'on pourra switcher entre les 2 versions avec le ticket suivant https://passculture.atlassian.net/browse/PC-14455

2022-05-17 15:09 UTC, yorickeando commented on src/ui/svg/icons/Smartphone.tsx
> +import styled from 'styled-components/native'
Est-ce que tu peux découper en deux commits, pour faciliter la relecture : 
 
- l'ajout de l'icône (et rajouter également aux cheatcodes et à storybook)
- l'implémentation du stepper

2022-05-17 15:10 UTC, yorickeando commented on src/features/identityCheck/types.ts
> +  PHONE_VALIDATION = 'PHONE_VALIDATION',
Le reste des valeurs est en `snake_case`, attention :)

2022-05-17 15:11 UTC, yorickeando commented on src/ui/components/inputs/SearchInput.tsx
> +  const {
Est-ce que tu as vérifié que sur ce champ il était nécessaire de maintenir ce backgroundColor, ou si le background de SearchInput suffisait ?

2022-05-17 15:12 UTC, yorickeando commented on src/ui/components/inputs/SearchInput.tsx
> +  const {
C'est sur l'autre contexte d'utilisation, dans `MarkValidation` qu'il était a priori nécessaire de conserver le fond blanc, pour l'accessibilité.

2022-05-17 15:12 UTC, WendyPassculture commented on src/ui/svg/icons/Smartphone.tsx
> +import styled from 'styled-components/native'
yes

2022-05-17 15:13 UTC, WendyPassculture commented on src/features/identityCheck/types.ts
> +  PHONE_VALIDATION = 'PHONE_VALIDATION',
bien vue

2022-05-17 16:24 UTC, WendyPassculture commented on src/ui/components/inputs/SearchInput.tsx
> +  const {
Le fond est déjà blanc donc ce n'était pas nécessaire, mais je viens de me demander si le theme est dark est-ce que le champs reste blanc. Je vais tester

2022-05-18 08:38 UTC, yorickeando commented on src/features/identityCheck/useIdentityCheckSteps.tsx
> +   * TODO: Change to feature flag
Tu peux mettre un message un peu plus explicite et l'associer au numéro de ticket sur lequel on va résoudre le problème ?

ex : `TODO: (PC-14455) replace this const with result from stepperIncludesPhoneValidation value from useNextSubscriptionStep`

2022-05-18 08:40 UTC, yorickeando commented on src/features/identityCheck/useIdentityCheckSteps.tsx
> +  const stepsV1: StepConfig[] = [
Je pense qu'on peut rester sur `steps`, c'est toujours `steps` qu'on renvoie de toute façon, pas de notion de V2, seulement un `steps` complété éventuellement.

2022-05-18 08:43 UTC, yorickeando commented on src/ui/components/inputs/SearchInput.tsx
> +  const {
tu as pu avoir ta réponse ? Dans le doute, je ne mettrais rien, si jamais tu n'as pas trouvé, dans un souci d'uniformisation sur la codebase.

2022-05-18 08:46 UTC, WendyPassculture commented on src/ui/components/inputs/SearchInput.tsx
> +  const {
Oui je vais retirer car le theme dark risque de poser probleme

2022-05-18 08:50 UTC, WendyPassculture commented on src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx
> +        <LinkToComponent name="IdentityCheckStepperV2" title="Stepper V2" />
C'est un oubli j'ai retiré

2022-05-18 13:12 UTC, anoukhello approved these changes
👌

2022-05-19 09:42 UTC, merged