(PC-5853) Interdir les moins de 16 ans à s'enregistrer sur Pass Culture (Frontend)
pass-culture/pass-culture-app-native pull request #304
Opened 2021-01-04 14:48 UTC by BenStirrup

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5853

## Checklist

I have:

- [x] Made sure the title of my PR follows the convention `[PC-XXX] <summary>`.
- [ ] Made sure my feature is working on the relevant real / virtual devices.
- [x] Written **unit tests** for my feature.
- [x] Added new reusable components to the AppComponents page and communicate to the team on slack
- [ ] Added a **screenshot** for UI tickets.

## Screenshots

| \*iOS - [Phone name] | \*Android - [Phone name] |
| -------------------- | :----------------------: |
|                      |                          | 

## Deploy hard

If native code (ios/android) was modified, **after** the PR is merged, on the master branch, upgrade the **app version** (+1 patch):

- if you want an hard deployment of the testing environment, use `yarn version:testing` (this will create a commit with a tag)
- then run `git push --follow-tags`

2021-01-05 09:27 UTC, AnoukHello approved these changes
Très clair !

2021-01-05 09:27 UTC, AnoukHello commented on src/features/auth/signup/SetBirthday.test.tsx
> +    it('should log WhyAnniversary when clicking "Pourquoi" link', async () => {
Il y avait des warnings ?

2021-01-05 09:46 UTC, BenStirrup commented on src/features/auth/signup/SetBirthday.test.tsx
> +    it('should log WhyAnniversary when clicking "Pourquoi" link', async () => {
Je supprime

2021-01-05 09:48 UTC, BenStirrup commented on src/features/auth/signup/SetBirthday.tsx
> +      birthday: date ? date : '',
Je suppose que c'est pour respecter le typage `string | null`

2021-01-05 09:49 UTC, blixit requested changes
J'ai le sentiment que ta PR rajoute beaucoup trop de complexité et on perd la distinction entre composant et page sur laquelle ce dernier est utilisé.

je ne comprends pas le but d'une telle refacto, alors que la PR vise à restreindre la valeur de l'année.

2021-01-05 09:49 UTC, blixit commented on src/features/auth/signup/SetBirthday.tsx
> +    setIsComplete(validation.isComplete)
t'as vérifié sur android et iOS que le bouton continuer ne clignote pas pendant qu'on saisit la date ?

2021-01-05 09:49 UTC, blixit commented on src/features/auth/signup/SetBirthday.tsx
> +                visible={isComplete && isValid && isTooYoung}
sauf erreur, isValid et isComplete ne devraient pas être indispensable puisque si istooyoung = true, ca implique que la date est complète et valide mais supérieure à un certain seuil.

2021-01-05 09:49 UTC, blixit commented on src/libs/dates.ts
> +  else if (monthOld == monthNew && dayOld > dayNew) diffInYears--
pourquoi ne pas faire un ou logique ici sachant qu'on fait la même action dans les 2 cas ?

2021-01-05 09:49 UTC, blixit commented on src/ui/components/inputs/DateInput.test.tsx
> +        fireEvent.changeText(year, '0')
pourquoi 0 ?

2021-01-05 09:49 UTC, blixit commented on src/ui/components/inputs/DateInput.test.tsx
> +        fireEvent.changeText(year, '10000')
pourquoi 10000 ?

2021-01-05 09:49 UTC, blixit commented on src/ui/components/inputs/DateInput.test.tsx
> +      expect(FULL_DATE_VALIDATOR.isValid(date, year, month, day)).toBeTruthy()
je ne comprends pas l'intérêt de ce test

2021-01-05 09:49 UTC, blixit commented on src/ui/components/inputs/DateInput.tsx
> +  isValid: (input: number) => input >= 1 && input <= 9999,
je préfère que oldest et youngest soient mis dans des constantes plutôt qu'utiliser des nombres magiques

2021-01-05 09:49 UTC, blixit commented on src/ui/components/inputs/DateInput.tsx
> +  dateValidation.isTooOld = diffInYears ? diffInYears > 120 : false
éviter les nombres magiques 16 et 120

2021-01-05 09:49 UTC, blixit commented on src/ui/components/inputs/DateInput.tsx
> +  const isReadyToBeSubmitted =
cette notion n'a pas de sens dans ce fichier d'autant plus que tu refais le test sur la page setbirthday, un renommage s'impose pour plus de clarté, non ?

2021-01-05 09:49 UTC, blixit commented on src/ui/components/inputs/DateInput.tsx
> +  isValid(date: Date, year: number, month: number, day: number) {
cette fonction n'a plus d'intérêt si tu as sorti l'instantiation de date.

2021-01-05 09:49 UTC, blixit commented on src/ui/components/inputs/DateInput.tsx
> +        isValid={(!dateValidation.isComplete && isDayValid) || isReadyToBeSubmitted}
dans les 2 cas isDayvalid reste vrai donc pourquoi faire un test aussi long ?

2021-01-05 09:49 UTC, blixit commented on src/ui/components/inputs/PartialDateInput.tsx
> +    minWidth: lengthByChar * 20,
testé sur iOS ??

2021-01-05 10:07 UTC, BenStirrup commented on src/features/auth/signup/SetBirthday.tsx
> +  const isReadyToBeSubmitted = isComplete && isValid && !isTooYoung && !isTooOld
La date est valide dans le sens où c'est un objet Date qui correspond à une vrai date du calendrier.
Ensuite, on vérifie si la date respecte ou non d'autres conditions.

2021-01-05 10:11 UTC, BenStirrup commented on src/features/auth/signup/SetBirthday.tsx
> +    setIsTooOld(validation.isTooOld)
De cette manière React peut faire sa diff `Object.is` sur chacune des primitives pour savoir si l'état a été modifié

2021-01-05 10:14 UTC, blixit commented on src/features/auth/signup/SetBirthday.tsx
> +  const isReadyToBeSubmitted = isComplete && isValid && !isTooYoung && !isTooOld
mais du coup, on mélange le métier et l'UI.

est-ce qu'on ne gagnerait pas à transférer cette logique au sein du composant page ou faire un composant intermédiaire entre SetBirthday et DateInput pour mieux mettre en évidence cette logique ?

2021-01-05 10:15 UTC, BenStirrup commented on src/libs/dates.ts
> +  else if (monthOld == monthNew && dayOld > dayNew) diffInYears--
bien vu

2021-01-05 10:19 UTC, BenStirrup commented on src/ui/components/inputs/DateInput.test.tsx
> +        fireEvent.changeText(year, '0')
La validité des années est entre 1 et 9999

2021-01-05 10:19 UTC, BenStirrup commented on src/ui/components/inputs/DateInput.test.tsx
> +        fireEvent.changeText(year, '10000')
La validité des années est entre 1 et 9999

2021-01-05 10:21 UTC, BenStirrup commented on src/ui/components/inputs/DateInput.test.tsx
> +      expect(FULL_DATE_VALIDATOR.isValid(date, year, month, day)).toBeTruthy()
Si la fonction renvoie `false` dans certains cas, on veut aussi vérifier qu'elle renvoie `true` dans d'autres.
On sait jamais, ca pourrait être la fonction `() => false` :)

2021-01-05 10:21 UTC, BenStirrup commented on src/ui/components/inputs/DateInput.tsx
> +  isValid: (input: number) => input >= 1 && input <= 9999,
ok pour moi

2021-01-05 10:22 UTC, BenStirrup commented on src/ui/components/inputs/DateInput.tsx
> +  dateValidation.isTooOld = diffInYears ? diffInYears > 120 : false
Ok pour moi

2021-01-05 10:26 UTC, BenStirrup commented on src/ui/components/inputs/DateInput.tsx
> +  isValid(date: Date, year: number, month: number, day: number) {
On veut quand même vérifier que l'objet Date qu'on créer est valide non ? Car il est possible d'instantier une date invalide (ou plutôt, JavaScript applique un "casting" particulier si il rencontre une date qui n'existe pas, sans remonter d'erreur).

2021-01-05 10:26 UTC, BenStirrup commented on src/ui/components/inputs/DateInput.tsx
> +        isValid={(!dateValidation.isComplete && isDayValid) || isReadyToBeSubmitted}
Yes bien vu

2021-01-05 10:29 UTC, BenStirrup commented on src/ui/components/inputs/DateInput.tsx
> +        isValid={(!dateValidation.isComplete && isDayValid) || isReadyToBeSubmitted}
Ah non, je viens de me rappeler la raison : si la date ne respecte pas les conditions trop jeune ou trop vieux, on veut que tous les inputs soient rouges.

2021-01-05 10:40 UTC, BenStirrup commented on src/features/auth/signup/SetBirthday.tsx
> +  const isReadyToBeSubmitted = isComplete && isValid && !isTooYoung && !isTooOld
Ce que je peux faire, c'est ajouter deux props `minimumDate` et `maximumDate` de type `Date` à `DateInput`, qui renvoie en validation deux variables booléennes `isDateLessThanMinimum` et `isDateMoreThanMaximum`. 
De cette manière, `DateInput` n'a plus de règles métiers spécifiques à l'anniversaire.

2021-01-05 10:45 UTC, BenStirrup commented on src/ui/components/inputs/PartialDateInput.tsx
> +    minWidth: lengthByChar * 20,
Yes c'est bon.
J'ai dû faire cela car les "M" sur Android sont plus larges.

2021-01-05 11:34 UTC, blixit commented on src/features/auth/signup/SetBirthday.tsx
> +    setIsTooOld(validation.isTooOld)
quel intérêt si les 4 sont toujours modifiés simultanément ?

2021-01-05 11:37 UTC, blixit commented on src/ui/components/inputs/DateInput.tsx
> +  isValid(date: Date, year: number, month: number, day: number) {
ce que je veux dire, c'est qu'on n'est pas l'abri qu'un prochain dev change les paramètres d'instantiation de new date sans changer les paramètres de isValid qu'on voulait atomique

2021-01-05 11:44 UTC, blixit commented on src/ui/components/inputs/DateInput.tsx
> +        isValid={(!dateValidation.isComplete && isDayValid) || isReadyToBeSubmitted}
dans ce cas, il y a un souci puisque le code ne me dit pas ce que tu expliques et que même toi tu dois faire un effort pour t'en souvenir.

C'est pour ca que je pense qu'il faut trouver un moyen de splitter cette complexité.

Ma proposition serait de faire un composant RangeDateInput au-dessus de DateInput. Toute la validation liée à too old ou too young se ferait alors dans ce composant, t'en penses quoi ?

2021-01-05 11:45 UTC, blixit commented on src/ui/components/inputs/PartialDateInput.tsx
> +    minWidth: lengthByChar * 20,
ok pour moi si t'as testé

2021-01-05 11:46 UTC, blixit commented on src/ui/components/inputs/DateInput.test.tsx
> +        fireEvent.changeText(year, '0')
Du coup on pourrait définir oldest à 1. le code serait plus parlant que '0' je pense

2021-01-05 11:49 UTC, blixit commented on src/ui/components/inputs/DateInput.test.tsx
> +        fireEvent.changeText(year, '10000')
je pense que t'aurais pu redéfinir oldest et youngest plutôt que de les remplacer par des nombres magiques.

2021-01-05 11:54 UTC, blixit commented on src/ui/components/inputs/DateInput.test.tsx
> +      expect(FULL_DATE_VALIDATOR.isValid(date, year, month, day)).toBeTruthy()
oui mais les dates invalides on les connait: les fins de mois trompeuses et les années bissextiles ou non.

comment tu choisis les dates valides pertinentes pour ton test ?

2021-01-05 15:56 UTC, BenStirrup commented on src/ui/components/inputs/DateInput.test.tsx
> +      expect(FULL_DATE_VALIDATOR.isValid(date, year, month, day)).toBeTruthy()
Le 29 février par exemple. C'est juste quelques cas simples pour vérifier que la fonction renvoie `true`

2021-01-05 15:57 UTC, BenStirrup commented on src/features/auth/signup/SetBirthday.tsx
> +    setIsTooOld(validation.isTooOld)
J'ai remis comme précedemment

2021-01-06 09:54 UTC, blixit approved these changes

2021-01-06 09:58 UTC, merged