(PC-18044) feat(search): add location incitation button
pass-culture/pass-culture-app-native pull request #3786
Opened 2022-10-19 15:51 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18044

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-10-20 09:31 UTC, cedricls1 commented on src/features/search/atoms/Buttons/GeolocationButton.tsx
> +          <LabelText>Géolocalise toi</LabelText>
J'ai hésité à rendre ça plus paramétrable mais d'un autre côté il est spécifique

2022-10-20 13:21 UTC, dbenfouzari requested changes

2022-10-20 13:21 UTC, dbenfouzari commented on src/features/search/atoms/Buttons/GeolocationButton.tsx
> +  }))``
Tu ne peux pas laisser ça dans le composant

2022-10-20 13:21 UTC, dbenfouzari commented on src/features/search/components/SearchResults.tsx
> +            <GeolocationButton onPress={() => showGeolocPermissionModal()} />
```suggestion
            <GeolocationButton onPress={showGeolocPermissionModal} />
```
Ca évite de recréer une fonction à chaque render, donc ça optimise les perfs. En plus, c'est inutile de recréer :P

2022-10-20 13:21 UTC, dbenfouzari commented on src/features/search/components/__tests__/SearchResults.native.test.tsx
> +    ${'digital offer'}                                          | ${{ offerTypes: { isDigital: true, isEvent: false, isThing: false } }}
C'est un détail, mais tu n'as pas besoin de string compute ici
```suggestion
    digital offer.                                              | ${{ offerTypes: { isDigital: true, isEvent: false, isThing: false } }}
```

2022-10-21 08:00 UTC, cedricls1 commented on src/features/search/components/__tests__/SearchResults.native.test.tsx
> +    ${'digital offer'}                                          | ${{ offerTypes: { isDigital: true, isEvent: false, isThing: false } }}
Si je le retire ça casse le test

2022-10-21 08:05 UTC, dbenfouzari-pass commented on src/features/search/components/__tests__/SearchResults.native.test.tsx
> +    ${'digital offer'}                                          | ${{ offerTypes: { isDigital: true, isEvent: false, isThing: false } }}
C'est bizarre... C'est un string, non ? Je comprends pas trop comment c'est possible que ça casse :/
Mais soit, c'est du détail, on laisse tomber :D Faudra checker à l'occasion

2022-10-21 08:06 UTC, dbenfouzari-pass approved these changes
LGTM :)

2022-10-21 08:13 UTC, merged