(PC-18167) feat(search): add dates & hours filter button results
pass-culture/pass-culture-app-native pull request #3820
Opened 2022-10-26 14:34 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18167

## Checklist

I have:

- [x] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [x] Written **unit tests** native (and web when implementation is different) for my feature.
- [x] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |<img width="433" alt="Capture d’écran 2022-10-26 à 16 35 39" src="https://user-images.githubusercontent.com/78556024/198056115-5df9025f-3cd2-4ee2-b26d-bdd373d24979.png">|<img width="444" alt="Capture d’écran 2022-10-26 à 16 35 55" src="https://user-images.githubusercontent.com/78556024/198056185-470d9209-ec9a-486a-b464-e9dbcd1ea5c3.png">|
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |<img width="866" alt="Capture d’écran 2022-10-26 à 16 36 14" src="https://user-images.githubusercontent.com/78556024/198056251-b5a5daa7-f700-4a8c-933f-d020fba5a250.png">|<img width="1728" alt="Capture d’écran 2022-10-26 à 16 36 26" src="https://user-images.githubusercontent.com/78556024/198056288-705c7bef-2355-47a9-a988-91c67f5d5a1e.png">|
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-10-26 14:52 UTC, dbenfouzari-pass requested changes
Globalement très cool, mais encore de petits détails

2022-10-26 14:52 UTC, dbenfouzari-pass commented on src/features/search/components/SearchResults.tsx
> +  const hasDatesHours = params?.date || params?.timeRange
Ce n'est pas un boolean. Il est même infer en `any`. Tu peux corriger ça facilement
```suggestion
  const hasDatesHours = Boolean(params?.date || params?.timeRange)
```

2022-10-26 14:52 UTC, dbenfouzari-pass commented on src/features/search/components/__tests__/SearchResults.native.test.tsx
> +    })
Je ne comprends pas l'intérêt du `act` ici ? Tu ne fais pas de clic ou quoi

2022-10-26 14:52 UTC, dbenfouzari-pass commented on src/features/search/components/__tests__/SearchResults.native.test.tsx
> +      })
Idem ici, pas sûr de l'utilité du `act`

2022-10-26 15:14 UTC, cedricls1 commented on src/features/search/components/SearchResults.tsx
> +  const hasDatesHours = params?.date || params?.timeRange
Ah yes je l'aurai pas cru nécessaire ici mais effectivement

2022-10-26 15:18 UTC, cedricls1 commented on src/features/search/components/__tests__/SearchResults.native.test.tsx
> +    })
Si je le retire, ça génère un warning dans la console

2022-10-26 15:19 UTC, cedricls1 commented on src/features/search/components/__tests__/SearchResults.native.test.tsx
> +      })
Idem ici warning sans `act`

2022-10-27 07:39 UTC, dbenfouzari-pass approved these changes

2022-10-28 07:32 UTC, merged