Pc 18343
pass-culture/pass-culture-app-native pull request #3858
Opened 2022-11-02 16:31 UTC by dbenfouzari-pass

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-11-02 16:39 UTC, cedricls1 commented on src/features/search/pages/useShowResultsForCategory.ts
> +      dispatch({ type: 'SET_CATEGORY', payload: [pressedCategory] })
A mon avis ce `dispatch` est inutile  au vue du `useEffect` ligne 80 à 83 de `Search.tsx`

2022-11-02 16:41 UTC, dbenfouzari-pass commented on src/features/search/pages/useShowResultsForCategory.ts
> +      dispatch({ type: 'SET_CATEGORY', payload: [pressedCategory] })
Pas faux. J'ai bêtement remplacé en fait.

2022-11-03 10:04 UTC, bruno-ebstein-pass-culture commented
:meow_hype: :fire:

2022-11-03 13:09 UTC, cedricls1 requested changes

2022-11-03 13:09 UTC, cedricls1 commented on src/features/search/components/__tests__/SearchHeader.native.test.tsx
>    useSearch: () => ({ searchState: mockSearchState, dispatch: mockDispatch }),
Tu peux utiliser directement `jest.fn()`voir supprimer le `dispatch`

2022-11-03 13:09 UTC, cedricls1 commented on src/features/search/pages/__tests__/SuggestedPlaces.native.test.tsx
> +    dispatch: mockDispatch,
Idem pour le `dispatch`

2022-11-03 13:09 UTC, cedricls1 commented on src/features/search/pages/__tests__/SuggestedPlaces.web.test.tsx
> +    dispatch: mockDispatch,
Idem pour le `dispatch`

2022-11-03 13:09 UTC, cedricls1 commented on src/features/search/sections/NewOffer.tsx
>  import React, { useCallback } from 'react'
Je crois que `NewOffer` n'est plus utilisée donc à priori tu peux supprimer

2022-11-03 13:09 UTC, cedricls1 commented on src/features/search/sections/tests/NewOffer.native.test.tsx
>  import { NewOffer } from '../NewOffer'
Tu dois pouvoir supprimer aussi

2022-11-03 13:09 UTC, cedricls1 commented on src/features/search/sections/tests/analytics.native.test.tsx
> +const mockDispatch = jest.fn()
Idem pour le `dispatch`

2022-11-03 13:09 UTC, cedricls1 commented on src/features/venue/components/__tests__/VenueOffers.native.test.tsx
> -const mockStagedDispatch = jest.fn()
Idem pour le `dispatch`

2022-11-03 13:09 UTC, cedricls1 commented on src/features/venue/components/__tests__/VenueOffers.web.test.tsx
>  const mockDispatch = jest.fn()
Idem pour le `dispatch`

2022-11-03 16:39 UTC, cedricls1 approved these changes

2022-11-03 16:52 UTC, merged