(PC-18347) fix(search): default geolocation & url geolocation
pass-culture/pass-culture-app-native pull request #3899
Opened 2022-11-10 09:07 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18347

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-11-10 09:31 UTC, kopax-polyconseil commented on src/features/search/pages/Search.tsx
> +    if (!params) {
Pourquoi tout d'un coup on a une condition si on a pas de params ? Est-ce celle de SearchWrapper ? 

À quoi ça sert de déplacer le problème dans un autre useEffect qu'on execute avec une matrix plus forte ?

le useEffect est dangereux la ou il se trouve, on ne peut pas s'en affranchir ?  C'est pas possible sans useEffect ?

Quid de simplement supprimer l'effet ?

2022-11-14 14:01 UTC, kopax-polyconseil commented on src/features/search/components/SearchResults.tsx
> +  useEffect(() => {
Ce hook est que pour le web ou pas? 

Il me semble que useState provoque un re-render, on a besoin d'un rerender ? Pourquoi pas avoir une immutableRef ?

2022-11-14 14:09 UTC, cedricls1 commented on src/features/search/components/SearchResults.tsx
> +  useEffect(() => {
Yes en native c'est ok même sans le hook.

Non on n'en a pas besoin, je vais changer ça merci 👍

2022-11-14 14:38 UTC, kopax-polyconseil commented on src/features/search/pages/Search.tsx
> +  useForceAroundMeLocation()
Pourquoi 2 hook a deux endroits ?

2022-11-14 14:44 UTC, cedricls1 commented on src/features/search/pages/Search.tsx
> +  useForceAroundMeLocation()
J'ai hésité car il n'est pas que dépendant de la position :
- `usePositionChangeWillUpdateLocation` c'est le hook qui va faire la gestion quand tu viens d'une URL avec params
- `useForceAroundMeLocation` c'est plus quand tu arrives sur la recherche depuis le menu (sans param dans l'URL)
Je vais regarder pour les fusionner

2022-11-14 15:42 UTC, cedricls1 commented on src/features/search/pages/Search.tsx
> +  useForceAroundMeLocation()
Sans succès...

2022-11-14 16:57 UTC, dbenfouzari-pass requested changes
Je n'ai pas essayé de comprendre ce que ça fait exactement puisque je suis un peu éloigné du sujet, encore plus du métier, mais d'un point de vue purement code voici mon retour.

2022-11-14 16:57 UTC, dbenfouzari-pass commented on src/features/search/pages/Search.tsx
> +    }
```suggestion
    const defaultParams: Partial<SearchState> = {
      view: SearchView.Landing,
      ...(position && { locationType: LocationType.AROUND_ME, aroundRadius: MAX_RADIUS }),
    }
```

2022-11-14 16:57 UTC, dbenfouzari-pass commented on src/features/search/components/useForceAroundMeLocation.ts
> +  }
Cette partie du code devrait être dans un `useEffect`

2022-11-14 16:57 UTC, dbenfouzari-pass commented on src/features/search/components/SearchResults.tsx
> +  const initialLocationRef = useRef<LocationType | undefined>(params?.locationFilter?.locationType)
Laisse-le deviner comme un grand :)

```suggestion
  const initialLocationRef = useRef(params?.locationFilter?.locationType)
```

2022-11-14 17:16 UTC, cedricls1 commented on src/features/search/components/SearchResults.tsx
> +  const initialLocationRef = useRef<LocationType | undefined>(params?.locationFilter?.locationType)
C'est pas mieux de forcer son typage ?

2022-11-18 16:26 UTC, dbenfouzari-pass approved these changes
J'adore quand on supprime plein de code :P

2022-11-18 16:27 UTC, merged