(BSR) doc(e2e): improvement suggestions
pass-culture/pass-culture-app-native pull request #4074
Opened 2022-12-14 10:41 UTC by cedricls1

2022-12-14 11:33 UTC, kopax-polyconseil commented on e2e/config/wdio.shared.conf.ts
> +    // 'spec',
uncomment et retest stp

2022-12-14 14:03 UTC, cedricls1 commented on e2e/config/wdio.shared.conf.ts
> +    // 'spec',
C'est fait et c'était ok sur toutes les plateformes 👍

2023-01-30 16:29 UTC, kopax-polyconseil approved these changes

2023-01-30 16:30 UTC, kopax-polyconseil requested changes
Je retirerai ce bloc pour l'instant, car la configuration a changé, autant revoir les détails plus tard.

2023-01-31 14:06 UTC, kopax-polyconseil approved these changes

2023-01-31 14:56 UTC, merged