(PC-19305) ci(e2e): add useIsE2e hook
pass-culture/pass-culture-app-native pull request #4090
Opened 2022-12-16 10:50 UTC by kopax-polyconseil

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19305

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2022-12-16 16:08 UTC, dbenfouzari-pass requested changes
Juste deux petites choses, sinon ça m'a l'air bien !

2022-12-16 16:09 UTC, dbenfouzari-pass commented on src/libs/e2e/getIsE2e.web.ts
> +    return globalThis.navigator.webdriver || !!globalThis.window.webdriver
Et `!!undefined === false` aussi

2022-12-16 18:55 UTC, kopax-polyconseil commented on src/libs/e2e/getIsE2e.web.ts
> +    return globalThis.navigator.webdriver || !!globalThis.window.webdriver
on pourrait ignorer le premier ici, je suis d'accord, il apporte rien et sera pas défini 5 sec après, je commit ta proposition

2022-12-16 18:57 UTC, kopax-polyconseil commented on src/libs/e2e/getIsE2e.web.ts
> +    return globalThis.navigator.webdriver || !!globalThis.window.webdriver
ah non, il va falloir corriger, on veut le 1er pas le 2nd

2022-12-16 18:57 UTC, kopax-polyconseil commented on src/libs/e2e/getIsE2e.web.ts
> +  return globalThis.navigator.webdriver || !!globalThis.window.webdriver
en revanche ici on veut le 2nd, et le délais n'est pas utile autre que pour ce cas, donc je vois pas pourquoi on le metterai pour les 2, c'est un ugly fix workaround, je laisse ainsi

2022-12-16 19:00 UTC, kopax-polyconseil commented
@dbenfouzari-pass j'ai clarrifier ce hook si tu peux recheck @dbenfouzari-pass

2022-12-16 19:01 UTC, kopax-polyconseil commented on src/libs/e2e/getIsE2e.web.ts
> +    return globalThis.navigator.webdriver || !!globalThis.window.webdriver
J'ai fix le hook avec le bon flag

2022-12-19 08:58 UTC, dbenfouzari-pass commented on src/libs/e2e/getIsE2e.web.ts
> +    return globalThis.navigator.webdriver
```suggestion
    return !!globalThis.navigator.webdriver
```
plutôt, comme en-dessous, non ?

2022-12-19 09:00 UTC, kopax-polyconseil commented on src/libs/e2e/getIsE2e.web.ts
> +    return globalThis.navigator.webdriver
le if assure a typescript un true.

2022-12-19 09:08 UTC, dbenfouzari-pass approved these changes

2022-12-19 09:08 UTC, merged