(WIP) maildev
pass-culture/pass-culture-app-native pull request #4144
Opened 2022-12-30 09:52 UTC by kopax-polyconseil

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-01-26 09:53 UTC, pierrecanthelou approved these changes
Un peu complexe pour moi donc je laisse à quelqu'un le soin de vérifier.
Mais c'est bô :)

2023-01-27 14:09 UTC, mlachevre-pass requested changes
La PR est bien trop importante pour que je puisse valider les workflows + le ts sans laisser passer des trucs.

Je pense que le code peut être simplifié et la PR splitée

2023-01-27 14:09 UTC, mlachevre-pass commented on .github/workflows/e2e-browser-safari.yml
> +          ifconfig
pourquoi as tu besoin de voir cette ip ?

2023-01-27 14:09 UTC, mlachevre-pass commented on .github/workflows/e2e-browser-safari.yml
> +      - name: "Install and start Docker engine"
cette action est jouée dans chaque workflow, dois y avoir moyen de le mettre dans un seul workflow (avec les installs docker ect...) et d'y faire appel où tu en as besoin

2023-01-27 14:09 UTC, mlachevre-pass commented on .github/workflows/e2e-android-app.yml
> +          echo PCAPI_DOCKER_TAG=$(curl https:/backend.${{ env.ENVIRONMENT }}.passculture.team/health/api) >> $GITHUB_ENV
le tag de l'image docker n'est pas viable directement via docker plutot qu'un curl ?

2023-01-27 14:55 UTC, kopax-polyconseil commented on .github/workflows/e2e-android-browser.yml
> +  PCAPI_BASE_URL: http://10.0.2.2:6001
C'est pour le processus du script e2e et non pour l'API.

2023-01-27 14:55 UTC, kopax-polyconseil commented on .github/workflows/e2e-browser-safari.yml
> +          ifconfig
pour debug mais je vais clean

2023-01-27 14:56 UTC, kopax-polyconseil commented on .github/workflows/e2e-browser-safari.yml
> +      - name: "Install and start Docker engine"
Je ne connais pas d'autres moyen que de créé des actions, il faut un repo, c'est assez contraignant en faites, j'ai déjà eu cette discussion avec les anciens ops, on a décidé de faire comme ça et voir plus tard quand le pass commence a développer des actions

2023-01-27 14:57 UTC, kopax-polyconseil commented on .github/workflows/e2e-android-app.yml
> +          echo PCAPI_DOCKER_TAG=$(curl https:/backend.${{ env.ENVIRONMENT }}.passculture.team/health/api) >> $GITHUB_ENV
Comment avec `docker` on peut recherche le tag qu'on a besoin ?

À priori, je veux avoir un backend qui tourne sur la version de testing et staging, ceci fait l'affaire pour staging mais pour testing il manque un endpoint qui renvoi le long SHA1 du commit.

Je vais également rajouter un input pour pouvoir le set au moment du run.

2023-01-27 14:57 UTC, kopax-polyconseil commented on .github/workflows/e2e-android-app.yml
> +      - name: Show pcapi server output
pour comprendre pourquoi les tests échoue coté backend

2023-01-31 15:58 UTC, kopax-polyconseil commented
Pour info : J'ai revert le merge de `browser.chrome`, `browser.safari` et `browser.firefox`, juste pour pouvoir lancer les workflows (autrement je peux pas les lancer avant le merge master), mais je vais drop le commit qui revert avant de merge

2023-02-06 13:19 UTC, mlachevre-pass commented on .github/workflows/e2e-android-app.yml
> +        uses: 'google-github-actions/auth@v0'
ce serait pas mal d'utiliser la v1 (la PR est en cours sur pass-culture-main)

2023-02-06 13:23 UTC, mlachevre-pass commented on e2e/generate-env.sh
> +SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
je suis pas sur de comprendre pourquoi tu cd + pwd alors que dirname te donne deja le chemin du fichier que tu veux obtenir

2023-02-06 13:49 UTC, mlachevre-pass commented on .github/workflows/e2e-android-app.yml
> +          docker-compose -f e2e/docker-compose-e2e.yml ps
Post debug cette ligne n'est plus utile il me semble

2023-02-07 09:12 UTC, kopax-polyconseil commented on e2e/generate-env.sh
> +SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
Hmm, ok j'utilise ce oneliner pour obtenir le path d'un fichier en bash depuis longtemps sans jamais l'avoir remis en question, surement que ta solution est meilleur.

2023-02-07 09:14 UTC, kopax-polyconseil commented on e2e/generate-env.sh
> +eval "$(cat "${SCRIPT_DIR}/.env.local.secret.tpl" | sed 's/"/+++/g'|sed  's/^\(.*\)$/echo "\1"/')" |sed 's/+++/"/g'|sed 's;\\";";g' > "${SCRIPT_DIR}/.env.local.secret"
- `sed 's/"/+++/g'` -> remplace les doubles quotes `"` par des `+++` 
- `sed  's/^\(.*\)$/echo "\1"/')"` -> prend tout la ligne et l'echo (ce qui va injecté les ENV la ou on a des place holders)
- `sed 's/+++/"/g'` -> remet les doubles quotes
- `sed 's/+++/"/g'|sed 's;\\";";g'` -> corrige l'échappement.
Si tu découpe les étapes et supprime le ` > "${SCRIPT_DIR}/.env.local.secret"`, tu peux print les différentes étapes

2023-02-07 09:19 UTC, kopax-polyconseil commented on .github/workflows/e2e-android-app.yml
> +        uses: 'google-github-actions/auth@v0'
Lien de la PR

2023-02-07 10:42 UTC, mlachevre-pass commented on .github/workflows/e2e-browser.yml
> +      - name: Slack failure notification
une action est disponible pour les notfis slack https://github.com/marketplace/actions/slack-send, une doc est dispo en interne pour l'implémentation

2023-02-07 10:43 UTC, mlachevre-pass commented on .github/workflows/e2e-android-app.yml
> +        uses: 'google-github-actions/auth@v0'
envoyé en MP

2023-02-07 10:46 UTC, mlachevre-pass commented on e2e/generate-env.sh
> +eval "$(cat "${SCRIPT_DIR}/.env.local.secret.tpl" | sed 's/"/+++/g'|sed  's/^\(.*\)$/echo "\1"/')" |sed 's/+++/"/g'|sed 's;\\";";g' > "${SCRIPT_DIR}/.env.local.secret"
apres test local, je ne vois pas l'utilité de : 
```sed 's/"/+++/g'``` ```sed 's/+++/"/g'``` et ```sed 's/+++/"/g'|sed 's;\\";";g'```
je loupe peut etre qqch

2023-02-07 13:24 UTC, kopax-polyconseil commented on .github/workflows/e2e-browser.yml
> +      - name: Slack failure notification
Sur ce point, ce n'est même pas claire les rapports attendu, j'avais un détails, mais @apibrac  ne trouve pas ça utile. Il suffit de cliquer sur le job pour voir pourquoi ça a fail. Moi je trouve ça pratique justement car on ne clique pas et tant que les tests sont flacky en CI, ça permet d'avoir un suivi rapide, après il faudrait surement discuter de ce qu'on attend sur slack avant d’entamer des modifs.

2023-02-07 13:31 UTC, apibrac commented on .github/workflows/e2e-browser.yml
> +      - name: Slack failure notification
Dans un tel cas je conseille de commencer par la version minimale : ce qui compte pour cette notification c'est d'indiquer un fail et le lien pour avoir le détail.
Et ajouter le détail directement dans la notification **plus tard, comme une nouvelle feature**, le jour où c'est évident que c'est utile de l'ajouter.
ça évite d'ajouter de la compléxité trop tôt et ça permet de se concentrer sur l'essentiel, en faisant simple

2023-02-08 10:42 UTC, mlachevre-pass approved these changes
Beau boulot, le refacto a permis d'éclaircir pas mal la PR. Un deuxième Ops va regardé la PR afin d'avoir un oeil supplémentaire

2023-02-08 14:45 UTC, kopax-polyconseil commented on e2e/docker-compose-e2e.yml
> +    depends_on:
```
dka@dka:[~/workspace/github.com/pass-culture/pass-culture-app-native (maildev)]: docker ps
CONTAINER ID   IMAGE                                                                                             COMMAND                  CREATED       STATUS                   PORTS                    NAMES
c0b6cfb82186   europe-west1-docker.pkg.dev/passculture-infra-prod/pass-culture-artifact-registry/pcapi:224.0.3   "/entrypoint.sh src/…"   6 hours ago   Up 2 hours (unhealthy)   0.0.0.0:6001->6001/tcp   pc-api-e2e
ccd0c354564e   cimg/postgres:12.9-postgis                                                                        "docker-entrypoint.s…"   7 days ago    Up 2 hours (healthy)     0.0.0.0:6432->5432/tcp   pc-postgres-e2e
41c7eb756d8f   redis:7-alpine                                                                                    "docker-entrypoint.s…"   7 days ago    Up 2 hours (healthy)     0.0.0.0:7579->6379/tcp   pc-redis-e2e
```

J'ai rajouté ça histoire d'avoir un health check test sur pcapi (qui manquait au docker-compose du repo main), mais le `unhealthy`, me laisse penser que c'est pas ça

2023-02-08 14:46 UTC, kopax-polyconseil commented on e2e/docker-compose-e2e.yml
> +    depends_on:
```
dka@dka:[~/workspace/github.com/pass-culture/pass-culture-app-native (maildev)]: docker inspect c0b6cfb82186
[
    {
        "Id": "c0b6cfb8218659250b1f9af387f5d4b7dacbd20c4555712bb2809351b53f77c8",
        "Created": "2023-02-08T08:38:06.312813861Z",
        "Path": "/entrypoint.sh",
        "Args": [
            "src/pcapi/app.py"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 16968,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-02-08T12:55:30.766480783Z",
            "FinishedAt": "2023-02-08T12:55:29.158603336Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 653,
                "Log": [
                    {
                        "Start": "2023-02-08T15:45:25.086605503+01:00",
                        "End": "2023-02-08T15:45:25.164118542+01:00",
                        "ExitCode": 127,
                        "Output": "/bin/sh: 1: curl: not found\n"
                    },
                    {
                        "Start": "2023-02-08T15:45:35.166388153+01:00",
                        "End": "2023-02-08T15:45:35.241112957+01:00",
                        "ExitCode": 127,
                        "Output": "/bin/sh: 1: curl: not found\n"
                    },
etc....
``` 

Ouai donc c'est pas ça :p

2023-02-08 15:57 UTC, jroussel-pass approved these changes
Une fois mes remarques corrigées, je pense qu'on pourra se dire qu'on a une v0 :)

2023-02-08 15:57 UTC, jroussel-pass commented on .github/workflows/e2e-android-app.yml
> +          npm install --chromedriver_version="${{ matrix.chromedriverVersion }}
Il n'y a pas une typo ici ?

2023-02-08 15:57 UTC, jroussel-pass commented on .github/workflows/e2e-android-browser.yml
> +          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_E2E_TOKEN }}
Ici, utilise la variable SLACK_BOT_TOKEN, c'est une variable d'organisation qu'on gère au niveau de l'orga github et qui est la même partout. Comme ça le jour où il y a un pb de sécurité ou autre, on aura à la changer à un seul endroit pour que tous les projects aient la nouvelle valeur.

Pense aussi à inviter le bot "Github Messages" sur les channels C04D6R9MQKS et C04EU7U4JTE

2023-02-08 15:57 UTC, jroussel-pass commented on .github/workflows/e2e-browser.yml
> +          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_E2E_TOKEN }}
Même remarque

2023-02-08 15:57 UTC, jroussel-pass commented on .github/workflows/e2e-ios-browser.yml
> +          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_E2E_TOKEN }}
idem

2023-02-08 16:56 UTC, merged