(PC-18978) feat(offerDuo): Remove filter OfferType, and make it work only for OfferDuo (wording as Duo)
pass-culture/pass-culture-app-native pull request #4184
Opened 2023-01-09 15:55 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18978

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-01-10 12:00 UTC, cedricls1 requested changes

2023-01-10 12:00 UTC, cedricls1 commented on src/features/search/components/sections/OfferDuo/OfferDuo.native.test.tsx
> +  it('should render OfferDuo with Activé description', () => {
En relisant ton test je me suis rendu compte d'un oubli :
- Le texte Activé sur le filtre Duo dans la page de filtre générale doit être affiché uniquement si le toggle Duo est activé

2023-01-10 12:00 UTC, cedricls1 commented on src/features/search/helpers/useFilterCount/useFilterCount.test.ts
> +    ${'sixFilters'}                  | ${fiveFilters}                               | ${5}
`${'fiveFilters'}`

2023-01-10 12:00 UTC, cedricls1 commented on src/features/search/helpers/useFilterCount/useFilterCount.ts
> +    priceRange: _priceRange,
Ici j'aurai laissé `priceRange`

2023-01-10 12:00 UTC, cedricls1 commented on src/features/search/helpers/useFilterCount/useFilterCount.ts
> +  const priceRange = _priceRange ?? [0, maxPrice]
Et du coup ici :
`const currentPriceRange = priceRange ?? [0, maxPrice]`

2023-01-10 12:00 UTC, cedricls1 commented on src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx
> +  const ToggleOfferDuo = useCallback(
renderToggleOfferDuo ?
un `useCallback` qui aurait un nommage de composant, je ne sais pas si c'est idéal (vive les codes smells)

2023-01-10 12:00 UTC, cedricls1 commented on src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx
> +      hideModal()
Je crois que si tu le positionnes avant le `navigate` ça peut t'éviter un warning sur émulateur

2023-01-10 13:20 UTC, YassinL commented on src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx
> +  const ToggleOfferDuo = useCallback(
J'ai pris exemple sur ce que à fait Donovan dans `CategoriesModal`, par exemple `CategoriesController` je peux le rename pareil ou bien `renderToggleOfferDuo` c'est très bien aussi

2023-01-10 14:17 UTC, cedricls1 commented on src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx
> +  const ToggleOfferDuo = useCallback(
Ah oui c'est vrai, du coup tu peux utiliser rester conforme en utilisant `ToggleOfferDuoController` pour satisfaire Sonar 👀

2023-01-10 16:06 UTC, YassinL commented on src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx
> +  const ToggleOfferDuo = useCallback(
[709980c](https://github.com/pass-culture/pass-culture-app-native/pull/4184/commits/709980c9bf2929dfdbe2b4cf1570d1b9a42d008c)

2023-01-10 16:17 UTC, cedricls1 commented on src/features/search/components/sections/OfferDuo/OfferDuo.native.test.tsx
> +  return render(reactQueryProviderHOC(<OfferDuo />))
ça ne fonctionne pas si tu utilises juste : `return render(<OfferDuo />)` ?

2023-01-10 17:18 UTC, YassinL commented on src/features/search/components/sections/OfferDuo/OfferDuo.native.test.tsx
> +  return render(reactQueryProviderHOC(<OfferDuo />))
effectivement ça fonctionne [8081a84](https://github.com/pass-culture/pass-culture-app-native/pull/4184/commits/8081a84625aea5a4be510e9702d18e11927c591d)

2023-01-11 07:34 UTC, cedricls1 approved these changes

2023-01-11 07:34 UTC, cedricls1 commented on src/features/search/components/sections/OfferDuo/OfferDuo.native.test.tsx
> +  // eslint-disable-next-line local-rules/no-react-query-provider-hoc
Du coup tu n'as plus besoin de ce commentaire :)

2023-01-11 08:34 UTC, YassinL commented on src/features/search/components/sections/OfferDuo/OfferDuo.native.test.tsx
> +  // eslint-disable-next-line local-rules/no-react-query-provider-hoc
[dbf7198](https://github.com/pass-culture/pass-culture-app-native/pull/4184/commits/dbf7198a57e1040a3037f94eeb793217c03f640c)

2023-01-11 09:12 UTC, merged