(PC-19509) feat(BookingDetailsCancel): display an expiration date message if the booking is digital
pass-culture/pass-culture-app-native pull request #4271
Opened 2023-01-23 13:32 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19509

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-01-23 17:30 UTC, pierrecanthelou commented on src/features/bookings/helpers/expirationDateUtils.ts
> +export const formattedExpirationDate = (dateCreated: string) => {
Ajouter les cas d'erreurs dateCreated === '', dateCreated === null ou undefined

2023-01-23 17:30 UTC, pierrecanthelou commented on src/features/bookings/components/BookingDetailsCancelButton.tsx
> +    const expirationDateMessage = `Ta réservation expirera le ${expirationDate}`
Quid si expirationDate c'est '' ou 'undefined'

2023-01-24 08:24 UTC, cedricls1 commented on src/features/bookings/components/BookingDetailsCancelButton.native.test.tsx
> +  it('should display button if confirmationDate is null and an expiration date message if isBookingIsDigital', () => {
should display cancel button and expiration date message when confirmation date is null and that's it a digital booking

2023-01-24 08:24 UTC, cedricls1 commented on src/features/bookings/components/BookingDetailsCancelButton.native.test.tsx
> +  it('should display only an expiration date message if is not still cancellable and if the booking is digital', () => {
should display only an expiration date message when the booking is digital and is not still cancellable

2023-01-24 08:24 UTC, cedricls1 commented on src/features/bookings/components/BookingDetailsCancelButton.tsx
> +  const isBookingIsDigital = booking.stock.offer.isDigital === true && !booking.expirationDate
`const isDigitalBooking = booking.stock.offer.isDigital === true && !booking.expirationDate`

2023-01-24 08:24 UTC, cedricls1 commented on src/features/bookings/helpers/expirationDateUtils.ts
> +export const formattedExpirationDate = (dateCreated: string) => {
D'après le fichier API `dateCreated` ne peut pas être `null` ou `undefined` par contre

2023-01-24 08:24 UTC, cedricls1 commented on src/features/bookings/helpers/expirationDateUtils.test.ts
> +      const formattedExpirationDateExpected = '18/02/2023'
const expectedFormattedExpirationDate = '18/02/2023'

et tu peux prévoir le test pour une string vide

2023-01-24 13:38 UTC, pierrecanthelou commented on src/features/bookings/helpers/expirationDateUtils.ts
> +export const formattedExpirationDate = (dateCreated: string) => {
@cedricls1 @YassinL Est-ce que c'est gênant de tester, surtout quand on voit le bug sur la recherche ?
:)

2023-01-24 13:49 UTC, pierrecanthelou requested changes

2023-01-24 13:49 UTC, pierrecanthelou commented on src/features/bookings/components/ActivationCodeButton.tsx
> +export const ActivationCodeButton = ({ onTerminate, fullWidth }: ActivationCodeButtonProps) => {
Ce serait peut-être bien de mettre des valeurs par défaut non ?

2023-01-24 13:49 UTC, pierrecanthelou commented on src/features/bookings/components/BookingExpiration.tsx
> +export const BookingExpiration = ({ renderButton, expirationDate }: BookingExpirationProps) => {
Tu peux essayer avec un children :p  ?

2023-01-24 13:49 UTC, pierrecanthelou commented on src/features/bookings/components/BookingExpiration.tsx
> +      {renderButton()}
```suggestion
      {children}
```

2023-01-24 13:49 UTC, pierrecanthelou commented on src/features/bookings/components/BookingExpiration.tsx
> +  const expirationDateMessage = `Ta réservation expirera le ${expirationDate}`
Est-ce qu'il y a un test sur le contenu de expirationDate avant qu'il soit mis en props ?

2023-01-24 14:49 UTC, YassinL commented on src/features/bookings/components/BookingExpiration.tsx
> +  const expirationDateMessage = `Ta réservation expirera le ${expirationDate}`
Je dirai que oui je le test déjà dans `expirationDateUtils.test.ts` et dans la fonction `formattedExpirationDate`, ou peut être tu demandes si je check si c'est bien une date qu'on me retourne ?

2023-01-24 15:00 UTC, YassinL commented on src/features/bookings/components/ActivationCodeButton.tsx
> +export const ActivationCodeButton = ({ onTerminate, fullWidth }: ActivationCodeButtonProps) => {
Je ne savais pas exactement les valeurs par défault mais je peux en mettre une pour `fullWidth = false`

2023-01-24 15:47 UTC, cedricls1 commented on src/features/bookings/components/BookingDetailsCancelButton.tsx
> +  const formattedConfirmationDate = formatToCompleteFrenchDate(
Je préfère que tu utilises :
  const formattedConfirmationDate = booking.confirmationDate ? formatToCompleteFrenchDate(
    new Date(booking.confirmationDate),
    false
  ) : ''

2023-01-24 16:50 UTC, YassinL commented on src/features/bookings/components/BookingDetailsCancelButton.tsx
> +  const formattedConfirmationDate = formatToCompleteFrenchDate(
[d529948](https://github.com/pass-culture/pass-culture-app-native/pull/4271/commits/d529948f161015ec2cf4d3bff436dd9c9611f0a6)

2023-01-24 16:50 UTC, YassinL commented on src/features/bookings/components/BookingExpiration.tsx
> +  const expirationDateMessage = `Ta réservation expirera le ${expirationDate}`
[d529948](https://github.com/pass-culture/pass-culture-app-native/pull/4271/commits/d529948f161015ec2cf4d3bff436dd9c9611f0a6)

2023-01-25 08:53 UTC, pierrecanthelou approved these changes
Bien ;)

2023-01-25 09:58 UTC, cedricls1 approved these changes

2023-01-25 09:58 UTC, cedricls1 commented on src/features/bookings/helpers/expirationDateUtils.test.ts
> +    it('should return undefined if dateCreated is an empty string', () => {
C'est plus `should return an empty string when dateCreated is an empty string` mais c'est du détail

2023-01-25 11:13 UTC, merged