(PC-19822) feat(Hit): display nativeCategory (subCatgeory) label instead of categeory label
pass-culture/pass-culture-app-native pull request #4277
Opened 2023-01-23 17:50 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19822

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-01-24 13:30 UTC, pierrecanthelou requested changes

2023-01-24 13:30 UTC, pierrecanthelou commented on src/features/search/components/Hit/Hit.tsx
> +  const nativeCategory = getNativeCategoryFromEnum(data, nativeCategoryId)
Salut Yassin, alors si c'est une seule catégorie ici qui est retournée...

2023-01-24 13:30 UTC, pierrecanthelou commented on src/features/search/components/Hit/Hit.tsx
>          <Body ellipsizeMode="tail" numberOfLines={1}>
```suggestion
        {nativeCategory?.value?.length>0 && <Body ellipsizeMode="tail" numberOfLines={1}>
```

2023-01-24 13:30 UTC, pierrecanthelou commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +  return data?.nativeCategories.find((nativeCategory) => nativeCategory.name === enumValue)
```suggestion
  return data?.nativeCategories.findFirst((nativeCategory) => nativeCategory.name === enumValue)?.value
```

2023-01-24 13:30 UTC, pierrecanthelou commented on src/features/search/components/Hit/Hit.tsx
> +  const nativeCategory = getNativeCategoryFromEnum(data, nativeCategoryId)
Et je me dis que le nom qui se termine par enum cela lie la fonction à un détail alors que ce que tu veux c'est "le nom de la categoryId" non ?

2023-01-24 15:29 UTC, YassinL commented on src/features/search/components/Hit/Hit.tsx
>          <Body ellipsizeMode="tail" numberOfLines={1}>
Cela ne fonctionne pas car `nativeCategory` est possiblement `undefined` ou `null` mais je peux faire ça : 
`!!(nativeCategory && nativeCategory.value && nativeCategory.value.length) &&` 
ou `nativeCategory && nativeCategory.value && nativeCategory.value.length ? ... : undefined`
mais dans le code on a tendance à préférer la première solution

2023-01-24 15:54 UTC, YassinL commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +  return data?.nativeCategories.find((nativeCategory) => nativeCategory.name === enumValue)
la fonction que j'utilise ici était déjà implémenter dans le code elle permet de récupérer la totalité de l'objet, je ne pense pas que je puisse l'utiliser car elle est réutiliser dans une fonction plus de `categoriesHelpers` mais je peux créer une nouvelle fonction si nécessaire pour récupérer seulement la value

2023-01-24 15:55 UTC, YassinL commented on src/features/search/components/Hit/Hit.tsx
> +  const nativeCategory = getNativeCategoryFromEnum(data, nativeCategoryId)
Idem pour le nom de la fonction, c'était déjà une fonction implémenté et déjà utilisé pour récupérer l'objet

2023-01-24 17:35 UTC, YassinL commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +  return data?.nativeCategories.find((nativeCategory) => nativeCategory.name === enumValue)
[858ce56](https://github.com/pass-culture/pass-culture-app-native/pull/4277/commits/858ce5636112fbc5629081def3ce159de88518a9)

2023-01-24 22:08 UTC, YassinL commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +  return data?.nativeCategories.find((nativeCategory) => nativeCategory.name === enumValue)
[50d24ed](https://github.com/pass-culture/pass-culture-app-native/pull/4277/commits/50d24ed2bc66c4528a92b108c7534e4f8057e015)

2023-01-25 08:05 UTC, dbenfouzari-pass commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +  return data?.nativeCategories.find((nativeCategory) => nativeCategory.name === enumValue)
@pierrecanthelou d'où est-ce que tu sors `JavaScript.Array.findFirst` ?
`Array.find` retourne déjà un seul item de toutes manières.

2023-01-25 08:12 UTC, dbenfouzari-pass requested changes

2023-01-25 08:12 UTC, dbenfouzari-pass commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +}
Tu dupliques inutilement du code.
Tu pourrais faire 
```suggestion
export function getNativeCategoryValue(
  data: SubcategoriesResponseModelv2 | undefined,
  enumValue: NativeCategoryIdEnumv2
) {
  return getNativeCategoryFromEnum(data, enumValue)?.value
}
```

2023-01-25 08:12 UTC, dbenfouzari-pass commented on src/features/search/components/NativeCategoryValue/NativeCategoryValue.tsx
> +  return (nativeCategoryValue?.length ?? 0) > 0 ? (
Super obscur...
```suggestion
return !!nativeCategoryValue ? (
```
ou même si tu préfères
```suggestion
return Boolean(nativeCategoryValue) ? (
```

2023-01-25 08:12 UTC, dbenfouzari-pass commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +}
Par ailleurs, tu n'utilises cette fonction qu'une seule fois et disons-le, elle n'est pas très utile.
Tu pourrais simplement, à l'endroit où tu l'utilises aujourd'hui, faire un 
```ts
const { value } = getNativeCategory(data, nativeCategoryId) || {}
```
et supprimer cet helper.

Ça ne complexifie pas tellement le code, et ça évite un énième helper.

2023-01-25 08:14 UTC, dbenfouzari-pass commented on src/features/search/components/NativeCategoryValue/NativeCategoryValue.tsx
> +  return (nativeCategoryValue?.length ?? 0) > 0 ? (
Puisque `nativeCategoryValue` peut être `null | undefined | string` ça te gère tous les cas, même celui du `string` vide (je ne pense pas qu'une telle chose puisse arriver mais puisque tu tiens à le vérifier avec le `.length`...)

2023-01-25 09:08 UTC, pierrecanthelou commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +}
Comme tu veux tu choisis :p

2023-01-25 09:08 UTC, pierrecanthelou commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +  return data?.nativeCategories.find((nativeCategory) => nativeCategory.name === enumValue)
@dbenfouzari-pass Au temps pour moi !

2023-01-25 09:56 UTC, pierrecanthelou approved these changes

2023-01-25 09:58 UTC, pierrecanthelou approved these changes

2023-01-25 09:59 UTC, pierrecanthelou approved these changes

2023-01-25 13:28 UTC, dbenfouzari-pass requested changes

2023-01-25 13:28 UTC, dbenfouzari-pass commented on src/features/search/components/Hit/Hit.tsx
> +  const { data } = useSubcategories()
Tu importes et utilises `useSubcategories` uniquement pour le composant `<NativeCategoryValue />`.
Tu pourrais pas plutôt faire l'import dans `<NativeCategories />` ?

2023-01-25 13:28 UTC, dbenfouzari-pass commented on src/features/search/components/NativeCategoryValue/NativeCategoryValue.tsx
> +  const { value } = getNativeCategoryFromEnum(data, nativeCategoryId) || {}
Si tu suis ma recommandation de dessus tu pourrais avoir 
```suggestion
  const { data } = useSubcategories()
  const { value } = getNativeCategoryFromEnum(data, nativeCategoryId) || {}
```

2023-01-25 13:41 UTC, YassinL commented on src/features/search/components/Hit/Hit.tsx
> +  const { data } = useSubcategories()
Je pourrai, après je voulais que le composant reste le plus générique possible.

2023-01-25 14:04 UTC, YassinL commented on src/features/search/components/Hit/Hit.tsx
> +  const { data } = useSubcategories()
@dbenfouzari-pass

2023-01-25 16:24 UTC, dbenfouzari-pass commented on src/features/search/components/Hit/Hit.tsx
> +  const { data } = useSubcategories()
Il n'est pas très générique, puisqu'il attend l'entièreté de l'objet `data` qui est de type `SubcategoriesResponseModelv2`. Dans tous les cas il a cette donnée alors...

2023-01-25 16:30 UTC, dbenfouzari-pass approved these changes

2023-01-26 08:27 UTC, dbenfouzari-pass approved these changes

2023-01-26 09:20 UTC, merged