(PC-19725) feat(search): use close and back buttons in all search filters modals
pass-culture/pass-culture-app-native pull request #4294
Opened 2023-01-25 14:39 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19725

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-01-25 15:37 UTC, cedricls1 commented
La duplication est dû à l'utilisation du composant modal

2023-01-25 15:58 UTC, dbenfouzari-pass requested changes

2023-01-25 15:58 UTC, dbenfouzari-pass commented on src/features/search/components/sections/DateHour/DateHour.tsx
> +export const DateHour: FunctionComponent<Props> = ({ onClose }) => {
```suggestion
export const DateHour = ({ onClose }: Props) => {
```

il vaut mieux laisser TypeScript `infer` le retour

2023-01-25 15:58 UTC, dbenfouzari-pass commented on src/features/search/components/sections/Location/Location.tsx
> +export const Location: FunctionComponent<Props> = ({ onClose }) => {
Même remarque : laisser TypeScript infer

2023-01-25 16:20 UTC, cedricls1 commented on src/features/search/components/sections/DateHour/DateHour.tsx
> +export const DateHour: FunctionComponent<Props> = ({ onClose }) => {
ça me va après cette façon de faire est quand même pas mal utilisée (enfin parmi d'autres).
Il faudrait peut être mettre à l'ordre du jour d'une synchro front pour tenter d'harmoniser (si ça n'a pas déjà été fait, il faudrait que je re-check les docs)

2023-01-26 12:17 UTC, dbenfouzari-pass commented on src/features/search/components/sections/DateHour/DateHour.tsx
> +export const DateHour: FunctionComponent<Props> = ({ onClose }) => {
C'est la nouvelle best practice (nouvelle puis 2 ans je crois)

2023-01-26 12:40 UTC, merged