(PC-19824) feat(search): add native category in autocomplete
pass-culture/pass-culture-app-native pull request #4301
Opened 2023-01-26 14:02 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19824

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-01-26 16:28 UTC, YassinL commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +export function isAssociatedNativeCategoryToCategory(
Pour faire ça tu peux utiliser un some() : 
```js
export function isAssociatedNativeCategoryToCategory(data, categoryId, nativeCategoryId) {
  if (!data) {
    return false;
  }

  return data.subcategories.some(
    (subcategory) =>
      subcategory.searchGroupName === categoryId &&
      subcategory.nativeCategoryId === nativeCategoryId
  );
}
```

2023-01-26 16:35 UTC, dbenfouzari-pass commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +export function isAssociatedNativeCategoryToCategory(
Effectivement.
Première amélioration très simple:
```
return associatedNativeCategory.length > 0
```

Et la seconde, la meilleure, est celle que te propose @YassinL

2023-01-26 16:39 UTC, dbenfouzari-pass requested changes
Un petit détail, et le point que relève @YassinL

2023-01-26 16:39 UTC, dbenfouzari-pass commented on src/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.tsx
> +    nativeCategories.length > 0 ? nativeCategories[0].value : undefined
```suggestion
const mostPopularNativeCategoryId = nativeCategories[0]?.value
```

2023-01-27 08:16 UTC, cedricls1 commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +export function isAssociatedNativeCategoryToCategory(
Je ne l'avais jamais rencontré avant mais effectivement c'est pas mal merci :)

2023-01-27 08:18 UTC, cedricls1 commented on src/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.tsx
> +    nativeCategories.length > 0 ? nativeCategories[0].value : undefined
👀  bien vu

2023-01-27 08:44 UTC, YassinL approved these changes

2023-01-27 09:45 UTC, dbenfouzari-pass commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +export function isAssociatedNativeCategoryToCategory(
Alors je te conseille d'aller checker la doc de `Array.some` et `Array.every` qui sont très pratiques :D

2023-01-27 09:45 UTC, dbenfouzari-pass approved these changes

2023-01-27 09:47 UTC, merged