(PC-20178) feat(search): use perform search log rather than use landing category log
pass-culture/pass-culture-app-native pull request #4331
Opened 2023-01-31 16:36 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20178

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-02-02 11:05 UTC, YassinL approved these changes

2023-02-03 17:01 UTC, pierrecanthelou requested changes

2023-02-06 08:24 UTC, cedricls1 commented on src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
>        switch (filterBehaviour) {
Je me retrouve avec une erreur d'hook non utilisable dans une callback sauf que j'ai besoin du state additionnel de la callback. A dispo pour te montrer

2023-02-06 13:49 UTC, pierrecanthelou approved these changes

2023-02-06 13:49 UTC, pierrecanthelou commented on src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
>        switch (filterBehaviour) {
J'ai pas le courage là maintenant mais si on fait l'atelier sur le refacto ce sera dedans :)
Donc en l'état change rien

2023-02-06 13:58 UTC, merged