(PC-17790) feat(SearchResult): optimization performance with RecyclerListView
pass-culture/pass-culture-app-native pull request #4375
Opened 2023-02-07 16:57 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-02-28 15:02 UTC, YassinL commented
Le Coverage du ListFooterComponent est à 0.0% comme je l'expliquais dans la description il est utilisé seulement en web (pour l'instant) du coup j'ai crée un fichier `.web`, malheureusement il n'est pas visible dans sonar.

2023-02-28 15:24 UTC, dbenfouzari-pass commented
Je regarderai mieux demain mais pour moi si on enlève des fonctionnalités la PR devient irrecevable.
L'accessibilité c'est très important, il ne faut pas la négliger.

Demain je switcherai sur ta branche pour essayer de comprendre ce que tu n'as pas réussi à faire.

2023-02-28 16:47 UTC, cedricls1 commented
Je pense que pour le bouton `Afficher plus de résultats` en native c'est pas très grave car c'est un toggle que tu peux faire apparaître uniquement en web qui déclenche son apparition à priori (à confirmer côté UX).
Sinon sur la structure du code je ferai un dossier dans `search/components` pour chacun des nouveaux composants que tu as mis dans le dossier `SearchResults`.
Tu peux aussi essayer de transformer `ListFooterComponent.tsx` en `ListFooterComponent.web.tsx` sachant qu'il ne sera utile qu'en web (ça augmentera potentiellement ton coverage).
Je te fais la revue du code demain :)

2023-03-01 08:29 UTC, cedricls1 commented
Pour le nommage des composants je serais plus tenter par `ListFooter`, `ListHeader` et `List` (vu qu'elles sont dans la feature search comme on a renommé les modals). Mais d'un autre côté ça fait nom très générique mais dans ce cas là j'harmoniserai le tout (`SearchList`, `SearchListHeader`, `SearchListFooter`)

2023-03-02 10:50 UTC, dbenfouzari-pass requested changes

2023-03-02 10:50 UTC, dbenfouzari-pass commented on src/features/search/components/NoSearchResults/NoSearchResult.tsx
> +  ...(theme.isDesktopViewport ? {} : { marginTop: -(theme.tabBar.height + getSpacing(10)) }),
```suggestion
  ...(theme.isMobileViewport && { marginTop: -(theme.tabBar.height + getSpacing(10)) }),
```

2023-03-13 16:42 UTC, cedricls1 commented on src/features/search/components/SearchResults/SearchListHeader.tsx
> +  const logActivateGeolocfromSearchResults = useCallback(() => {
le `useCallback` est utile ici sans dépendance ?

2023-03-13 16:42 UTC, cedricls1 commented on src/features/search/components/SearchResults/SearchListHeader.tsx
> +  ...(nbHits > 0 ? { paddingBottom: getSpacing(4) } : {}),
`...(nbHits > 0 && { paddingBottom: getSpacing(4) }),`

2023-03-14 07:59 UTC, YassinL commented on src/features/search/components/SearchResults/SearchListHeader.tsx
> +  const logActivateGeolocfromSearchResults = useCallback(() => {
Bon point, pas vraiment je vais sortir la fonction du composant et retirer le useCallBack 👍

2023-03-14 08:53 UTC, cedricls1 commented
@YassinL Pour ton coverage vu que `SearchListFooter` sert juste en web tu peux le renommer `SearchListFooter.web.tsx`, je pense que tu vas améliorer ton score de coverage.

2023-03-14 09:29 UTC, dbenfouzari-pass requested changes

2023-03-14 09:29 UTC, dbenfouzari-pass commented on src/features/search/components/SearchListHeader/SearchListHeader.tsx
> +  }
En vrai ici je ferai ça
```suggestion
export const SearchListHeader: React.FC<SearchListHeaderProps> = ({ nbHits }) => {
  const { position, showGeolocPermissionModal } = useGeolocation()
  const { userData } = useSearchResults()
  const { params } = useRoute<UseRouteType<'Search'>>()
  const shouldDisplayUnavailableOfferMessage = userData && userData.length > 0
  const unavailableOfferMessage = shouldDisplayUnavailableOfferMessage ? userData[0]?.message : ''

  const onPress = () => {
    analytics.logActivateGeolocfromSearchResults()
    showGeolocPermissionModal()
  }
```

Parce qu'on crée une fonction qui ne fait rien d'autre qu'en appeler une autre... Ca ne sert à rien.

PS: Puisque c'est difficilement visible avec Github, j'ai supprimé `const logActivateGeolocfromSearchResults` et j'ai remplacé son appel par `analytics.logActivateGeolocfromSearchResults()`

2023-03-14 12:56 UTC, cedricls1 commented on src/features/search/components/SearchResults/type.ts
> +export interface SearchListProps {
Est-ce que tu peux l'ajouter directement au fichier `types.ts` à la racine de la feature `search` ?

2023-03-14 15:32 UTC, cedricls1 approved these changes

2023-03-17 08:38 UTC, dbenfouzari-pass approved these changes

2023-03-20 08:39 UTC, merged