(PC-20531) feat(offer): use Algolia Recommend
pass-culture/pass-culture-app-native pull request #4414
Opened 2023-02-17 13:05 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20531

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-02-17 13:15 UTC, dbenfouzari-pass commented on src/features/offer/api/useSimilarOffers.ts
> +  return endpoint + urlParams.toString()
🎉

2023-02-17 13:19 UTC, dbenfouzari-pass commented on src/features/offer/api/useSimilarOffers.ts
> +  ) as string
Je n'aime pas beaucoup le `as string` à la fin.
Je pense que pour éviter ça il faut simplement que tu fasses un `if (!offerId) return` au-dessus de `const similarOffersEndpoint`

2023-02-17 13:21 UTC, dbenfouzari-pass commented on src/features/offer/api/useSimilarOffers.ts
> +    }
```suggestion
    setSimilarOffers(categoryIncluded
      ? await getAlgoliaRelatedProducts(String(offerId), queryParameters, fallbackParameters)
      : await getAlgoliaFrequentlyBoughtTogether(String(offerId), queryParameters)
    )
```

Je ne sais pas si ça perd en lisibilité 🤔 
Mais j'aime bien cette façon d'écrire

2023-02-17 13:25 UTC, cedricls1 commented on src/features/offer/api/useSimilarOffers.ts
> +  ) as string
Je l'ai rajouté au début de `getSimilarOffersEndpoint` et effectivement je peux le retirer du coup 👍

2023-02-17 13:29 UTC, cedricls1 commented on src/features/offer/api/useSimilarOffers.ts
> +    }
Franchement ça passe bien vu je vais update 👍

2023-02-20 15:00 UTC, cedricls1 commented
Le coverage n'est pas incroyable mais le principal y est

2023-02-20 15:13 UTC, cedricls1 commented on src/features/offer/api/useSimilarOffers.ts
> +  return endpoint + urlParams.toString()
le `set` n'est pas supportée sous iOS par contre le `append` est ok

2023-02-20 15:46 UTC, YassinL reviewed
Je ne connais pas, mais je te fais quelques petites suggestions. 
Sinon beau travail Bravo !! 🚀

2023-02-20 15:46 UTC, YassinL commented on src/features/offer/helpers/getSearchGroupIdFromSubcategoryId/getSearchGroupIdFromSubcategoryId.ts
> +    return undefined
Tu peux refacto ces deux condition, et return sans argument renvoie undefined : 
```jsx
if (!data || !subcategoryId) {
    return;
  }
  ```

2023-02-20 15:46 UTC, YassinL commented on src/features/offer/helpers/getSearchGroupIdFromSubcategoryId/getSearchGroupIdFromSubcategoryId.ts
> +    .map((subcategory) => subcategory.searchGroupName)
Je ne suis pas sur à 100% mais je crois que si tu utilises un `.find` ça t'évite d'utiliser un `.filter` et `.map`
```jsx
const subcategory = data.subcategories.find((subcategory) => subcategory.id === subcategoryId);
 return subcategory.searchGroupName;
 ```

2023-02-20 15:46 UTC, YassinL commented on src/features/offer/api/useSimilarOffers.ts
> +}
Petite question pour ma culture perso de notre code base on préfère utilisé des `then/catch` plutôt que des `async/await` dans un `try/catch` ?
exemple : 
```jsx
const getApiRecoSimilarOffers = async (similarOffersEndpoint: string) => {
  try {
    const response = await fetch(similarOffersEndpoint);
    const data = await response.json();
    const similarOffers = data.results;
    return similarOffers;
  } catch (error) {
    eventMonitoring.captureException(error);
    return [];
  }
}
```

2023-02-21 10:52 UTC, dbenfouzari-pass commented on src/features/offer/api/useSimilarOffers.ts
> +    .catch((error) => eventMonitoring.captureException(error))
```suggestion
    .catch(eventMonitoring.captureException)
```

2023-02-21 11:20 UTC, dbenfouzari-pass requested changes

2023-02-21 11:20 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +    otherCategoriesSimilarOffers && otherCategoriesSimilarOffers.length > 0
```suggestion
  const hasSameCategorySimilarOffers = sameCategorySimilarOffers?.length > 0
  const hasOtherCategoriesSimilarOffers = otherCategoriesSimilarOffers?.length > 0
```

2023-02-21 11:20 UTC, dbenfouzari-pass commented on src/features/offer/helpers/getAlgoliaRecommendParams/getAlgoliaRecommendParams.ts
> +  if (categories && categories.length > 0) {
```suggestion
  if (categories?.length > 0) {
```

2023-02-21 11:20 UTC, dbenfouzari-pass commented on src/features/offer/helpers/getSearchGroupIdFromSubcategoryId/getSearchGroupIdFromSubcategoryId.ts
> +    .map((subcategory) => subcategory.searchGroupName)
```suggestion
  return data.subcategories
    .find((subcategory) => subcategory.id === (subcategoryId as unknown as SubcategoryIdEnumv2))
    ?.searchGroupName
```

2023-02-21 11:20 UTC, dbenfouzari-pass commented on src/features/offer/pages/Offer/Offer.tsx
> +    categoryIncluded: undefined,
```suggestion
```

2023-02-21 11:20 UTC, dbenfouzari-pass commented on src/features/offer/pages/Offer/Offer.tsx
> +    categoryExcluded: subcategorySearchGroupId?.[0] || SearchGroupNameEnumv2.NONE,
Pareil

2023-02-21 11:20 UTC, dbenfouzari-pass commented on src/features/offer/pages/Offer/Offer.tsx
> +    otherCategoriesSimilarOffers && otherCategoriesSimilarOffers.length > 0
```suggestion
  const hasOtherCategoriesSimilarOffers = otherCategoriesSimilarOffers?.length > 0
```

2023-02-21 11:20 UTC, dbenfouzari-pass commented on src/features/offer/pages/Offer/Offer.tsx
> +      if (isCloseToBottom({ ...nativeEvent, padding: hasTwoSimilarOffersPlaylist ? 600 : 300 })) {
Tu devrais exporter ça dans une constante ou une fonction bien nommée :
```suggestion
const PLAYLIST_HEIGHT = 300;

function getPlaylistsHeight(numberOfPlaylists: number) {
  return PLAYLIST_HEIGHT * numberOfPlaylists
}
      if (isCloseToBottom({ ...nativeEvent, padding: getPlaylistsHeight(hasTwoSimilarOffersPlaylist ? 2 : 1) })) {
```

2023-02-21 13:29 UTC, cedricls1 commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +    otherCategoriesSimilarOffers && otherCategoriesSimilarOffers.length > 0
Avec `sameCategorySimilarOffers?.length > 0`, Typescript n'est pas content mais si j'utilise `sameCategorySimilarOffers?.length` il est content ^^

2023-02-22 11:20 UTC, cedricls1 commented on src/features/offer/api/useSimilarOffers.ts
> +  categoryExcluded: undefined
ça me génère un code smell, c'était pour cette raison que j'avais retiré le fait que ça soit un param optionnel

2023-02-22 11:42 UTC, cedricls1 commented on src/features/offer/api/useSimilarOffers.ts
> +  categoryExcluded: undefined
J'ai remplacé `undefined` par `never` et c'est ok

2023-02-22 11:45 UTC, cedricls1 commented
Je n'ai pas réussi à tester le cas où les APIs d'Algolia Recommend renvoient un string car le mock s'attend à avoir un tableau de recommendations et si je met un seul objet il me renvoie quand même un tableau avec une recommendation.

2023-02-22 13:04 UTC, YassinL approved these changes

2023-02-22 13:07 UTC, dbenfouzari-pass commented on src/features/offer/api/useSimilarOffers.ts
> +  categoryExcluded: undefined
Très bizarre quand même ! Mais oui `never` c'est encore mieux.
A l'avenir ce serait top que tu m'écrives précisément le code smell.

2023-02-22 13:14 UTC, cedricls1 commented on src/features/offer/api/useSimilarOffers.ts
> +  categoryExcluded: undefined
Le code smell en question : `consider removing 'undefined' type or '?' specifier, one of them is redundant.`

2023-02-22 13:16 UTC, dbenfouzari-pass requested changes
Des broutilles, mais si on arrivait à harmoniser ce serait pas mal :D

2023-02-22 13:16 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +  const hasOtherCategoriesSimilarOffers = otherCategoriesSimilarOffers?.length
Effectivement `undefined > 0` ça marcherait pas :P

Dans ce cas je préfère mieux
```suggestion
  const hasSameCategorySimilarOffers = Boolean(sameCategorySimilarOffers?.length)
  const hasOtherCategoriesSimilarOffers = Boolean(otherCategoriesSimilarOffers?.length)
```

parce que là niveau TypeScript tu dois avoir un truc du genre `number | undefined` alors qu'on veut un boolean

2023-02-22 13:16 UTC, dbenfouzari-pass commented on src/features/offer/pages/Offer/Offer.tsx
> +  const hasSameCategorySimilarOffers = sameCategorySimilarOffers?.length
Du coup ici pareil :
```suggestion
  const hasSameCategorySimilarOffers = Boolean(sameCategorySimilarOffers?.length)
```

2023-02-22 13:16 UTC, dbenfouzari-pass commented on src/features/offer/pages/Offer/Offer.tsx
> +  const hasOtherCategoriesSimilarOffers = otherCategoriesSimilarOffers?.length
Et ici aussi
```suggestion
  const hasOtherCategoriesSimilarOffers = Boolean(otherCategoriesSimilarOffers?.length)
```

2023-02-22 14:22 UTC, cedricls1 commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +  const hasOtherCategoriesSimilarOffers = otherCategoriesSimilarOffers?.length
Yes c'est vrai 👍

2023-02-22 14:28 UTC, cedricls1 commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +  const hasOtherCategoriesSimilarOffers = otherCategoriesSimilarOffers?.length
Sur `OfferBody` ça me génère une erreur Typescript au niveau du param `data` de `PassPlaylist` :

> Impossible d'assigner le type 'SearchHit[] | undefined' au type 'any[]'.
>   Impossible d'assigner le type 'undefined' au type 'any[]'.

2023-02-23 11:02 UTC, dbenfouzari-pass approved these changes
Et bravo pour le coverage :)

2023-02-23 15:31 UTC, merged