(PC-19849) fix(TouchableLink): type internal touchable link correctly in styledComponent
pass-culture/pass-culture-app-native pull request #4449
Opened 2023-02-23 15:04 UTC by marineshaw

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-X19849

## Checklist

I have:

- [x] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [x] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |![image](https://user-images.githubusercontent.com/68000368/220945410-3cf43a43-98b5-44f0-b2ac-05602fd7f8eb.png)|
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |![image](https://user-images.githubusercontent.com/68000368/220945205-3209bf06-27d0-487f-9588-8f8194eba8ae.png)|
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-02-23 15:48 UTC, anoukhello requested changes

2023-02-23 15:48 UTC, anoukhello commented on src/ui/components/SeeMoreWithEye.tsx
> +const StyledTouchableLink: typeof InternalTouchableLink = styled(InternalTouchableLink).attrs(
En fait c'est juste ça `typeof InternalTouchableLink` qui change ? Sinon c'est juste une extraction de composant ?

2023-02-23 15:48 UTC, anoukhello commented on src/features/identityCheck/components/StepButton.tsx
> +  // )
coucou

2023-02-23 15:48 UTC, anoukhello commented on src/features/identityCheck/components/StepButton.tsx
> +    </StyleContainer>
J'ai du mal à bien voir ce qui change au niveau du style mais il y a clairement qlq chose de cassé sur le stepper d'après les screenshots dans le commentaire de la PR, car le bouton en état "current" doit être centré comme ici 
<img width="321" alt="Capture d’écran 2023-02-23 à 16 10 27" src="https://user-images.githubusercontent.com/22886846/220958582-685bf24a-b9dc-443b-b36d-32fbe9d5f2fd.png">
et non justifié à gauche

2023-02-23 15:58 UTC, anoukhello commented on src/features/identityCheck/components/StepButton.tsx
> +    </StyleContainer>
Du coup il faudra bien vérifier sur web et mobile que le style est ok une fois corrigé :)

2023-02-24 09:54 UTC, marineshaw commented on src/ui/components/SeeMoreWithEye.tsx
> +const StyledTouchableLink: typeof InternalTouchableLink = styled(InternalTouchableLink).attrs(
On a changé le type de la props aussi, avant elle pouvait être undefined, maintenant ce n'est plus le cas ! (et c'est le typeof InternalTouchableLink qui nous oblige à faire ça, il permet de montrer l'erreur)

2023-02-24 10:04 UTC, anoukhello approved these changes
Nickel !

2023-02-24 13:58 UTC, merged