api.ts update
pass-culture/pass-culture-app-native pull request #4471
Opened 2023-03-02 09:38 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-03-07 15:23 UTC, dbenfouzari-pass commented on src/features/bookOffer/components/BookHourChoice.tsx
> +      dispatch({ type: 'SELECT_QUANTITY', payload: 1 })
S'il est duo, tu dois pas `dispatch({ type: 'SELECT_QUANTITY', payload: 2 })` ?

2023-03-07 15:25 UTC, cedricls1 commented on src/features/bookOffer/components/BookHourChoice.tsx
> +      dispatch({ type: 'SELECT_QUANTITY', payload: 1 })
En fait tu forces la quantité à 1 quand l'offre n'est pas duo à ce moment sinon c'est géré à l'étape d'après :)

2023-03-07 15:49 UTC, dbenfouzari-pass requested changes

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/components/BookHourChoice.tsx
> +          ),
Cette partie est un peu complexe.
Tu pourrais avoir un
```suggestion
          const stockAtDateFilterPredicate = (stock: ??) =>
            !stock.isExpired &&
            stock.beginningDatetime &&
            formatToKeyDate(stock.beginningDatetime) === selectedDate

          const sortByDatePredicate = (a: string, b: string) => {
            return new Date(a as string).getTime() - new Date(b as string).getTime()
          }

          ...new Set(
            stocks
              .filter(stockAtDateFilterPredicate)
              .map((stock) => stock.beginningDatetime)
              .sort(sortByDatePredicate) as string[]
          ),
```

Dans l'idéal il faudrait sortir les `predicate` du composant aussi.

Autre point. J'imagine qu'il y a une raison aux `as string`, mais y'a pas moyen de les corriger ?

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/components/BookHourChoice.tsx
> +          )
Ici même genre de remarque : c'est compliqué de comprendre. Peut-être qu'une fonction bien nommée aiderait ?

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/components/BookPricesChoice.tsx
> +            })}
```tsx
const filteredStocks = stocks.filter(...).sort(...) // voire un useMemo
          
return filteredStocks.map(
  <Li>...</Li>
)
```

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/components/BookingEventChoices.tsx
> +  enablePricesByCategories,
Tu as dû passer plein de tests pour que cette valeur soit à `false`.
Pourquoi tu fais pas simplement
```suggestion
  enablePricesByCategories = false,
```

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/components/BookingEventChoices.tsx
>    const getButtonState = () => {
Vu ce que ça fait, je l'aurai plutôt nommée `getIsValid`

Par ailleurs, maintenant qu'il ne fait plus rien tu pourrais juste avoir une variable
```tsx
const isValid = typeof stockId === 'number' && typeof quantity === 'number'
```

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts
> +export function getButtonState(bookingState: BookingState) {
Pourquoi tu as 2 fonctions `getButtonState` ?
Elles font pas la même chose apparemment, mais quand même

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts
> +  }
```suggestion
  switch (step) {
    case Step.DATE:
      return date !== undefined
    case Step.HOUR:
      return hour !== undefined || stockId !== undefined
    case Step.PRICE:
      return stockId !== undefined
    case Step.DUO:
      return quantity !== undefined
    default:
      return false
  }
```

inutile de mettre les parenthèses dans ton cas :)

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/components/BookingOfferModalFooter.tsx
> +  return step < Step.CONFIRMATION ? (
Ca m'embête beaucoup que `Step` soit un enum de nombres que tu manipules...
Le principe d'un enum c'est que l'ordre dans lequel sont définies ses entrées n'influe pas sur la sortie. Ici oui, et surtout tu manipules cette sortie.

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/components/Calendar/Calendar.tsx
> +}
```suggestion
export const getDayDescription = (price: number, hasSeveralPrices?: boolean) => {
  return `${hasSeveralPrices ? 'dès ' : ''} {formatToFrenchDecimal(price).replace(' ', '')}`
}
```

Je ne sais pas si c'est mieux.
Ou alors 
```suggestion
export const getDayDescription = (price: number, hasSeveralPrices?: boolean) => {
  let dayDescription = hasSeveralPrices ? 'dès ' : ''
  dayDescription += formatToFrenchDecimal(price).replace(' ', '')

  return dayDescription
}
```

Je n'aime pas les déclarations vides, souvent ça indique que quelque chose peut être fait autrement.
Je pense que la seconde solution que je te propose est un bon compromis.

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts
> +}
J'aurai préféré un truc du genre 
```ts
export enum Step {
  DATE = "booking-step__date",
  HOUR = "booking-step__hour",
  CONFIRMATION = "booking-step__confirmation",
}

export function getSteps(stocks, offerIsDuo) {
  if (...) {
    return [Step.DATE, Step.CONFIRMATION]
  }
  return [Step.DATE, Step.HOUR, Step.CONFIRMATION]
}

export function getTotalSteps(...) {
  return getSteps(...).length
}
```

Tu vois le genre ?
Pour éviter de manipuler les chiffres là :/

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts
> +    }
Même remarque concernant les `{}`

2023-03-07 15:49 UTC, dbenfouzari-pass commented on src/features/bookOffer/pages/BookingOfferModal.tsx
> +  }, [leftIcon, leftIconAccessibilityLabel, onLeftIconPress])
L'usage du `useMemo` ici me semble parfaitement inutile.
Tu ne manipules rien alors en l'état ça revient au même que si tu ne mettais pas de useMemo

```suggestion
  const modalLeftIconProps: ModalLeftIconProps = { leftIcon, leftIconAccessibilityLabel, onLeftIconPress }
```

2023-03-07 15:53 UTC, cedricls1 commented on src/features/bookOffer/pages/BookingOfferModal.tsx
> +  }, [leftIcon, leftIconAccessibilityLabel, onLeftIconPress])
Yes à la base il était utilisé dans un useMemo mais j'ai externalisé les composants, je retire

2023-03-07 16:02 UTC, cedricls1 commented on src/features/bookOffer/components/BookingEventChoices.tsx
>    const getButtonState = () => {
Yes tu as raison je corrige

2023-03-07 16:02 UTC, cedricls1 commented on src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts
> +export function getButtonState(bookingState: BookingState) {
J'ai retiré celle qui servait plus à grand chose ^^

2023-03-07 16:09 UTC, cedricls1 commented on src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts
> +}
Yes bien vu, ça sera plus visuel

2023-03-07 16:34 UTC, cedricls1 commented on src/features/bookOffer/components/BookHourChoice.tsx
> +          )
J'ai renommé la variable pour être plus précis

2023-03-08 08:18 UTC, cedricls1 commented on src/features/bookOffer/components/BookHourChoice.tsx
> +          ),
J'ai fait une partie de ce que tu as demandé

2023-03-08 13:04 UTC, dbenfouzari-pass approved these changes

2023-03-08 13:23 UTC, merged