WIP
pass-culture/pass-culture-app-native pull request #4541
Opened 2023-03-14 16:07 UTC by kopax-polyconseil

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-03-16 19:46 UTC, dbenfouzari-pass requested changes
Juste un petit détail.

Mais surtout, je me demande si tu ferais pas mieux de créer un hook `useVersion`

```ts
import packageJson from "package.json"

export function useVersion() {
  const codePushVersion = useCodePushVersion();

  let version = `Version&nbsp;${Package.version}`
  if (codePushLabel) version += `-${codePushLabel}`

  return version
}
```

Ou un truc du genre. Comme ça dans `Profile.tsx` tu peux juste avoir un `const version = useVersion()` et basta.

2023-03-16 19:46 UTC, dbenfouzari-pass commented on src/features/profile/pages/Profile.tsx
> +            {codePushLabel ? `-${codePushLabel}` : undefined}
```tsx
let version = `Version&nbsp;${Package.version}`
if (codePushLabel) version += `-${codePushLabel}`

{/* ... */}

<Typo.CaptionNeutralInfo>{version}</Typo.CaptionNeutralInfo>
```

2023-03-16 19:46 UTC, dbenfouzari-pass commented on src/ui/hooks/useCodePushVersion.web.test.ts
> +  it('should return null', () => {
Pour un meilleur debug si nécessaire :
```suggestion
  it('should return null on web', () => {
```

2023-03-17 08:03 UTC, cedricls1 commented
@YassinL Je me demande si ça ne serait pas mieux de faire sauter le `v` et de garder que le numéro.
On aurait `1.231.12-3875`. A suggérer en daily peut être

2023-03-17 08:14 UTC, cedricls1 commented on src/features/profile/pages/Profile.native.test.tsx
> +  it('displays the CodePush version label', async () => {
J'aime bien garder le `should`

2023-03-17 08:14 UTC, cedricls1 commented on src/features/profile/pages/Profile.native.test.tsx
> +  it('does not display the version label when it is not available', async () => {
Ici aussi

2023-03-17 08:14 UTC, cedricls1 commented on src/ui/hooks/useCodePushVersion.test.ts
> +  it('returns empty string if CodePush.getUpdateMetadata returns null', async () => {
`should return empty string when there are not CodePush information`
C'est un peu moins technique

2023-03-17 08:14 UTC, cedricls1 commented on src/ui/hooks/useCodePushVersion.test.ts
> +  it('returns version label if CodePush.getUpdateMetadata returns metadata', async () => {
`should return version label when there are CodePush information`

2023-03-17 08:14 UTC, cedricls1 commented on src/ui/hooks/useCodePushVersion.test.ts
> +  it('calls eventMonitoring.captureException on error', async () => {
`should capture a Sentry issue when there is an error`

2023-03-17 15:12 UTC, dbenfouzari-pass approved these changes

2023-03-17 15:20 UTC, cedricls1 reviewed
Du détail ^^
Par contre tu as des tests web qui failed

2023-03-17 15:20 UTC, cedricls1 commented on src/features/profile/pages/Profile.native.test.tsx
> +  it('should displays the verdsion with the CodePush version label', async () => {
`should display the version with the CodePush version label`

2023-03-17 15:20 UTC, cedricls1 commented on src/features/profile/pages/Profile.native.test.tsx
> +  it('should does not display the Code push version label when it is not available', async () => {
`should not display the Code push version label when it is not available`

2023-03-17 15:32 UTC, YassinL commented on src/ui/hooks/useVersion.test.ts
> +  it('should calls eventMonitoring.captureException on error', async () => {
^^ ça me va aussi 👍

2023-03-17 15:45 UTC, cedricls1 approved these changes

2023-03-17 17:58 UTC, kopax-polyconseil commented on src/ui/hooks/useVersion.ts
> +  const shortCodePushLabel = codePushLabel.substring(1)
- Pour ça je trouve `.slice(1)` plus lisible, sinon autre idée pour faire sauter ton commentaire : `.replace('v', '')`

2023-03-20 15:29 UTC, cedricls1 approved these changes

2023-03-20 15:34 UTC, merged