(PC-21656) feat(home): Fix spinner display for progressive loading
pass-culture/pass-culture-app-native pull request #4645
Opened 2023-04-13 09:05 UTC by aliraiki

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21656

## Checklist

I have:

- [x] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [x] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-04-13 12:00 UTC, pierrecanthelou requested changes
Le comportement est bon mais je vois des modifications à apporter sur les timeouts. Notamment si je sors du composant en ayant appuyé sur une offre

2023-04-13 12:21 UTC, anoukhello reviewed
Est-ce que tu as vérifié ce que ça donne sur android ?

Aussi petit warning par rapport à [cette PR](https://github.com/pass-culture/pass-culture-app-native/pull/3498/files) qui introduisait ou supprimait des choses supprimées ou remises ici, t'en penses quoi ?

2023-04-13 12:52 UTC, pierrecanthelou commented
Pas encore suffisant en fait :(
On voit bien un spinner mais on voit aussi un gros soucis de "plus de spinner mais quand même des données en transfert"

https://user-images.githubusercontent.com/119601402/231764177-3e2383df-8987-4e3d-a80b-635023424fe7.mp4


https://user-images.githubusercontent.com/119601402/231764056-18a28c60-b3e9-456f-a704-1e2513ff418f.mp4

2023-04-13 13:36 UTC, aliraiki commented on src/features/home/pages/GenericHome.tsx
> +      {!!(!hasShownAll || isLoading) && (
Je pense que `!!(!hasShownAll || isLoading)` est équivalent à `!hasShownAll || !!isLoading` et pas `!hasShownAll && !!isLoading` non ? (double négation de ||)

2023-04-13 14:15 UTC, aliraiki commented
> Pas encore suffisant en fait :( On voit bien un spinner mais on voit aussi un gros soucis de "plus de spinner mais quand même des données en transfert"

Je suis d'accord, les requêtes de certaines playlists prennent plus de temps que d'autres, et ne s'affichent donc pas dans l'ordre attendu.

2023-04-13 14:49 UTC, pierrecanthelou commented on src/features/home/pages/GenericHome.tsx
> +      {!!(!hasShownAll || isLoading) && (
Crotte tu as raison mais quoi qu'il en soit j'ai l'impression que le loader ne s'affiche pas bien. Il doit y avoir un truc à revoir. Moi j'ai testé avec un bad-network et yarn ios:prod

2023-04-13 14:59 UTC, pierrecanthelou approved these changes
Ok pour moi ;)

2023-04-14 08:26 UTC, anoukhello approved these changes

2023-04-17 07:54 UTC, merged