(PC-21651) upgrade(react-native-firebase): upgrade lib
pass-culture/pass-culture-app-native pull request #4653
Opened 2023-04-14 08:06 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21651

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-04-14 08:33 UTC, anoukhello requested changes
D'après le ticket il fallait plutôt mettre à jour react-native-firebase en version `16.4.3` non ?

Aussi je pense qu'il faut mettre à jour les pods et d'après ce que je vois ça coince un peu en faisant `bundle exec pod install`
````
[!] CocoaPods could not find compatible versions for pod "Firebase/Performance":
  In snapshot (Podfile.lock):
    Firebase/Performance (= 8.15.0)

  In Podfile:
    RNFBPerf (from `../node_modules/@react-native-firebase/perf`) was resolved to 16.7.0, which depends on
      Firebase/Performance (= 10.3.0)

Specs satisfying the `Firebase/Performance (= 8.15.0), Firebase/Performance (= 10.3.0)` dependency were found, but they required a higher minimum deployment target.
```

2023-04-18 08:21 UTC, anoukhello approved these changes
Ok si tu as vérifié que tous les services de firebase fonctionnent correctement :)

2023-04-18 08:21 UTC, anoukhello commented on ios/Podfile
> +  pod 'GoogleUtilities', :modular_headers => true
Tu sais pourquoi il faut ajouter ça ?

2023-04-18 10:09 UTC, Lucasbeneston commented
> Désolé @anoukhello je suis allé un peu vite dessus du coup j'ai pu fix le Podfile, et je l'ai complété, j'ai vérifié que tout fonctionne à nouveau. j'ai tenté par la suite de passer en modulaire et en avançant je me suis rendu compte qu'on utilisait `@react-native-firebase/firestore` et pour le coup il semble que la migration vers la version modulaire de Firebase ne soit pas encore disponible pour la bibliothèque en native.

Oui effectivement ce n'est pa encore modulaire pour react-native-firebase, pour ça qu'on a pas fait l'autre MAJ

2023-04-18 10:17 UTC, Lucasbeneston approved these changes
Ça me semble cohérent, si tu dis que tu as testé et que c'est toujours bon : ✅

2023-04-18 12:25 UTC, YassinL commented on ios/Podfile
> +  pod 'GoogleUtilities', :modular_headers => true
J'ai dû les ajouter en raison de la mise à niveau de `FirebaseFirestore` vers la version `10.1.0`, qui était nécessaire suite à la mise à jour des différentes bibliothèques `@react-native-firebase/...` vers la version `16.4.3`.

En effectuant un `pod install`, j'ai rencontré une erreur (par exemple pour GoogleUtilities) : Le pod Swift `FirebaseCoreInternal` dépend de `GoogleUtilities`, qui ne définit pas de modules. Pour activer la génération de cartes de modules (ce qui est nécessaire pour les importer depuis Swift lors de la construction de bibliothèques statiques), vous pouvez définir `use_modular_headers` globalement dans votre fichier `Podfile`, ou spécifier `:modular_headers => true` pour des dépendances particulières. (j'ai traduis le message d'erreur)

J'ai donc suivi les instructions de l'erreur et j'ai également cherché des solutions sur Stack Overflow et GitHub. Le même problème s'est produit pour FirebaseCore.

2023-04-18 12:27 UTC, YassinL commented on ios/PassCulture.xcodeproj/project.pbxproj
> +			baseConfigurationReference = 1ABB05BBB204C6C2441212D9 /* Pods-PassCulture.release.xcconfig */;
Les modifications apportées à ce fichier sont dues à la mise à niveau du Podfile, qui est liée à la mise à niveau de `@react-native-firebase/...`.

2023-04-18 14:23 UTC, merged