(PC-21779) feat(offer): new venue section
pass-culture/pass-culture-app-native pull request #4669
Opened 2023-04-18 06:58 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21779

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-04-18 15:26 UTC, cedricls1 commented
> Juste par curiosité, je ne vais pas review, mais pourquoi il y a parfois une bordure arrondie grise et parfois non autour du lieu de retrait ?

La bordure arrondie grise c'est quand c'est un bouton qui permet d'accéder au lieu (lieu permanent)
Dans l'autre cas c'est juste de l'affichage car le lieu est non permanent et tu ne peux donc pas accéder à la page lieu.

2023-04-18 15:28 UTC, Lucasbeneston commented
> > Juste par curiosité, je ne vais pas review, mais pourquoi il y a parfois une bordure arrondie grise et parfois non autour du lieu de retrait ?
> 
> La bordure arrondie grise c'est quand c'est un bouton qui permet d'accéder au lieu (lieu permanent) Dans l'autre cas c'est juste de l'affichage car le lieu est non permanent et tu ne peux donc pas accéder à la page lieu.

Ah d'accord ! J'avoue que j'ai l'impression que je ne peux pas cliquer dessus avec la bordure grise seulement, contrairement a avant avec le chevron ! 

Ça pourrait être intéressant de voir l'avant après pour le nombre de clic. 

En tout cas c'est top comme design avec la diff de couleur sur les km

2023-04-18 15:42 UTC, YassinL approved these changes
Pour moi tout est good bien joué 👍

2023-04-18 15:46 UTC, dbenfouzari-pass requested changes

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.native.test.tsx
> +  describe('When wipEnableMultivenueOffer feature flag desactivated', () => {
Quitte à corriger :
```suggestion
  describe('When wipEnableMultivenueOffer feature flag deactivated', () => {
```

Ce n'est pas comme en français, ça ne prend pas de `s` (cf https://www.google.com/search?q=deactivated&sourceid=chrome&ie=UTF-8)

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +  }
On en aura besoin plus tard alors il faudrait l'exporter dans un fichier à part, et écrire ses propres tests (ou pas, mais en tous cas il faut exporter cet helper)

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSection/VenueSection.tsx
> +  locationCoordinates: Coordinates
Pourquoi passer `locationCoordinates` alors que ça vient déjà de `venue` et donc `venue.coordinates` ?

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSection/VenueSection.tsx
> +  showVenueBanner?: boolean | false
Original 😆 
```suggestion
  showVenueBanner?: boolean
```

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +            }
Ce `beforeNavigateToItinerary` devrait au mieux être dans une fonction plus haut. En effet ici la fonction est recréée à chaque render. Tu pourras réutiliser dans `<WhereSection />` également.

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +            title={getVenueSectionTitle()}
Tu ne devrais pas rappeler la fonction `getVenueSectionTitle` à chaque render.
Par contre tu peux avoir un truc du genre
```ts
const venueSectionTitle = useMemo(() => ..., [])
```

et appeler
```suggestion
            title={venueSectionTitle}
```

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +          title={getVenueSectionTitle()}
Idem ici, on n'appelle pas la fonction

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueDetails/VenueDetails.tsx
> +  // only used by venue card
```suggestion
  /**
    * This prop is for internal usage only.
    * It is used by `<VenueCard />` component and should not be used by
    * developers outside this component.
    */
```

Pour que ce soit bien clair 😛

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSection/VenueSection.tsx
> +    : ''
Je ne pense pas qu'il soit nécessaire de faire ce check.
```suggestion
  const venueFullAddress = formatFullAddressStartsWithPostalCode(venue.address, venue.postalCode, venue.city)
```
puisqu'on voudrait peut-être afficher juste postalCode + city : `75000 Paris`.

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSection/VenueSection.tsx
> +  }
Il manque un `useCallback` ici.

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/libs/address/useFormatFullAddress.ts
> +  return [firstPart, address].join(', ')
Tu peux remplacer par

```suggestion
  return [firstPart, address].filter(Boolean).join(', ')
```

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSection/VenueSection.native.test.tsx
> +  it('should log ConsultLocationItinerary analytics when pressing on "Voir l’itinéraire"', () => {
```suggestion
  it('should call `beforeNavigateToItinerary` function when pressing on "Voir l’itinéraire"', () => {
```

2023-04-18 15:46 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSection/VenueSection.native.test.tsx
> +    fireEvent.press(getByText('Voir l’itinéraire'))
```suggestion
    render(
      <VenueSection
        venue={venue}
        locationCoordinates={{ latitude: 2, longitude: 4 }}
        beforeNavigateToItinerary={beforeNavigateToItinerary}
        showVenueBanner
        title="Lieu de retrait"
      />
    )

    fireEvent.press(screen.getByText('Voir l’itinéraire'))
```

2023-04-19 07:11 UTC, cedricls1 commented on src/features/offer/components/OfferBody/OfferBody.native.test.tsx
> +  describe('When wipEnableMultivenueOffer feature flag desactivated', () => {
Merci pour le cours d'anglais ^^

2023-04-19 07:26 UTC, cedricls1 commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +            title={getVenueSectionTitle()}
Impossible d'utiliser un useMemo parce qu'il y a la condition 
`if (!offer) return <React.Fragment></React.Fragment>`

2023-04-19 08:05 UTC, cedricls1 commented on src/features/offer/components/VenueSection/VenueSection.tsx
> +  locationCoordinates: Coordinates
Yes t'as raison j'ai un peu trop copier coller

2023-04-19 08:15 UTC, cedricls1 commented on src/features/offer/components/VenueSection/VenueSection.tsx
> +  showVenueBanner?: boolean | false
Ah ouais j'avoue, j'avais pas capté bien vu

2023-04-19 08:57 UTC, cedricls1 commented on src/features/offer/components/VenueSection/VenueSection.tsx
> +    : ''
Yes tu as raison par contre il ne faut pas avoir le bouton "Voir l'itinéraire" si on n'a pas d'adresse précise. Je revois un petit peu les conditions

2023-04-19 09:11 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +            title={getVenueSectionTitle()}
Ok je comprends. Je n'aime pas avoir un return en plein milieu justement pour cette raison.
Pour moi on devrait avoir 
```tsx
const Component = () => {
  useEffect(() => ...)
  const handler = useCallback(() => ...)

  if (!var) return
  return (...)
}
```

Ce qui impliquerait de faire des checks dans toutes les variables plus haut mais c'est mieux ainsi...
Enfin en ce qui te concerne OK, ça marche 👍

2023-04-19 09:14 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSection/VenueSection.tsx
> +  }
Oui. Comme je l'expliquais tu es dans `VenueSection` qui n'est pas censé savoir si `venue` est mémoizé ou non. Donc tu pars du principe où c'est le cas et où `<VenueSection />` fait bien les choses.

2023-04-19 09:16 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.native.test.tsx
> -    })
Tu aurais pu laisser ces tests ce n'était pas perdu :P

2023-04-19 09:23 UTC, cedricls1 commented on src/features/offer/components/OfferBody/OfferBody.native.test.tsx
> -    })
Yes mais du coup ils font un peu doublons avec les tests de la fonction. Je les laisse quand même ?

2023-04-19 09:27 UTC, cedricls1 commented on src/features/offer/components/VenueSection/VenueSection.tsx
> +  locationCoordinates: Coordinates
Ah oui c'est vrai 👍

2023-04-19 09:40 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.native.test.tsx
> -    })
Vu ensemble sur Slack : oui c'est bien de les laisser pour vérifier que dans le contexte tout fonctionne bien

2023-04-19 12:15 UTC, dbenfouzari-pass approved these changes

2023-04-19 12:24 UTC, merged