(PC-21987) feat(StepCard): add new component StepCard
pass-culture/pass-culture-app-native pull request #4735
Opened 2023-04-28 08:50 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21987

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-04-28 09:54 UTC, dbenfouzari-pass requested changes

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +}
Je suis pas trop d'accord avec ça, ça casse complètement l'icône de base.

Si le dev veut mettre une icône violette par exemple, tu forces pour que ce soit en `primary` ou `secondary`.

La solution serait de faire quelque chose comme ça:

```ts
function getIconWithColors(icon: ReactElement, disabled: boolean, theme: DefaultTheme) {
  if (!disabled) return icon;

  return React.cloneElement(icon, { color: theme.colors.greyMedium, color2: theme.colors.greyMedium })
}
```

Par ailleurs tu ne fais qu'appliquer une seule couleur. Alors plutôt que de passer le `theme` en entier, ce qui n'est pas une bonne pratique pour une fonction comme celle-ci, tu peux juste passer une `disabledColor` par exemple :

```ts
function getIconWithColors(icon: ReactElement, disabled: boolean, disabledColor: LeTypeDesCouleurs) {
  if (!disabled) return icon;

  return React.cloneElement(icon, { color: disabledColor, color2: disabledColor })
}
```

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +  const iconElement = getIconWithColors(icon, disabled, theme)
C'est typiquement le genre de chose à mettre dans un `useMemo` :D

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +    paddingBottom: hasSubtitle ? getSpacing(5) : getSpacing(6),
Ce n'est pas vrai ça.
Ce qu'a voulu faire Aline c'est avoir un composant qui aie toujours la même hauteur.

Donc tu veux fixer la hauteur du composant à 88px lorsqu'il est `disabled` et à `92px` lorsqu'il ne l'est pas.
Ensuite tu as ton titre et sous-titre qui sont alignés verticalement dans ce composant.

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +    paddingRight: getSpacing(3),
J'ai vérifié sur Figma et on a 16px horizontalement. Donc `getSpacing(4)`

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +    width: disabled ? '98%' : '100%',
Dangereux de bosser avec les %.
Ce que tu veux en fait c'est que ton composant soit `4px` plus large. Donc tu peux simplement supprimer cette ligne et appliquer une margin négative sur l'état actif

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +const Icon = styled.View({
ce n'est pas vraiment l'icône que tu stylises mais son wrapper :

```suggestion
const IconWrapper = styled.View({
```
ou
```suggestion
const IconContainer = styled.View({
```

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +  marginLeft: getSpacing(4),
Ce serait mieux d'appliquer un `gap: getSpacing(4)` sur le parent plutôt que de le forcer sur le `<TextContainer />`.

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +}))
A mon avis tu peux forcer l'utilisation de 2 lignes max avec un ellipsis. Faut voir avec Aline mais en l'état ton composant pourrait avoir 20 lignes.

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.native.test.tsx
> +    render(<StepCard title={title} icon={icon} />)
Je ne comprends pas ton `<MockIcon />` ?

Pourquoi ne pas simplement faire 
```suggestion
    render(<StepCard title={title} icon={<BicolorAroundMe />} />)
```

2023-04-28 09:54 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.native.test.tsx
> +    expect(screen.getByTestId('stepcard-container')).toHaveStyle({ borderColor: '#CBCDD2' })
Il te manque un autre test dans ce cas : il faut tester que ton title est gris également.
Par ailleurs plutôt que de mettre un `borderColor` en dur tu peux aussi faire
```suggestion
    expect(screen.getByTestId('stepcard-container')).toHaveStyle({ borderColor: theme.colors.TACOULEUR })
```

2023-04-28 11:55 UTC, YassinL commented on src/ui/components/stepCard/StepCard.tsx
> +    paddingBottom: hasSubtitle ? getSpacing(5) : getSpacing(6),
J'ai fais ça car j'en ai discuté avec Aline et c'est bien ce qu'elle voulait faire, de changer la taille du padding lorsqu'il y a ou non un `subTitle`

2023-04-28 11:56 UTC, YassinL commented on src/ui/components/stepCard/StepCard.tsx
> +    width: disabled ? '98%' : '100%',
J'ai copié ce qu'il y avait dans le `StepButton` car Aline voulait la même chose mais je peux faire ta suggestion si l'effet est le même 👍

2023-04-28 11:58 UTC, YassinL commented on src/ui/components/stepCard/StepCard.tsx
> +}))
Oui à voir avec elle mais je pense que c'est voulu qu'il puisse avoir plusieurs ligne

2023-04-28 12:20 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +    width: disabled ? '98%' : '100%',
A vrai dire le truc du % ne donnera pas le même effet.
Sur petit écran ce sera peut-être 4px, mais sur grand écran peut-être 40px.

2023-04-28 12:42 UTC, YassinL commented on src/ui/components/stepCard/StepCard.tsx
> +}))
Je confirme bien pour l'instant on reste sur la possibilité que le composant soit responsive et puisse prendre 1 ou 20 lignes

2023-05-02 11:52 UTC, YassinL commented on src/ui/components/stepCard/StepCard.tsx
> +    margin: !disabled ? -4 : 0,
Je ne suis pas sûr(e), mais cela semble être ainsi sur Figma. J'ai réduit de 2 pour que soit 4px en tout de chaque côtés.

2023-05-02 12:22 UTC, cedricls1 commented on src/ui/components/stepCard/StepCard.tsx
> +import React, { ReactElement, useMemo } from 'react'
Donovan a ajouté son composant directement dans features/profiles/components
Je me demande si ça serait pas mieux de l'avoir à cet endroit aussi

2023-05-02 12:22 UTC, cedricls1 commented on src/ui/components/stepCard/StepCard.native.test.tsx
> +    const title = 'This is a StepCard'
Je pense que tu peux les utiliser directement dans le `render` mais en soit pourquoi pas avoir des variables mais je pense que tu peux au moins les déclarer pour tout ton fichier de test

2023-05-02 12:37 UTC, dbenfouzari-pass requested changes

2023-05-02 12:37 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.native.test.tsx
> +    const title = 'This is a StepCard'
Effectivement je suis du même avis : c'est bien de mettre en variable pour ne pas répéter le code mais là en l'état ça ne sert à rien.

Si tu veux réellement mettre ça dans une variable fais-le en haut du fichier pour éviter de la répéter test après test.

2023-05-02 12:37 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +}) => {
Pour compléter le commentaire de Cédric :

```suggestion
export function StepCard ({
  title,
  subtitle,
  icon,
  type = StepCardType.ACTIVE,
}: StepCardProps) => {
```

2023-05-02 12:37 UTC, dbenfouzari-pass commented on src/ui/components/stepCard/StepCard.tsx
> +}
Je me demande si tu ne devrais pas réutiliser le résultat de la fonction suivante 
```suggestion
function getIconWithColors(icon: ReactElement, type: StepCardType, theme: DefaultTheme) {
  const color = getBorderColor(type, theme)
  
  return type === StepCardType.ACTIVE ? icon : React.cloneElement(icon, { color, color2: color })
```

2023-05-02 12:46 UTC, YassinL commented on src/ui/components/stepCard/StepCard.tsx
> +}
C'est une bonne idée de refacto, c'est un peu moins lisible mais cela retire deux condition déjà présente merci !

2023-05-02 13:36 UTC, dbenfouzari-pass approved these changes

2023-05-02 14:35 UTC, merged

2023-05-02 16:13 UTC, Lucasbeneston commented on src/ui/components/stepCard/StepCard.tsx
> +    paddingRight: getSpacing(3),
Idem `paddingHorizontal` ?