(PC-22329) feat(Signup): add new signup progress bar
pass-culture/pass-culture-app-native pull request #4809
Opened 2023-05-24 12:57 UTC by marineshaw

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22329

## Checklist

I have:

- [x] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [x] Written **unit tests** native (and web when implementation is different) for my feature.
- [] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-05-24 13:09 UTC, pierrecanthelou requested changes
Hello, je t'ai fait quelques remarques, j'espère qu'elles sont valides ;)

2023-05-24 13:09 UTC, pierrecanthelou commented on src/features/auth/pages/signup/ProgressBar/ProgressBar.tsx
> +  const progressionRatio = (currentStep / totalStep) * 100
min(0) et max(100) non ?

2023-05-24 13:09 UTC, pierrecanthelou commented on src/features/auth/pages/signup/ProgressBar/ProgressBar.tsx
> +          isFull={currentStep === totalStep}
tu peux le sortir ?

2023-05-24 13:09 UTC, pierrecanthelou commented on src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx
> +  const [currentStep, updateStep] = useReducer((v: number, incr: number) => v + incr, 0)
Qu'est-ce que cela changerait si tu faisais un hook avec le reducer et les deux actions ?

2023-05-24 13:09 UTC, pierrecanthelou commented on src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx
> +      <ProgressBar currentStep={currentStep} totalStep={5} />
totalStep en props avec 5 par défaut ?

2023-05-24 17:23 UTC, bruno-ebstein-pass-culture commented on src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx
> +export const SignupProgressBar = () => {
est-ce que ça serait Storybookifiable ?

2023-05-25 08:46 UTC, marineshaw commented on src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx
> +  const [currentStep, updateStep] = useReducer((v: number, incr: number) => v + incr, 0)
Je pense qu'on le fera de manière plus propre hors cheatcodes lors de la vraie implem ! La c'est juste pour avoir un retour visuel pour les PM/Designer mais l'archi sera mieux géré quand on l'intégrera au parcours d'inscription

2023-05-25 08:48 UTC, marineshaw commented on src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx
> +export const SignupProgressBar = () => {
La progressBar est bien sur storybook mais l'animation est pas trop bien gérée parce qu'on avance pas de 1 en 1, là on se rend bien compte de ce que ça donne et ça permet aussi de tester sur Android et iOS !

2023-05-25 09:54 UTC, marineshaw commented on src/features/auth/pages/signup/ProgressBar/ProgressBar.tsx
> +          duration={800}
La valeur est set par les designers spécifiquement pour la progressBar et on voudra qu'elle soit homogénéiser partout je pense, pour moi c'est risqué de la mettre en props tout de suite, mais ça pourra se faire le jour ou on voudra changer la valeur je pense ?

2023-05-25 10:29 UTC, marineshaw commented on src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx
> +      <ProgressBar currentStep={currentStep} totalStep={5} />
Je pense que c'est une mauvaise idée parce que rien ne justifie cette valeur par défaut si ce n'est que ce sera celle de l'inscription, la progressBar est destinée à une utilisation plus large que ça !

2023-05-25 10:32 UTC, pierrecanthelou commented on src/features/auth/pages/signup/ProgressBar/ProgressBar.tsx
> +          duration={800}
Que penses-tu de le mettre dans une constante plutôt qu'un nombre magique ?

2023-05-25 10:32 UTC, pierrecanthelou commented on src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx
> +  const [currentStep, updateStep] = useReducer((v: number, incr: number) => v + incr, 0)
dac

2023-05-25 10:35 UTC, pierrecanthelou commented on src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx
> +        <StyledButton wording="Next Step" onPress={goToNextStep} disabled={currentStep === 5} />
Que penses-tu d'introduire de suite des constantes genre IS_FIRST_STEP = currentStep === 0;

2023-05-25 10:36 UTC, pierrecanthelou commented on src/features/auth/pages/signup/ProgressBar/ProgressBar.tsx
> +  const progressionRatio = (currentStep / totalStep) * 100
Je ne sais pas si cela est explicite ?

2023-05-25 10:37 UTC, pierrecanthelou commented on src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx
> +      <ProgressBar currentStep={currentStep} totalStep={5} />
C'est moi qui ait mal lu le code désolé !

2023-05-25 12:20 UTC, marineshaw commented on src/features/auth/pages/signup/ProgressBar/ProgressBar.tsx
> +          isFull={currentStep === totalStep}
Ah j'ai oublié de push 🙈🙈🙈

2023-05-25 15:09 UTC, Lucasbeneston approved these changes

2023-05-26 08:03 UTC, merged