(PC-22512) fix(offer): finalization modal choice another venue
pass-culture/pass-culture-app-native pull request #4830
Opened 2023-05-30 07:33 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22512

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-06-01 07:53 UTC, dbenfouzari-pass requested changes
Globalement très bon, manque juste des bricoles 💪

2023-06-01 07:53 UTC, dbenfouzari-pass commented on src/features/bookOffer/helpers/useModalContent.tsx
> +export const getDefaultModalContent = (): ModalContent => {
L'export ne m'a pas l'air nécessaire ?

2023-06-01 07:53 UTC, dbenfouzari-pass commented on src/features/search/components/SearchListFooter/SearchListFooter.web.tsx
> +      <View ref={ref as LegacyRef<View>}>
Nah ça c'est pas beau.
Il faut que tu modifies le composant 
Tu as ça :
```tsx
export const SearchListFooter: React.FC<SearchListFooterProps> = forwardRef(
```
Il faut que tu aies ça
```tsx
export const SearchListFooter = forwardRef<View, SearchListFooterProps>(
```

Par ailleurs le résultat de la première condition de ce render est un `<React.Fragment ref={ref} />`. Tu penses que tu peux le corriger en même temps stp ?

2023-06-01 08:46 UTC, cedricls1 commented on src/features/bookOffer/helpers/useModalContent.tsx
> +export const getDefaultModalContent = (): ModalContent => {
Bien vu

2023-06-01 16:21 UTC, cedricls1 commented on src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx
> +    void (async () => {
J'ai pas eu le choix pour ne pas avoir le bug Sentry (si je mettais `void` ligne 163 plus bas ça ne fonctionnait plus)

2023-06-01 16:40 UTC, pierrecanthelou reviewed
Un gros boulot :)
J'ai quelques questions.

2023-06-01 16:40 UTC, pierrecanthelou commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +          venueName={offer.venue.publicName ?? offer.venue.name}
Il manque les optional-chaining venueName={offer?.venue?.publicName ?? offer?.venue?.name}

2023-06-01 16:40 UTC, pierrecanthelou commented on src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx
>    const customHeader = useMemo(() => {
Ce serait intéressant d'avoir les performances de cet écran :)

2023-06-02 07:23 UTC, cedricls1 commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +          venueName={offer.venue.publicName ?? offer.venue.name}
Ligne 211 tu as une condition qui fait que si tu arrives ici, tu as forcément une offre. Une offre sans venue me semble étrange mais on peut prévoir l'optional-chaining au cas où sur la venue

2023-06-02 07:34 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.tsx
> +          venueName={offer.venue.publicName ?? offer.venue.name}
@pierrecanthelou c'est à TypeScript de dire s'il "manque" l'optional chaining.
Si TypeScript ne dit rien ici, j'imagine qu'il considère que c'est OK, le check est déjà fait plus haut.

2023-06-02 07:35 UTC, dbenfouzari-pass commented on src/features/search/components/SearchListFooter/SearchListFooter.web.tsx
> +      <View ref={ref as LegacyRef<View>}>
Super nouvelle !

2023-06-02 07:39 UTC, dbenfouzari-pass requested changes

2023-06-02 07:39 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSelectionList/VenueSelectionList.tsx
> +          <ItemWrapper key={item.offerId}>
Normalement c'est pas nécessaire si tu as la méthode `keyExtractor` ?

2023-06-02 07:39 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSelectionList/VenueSelectionList.tsx
> +            // ref={ref}
Tu peux supprimer la ligne ?

2023-06-02 07:39 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx
> +    void (async () => {
Il m'emmerde Sentry -_-
@pierrecanthelou on a un nouveau truc qui remonte sur Sentry, comme quoi c'est un peu d'appeler une fonction asynchrone sur une fonction synchrone.
Ca nous oblige à faire des trucs vachement relous, voire parfois un peu sales comme ici, pour qu'il s'en contente.

Y'a moyen de désactiver ?

2023-06-02 07:49 UTC, cedricls1 commented on src/features/offer/components/VenueSelectionList/VenueSelectionList.tsx
> +          <ItemWrapper key={item.offerId}>
J'avais remarqué des warnings dans la console après avoir mis ça, je ne les avais plus

2023-06-02 07:51 UTC, cedricls1 commented on src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx
>    const customHeader = useMemo(() => {
ça ne sera pas vraiment significatif vu que les données viennent d'Algolia (on ne mockerait pas le hook avec une requête serveur mais comme si on faisait un test de composant)

2023-06-02 07:57 UTC, cedricls1 commented on src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.tsx
> +    ...(!isSelected ? customFocusOutline({ color: theme.colors.black, isFocus }) : {}),
Yes elle m'a dit que si je n'arrivais pas à avoir le comportement qu'on a vu ensemble, elle préférait avoir le comportement par défaut qui est la bordure bleue

2023-06-02 08:15 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueSelectionList/VenueSelectionList.tsx
> +          <ItemWrapper key={item.offerId}>
Bizarre 🤔

2023-06-02 08:17 UTC, dbenfouzari-pass approved these changes

2023-06-02 08:40 UTC, merged