(PC-22172) feat(VideoModule): VideoOffer component design
pass-culture/pass-culture-app-native pull request #4878
Opened 2023-06-09 15:20 UTC by S4andro

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22172

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

iOS:
<img width="363" alt="Capture d’écran 2023-06-09 à 17 11 15" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/fa9c3dd5-21ab-4e60-9007-2af978a2e280">

Android:
<img width="324" alt="Capture d’écran 2023-06-09 à 17 19 36" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/416348e8-b6fc-46a6-8778-9583a317bb67">

2023-06-09 15:24 UTC, S4andro commented on src/features/home/components/modules/VideoModule.tsx
> +  console.log(offer)
le console.log est enlevé dans le commit d'après

2023-06-12 09:47 UTC, anoukhello requested changes

2023-06-12 09:47 UTC, anoukhello commented on src/features/home/components/modules/VideoModule.tsx
> +// OffersModuleParameters
Commentaire oublié ?

2023-06-12 09:47 UTC, anoukhello commented on src/features/home/components/modules/VideoModule.tsx
> +        colors={['#27DCA8FF', '#0E8474FF']}
Dans quel ticket cette couleur sera définie dynamiquement ? Ça peut être cool de mettre un "// TODO(PC-XXXX) update color blabla...", pareil pour les couleurs définies en dur dans `OfferVideoModule`

2023-06-12 09:47 UTC, anoukhello commented on src/features/home/components/modules/VideoModule.tsx
> +  //https://stackoverflow.com/questions/49442165/how-do-you-add-borderradius-to-imagebackground/57616397
Un petit espace après les // ? :)

2023-06-12 09:47 UTC, anoukhello commented on src/features/home/api/useVideoOffer.ts
> +  const adaptedPlaylistParameters = useAdaptOffersPlaylistParameters()
Le hook `useAdaptOffersPlaylistParameters` retourne une méthode qui va transformer les `offersModuleParameters` en paramètre intelligibles par `fetchMultipleOffers` donc ce serait plus logique de nommer cette méthode `adaptPlaylistParameters`

2023-06-12 09:47 UTC, anoukhello commented on src/features/home/components/modules/VideoModule.tsx
> +  console.log(offer)
Tu peux éditer ton commit avec le rebase interactif, hésite pas si tu veux qu'on revoit ensemble 2-3 techniques de git

2023-06-12 09:47 UTC, anoukhello commented on src/features/home/api/useVideoOffer.ts
> +  const uniqueAdaptedParameters = [adaptedParameters].filter(isSearchState)
Pourquoi unique ?

2023-06-12 09:47 UTC, anoukhello commented on src/features/home/components/modules/OfferVideoModule.tsx
> +            à partir du {getDisplayPrice(offer?.offer?.prices)}
```suggestion
            à partir de {getDisplayPrice(offer?.offer?.prices)}
```

2023-06-12 09:49 UTC, S4andro commented on src/features/home/components/modules/VideoModule.tsx
> +  console.log(offer)
Pourquoi pas, ça me fera pas de mal de revoir ce que je sais déjà et de voir ce que je peux faire en plus

2023-06-12 09:55 UTC, tanguyprache commented on src/features/home/components/modules/OfferVideoModule.tsx
> +            à partir du {getDisplayPrice(offer?.offer?.prices)}
Même supprimer "à partir du/de" c'est `getDisplayPrice` qui s'occupe déjà d'ajouter "Dès" si besoin

2023-06-12 10:15 UTC, tanguyprache commented on src/libs/queryKeys.ts
>    SUBSCRIPTION_PROFILE_INFO = 'subscriptionProfileInfo',
Peut-être nommer la clé 'VIDEO_OFFER' c'est une offre liée à une video que l'on fetch et pas la vidéo uniquement.

2023-06-12 10:22 UTC, tanguyprache commented on src/features/home/components/modules/OfferVideoModule.tsx
> +          <AdditionalInfoText>à partir du {formatDates(timestampsInMillis)}</AdditionalInfoText>
Pareil ici supprimer "à partir du" c'est `formatDates` qui s'occupe de formatter la date

2023-06-12 10:26 UTC, S4andro commented on src/features/home/components/modules/OfferVideoModule.tsx
> +          <AdditionalInfoText>à partir du {formatDates(timestampsInMillis)}</AdditionalInfoText>
Yes, est ce que je rajoute un TODO pour que ça affiche une seule date sur l'offre dans la modale vidéo ?

2023-06-12 10:49 UTC, anoukhello commented on src/features/home/components/modules/VideoModule.tsx
> +  console.log(offer)
Je te laisse caler un point quand tu veux :)

2023-06-12 12:10 UTC, S4andro commented on src/features/home/components/modules/VideoModule.tsx
> +        colors={['#27DCA8FF', '#0E8474FF']}
J'ai pas l'impression qu'il y en ait un pour le moment :/

2023-06-12 12:29 UTC, S4andro commented on src/features/home/api/useVideoOffer.ts
> +  const uniqueAdaptedParameters = [adaptedParameters].filter(isSearchState)
Il me semble que c'est parce que il y a qu'un seul paramètre, mais peut être qu'en réfléchissant changer
`adaptedParameters` -> `partialAdaptedParameters` puisque c'est un Partial<SearchState> et
 `uniqueAdaptedParameters` -> `adaptedParameters` puisque c'est un SearchState ?

2023-06-12 12:36 UTC, anoukhello commented on src/features/home/components/modules/VideoModule.tsx
> +        colors={['#27DCA8FF', '#0E8474FF']}
@tanguyprache tu sais dans quel ticket ce sera traité ?

2023-06-12 12:38 UTC, anoukhello commented on src/features/home/api/useVideoOffer.ts
> +  const uniqueAdaptedParameters = [adaptedParameters].filter(isSearchState)
Pourquoi pas oui !

2023-06-12 12:41 UTC, anoukhello commented on src/libs/queryKeys.ts
> +  VIDEO_OFFER = 'video_offer',
Cette modif là devait aller dans le commit précédent

2023-06-12 13:00 UTC, anoukhello commented on src/features/home/api/useVideoOffer.ts
Idem, ces changements font références à des commentaires dans le commit précédent, pas au design du composant `OfferVideomodule`

2023-06-12 13:32 UTC, tanguyprache commented on src/features/home/components/modules/VideoModule.tsx
> +        colors={['#27DCA8FF', '#0E8474FF']}
Yes : PC-22765

2023-06-13 09:39 UTC, anoukhello reviewed
Les tests natifs cassent je sais pas si tu as vu

2023-06-13 10:16 UTC, anoukhello reviewed
> J'ai vu ca hier mais j'ai pas réussi à résoudre le problème :/
> et je viens de voir que les UI Tests et Review non plus sont pas bonnes

Les 2 sont liés et les erreurs sont assez explicites, tu fais un appel API avec le hook `useVideoOffer` dans `VideoModule`, donc il faut gérer ça dans les tests de ce composant et dans les stories

2023-06-13 16:46 UTC, merged