(PC-20703) fix(Header): set header in white for android
pass-culture/pass-culture-app-native pull request #4900
Opened 2023-06-13 21:41 UTC by S4andro

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20703

## Checklist

I have:

- [x] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [x] Written **unit tests** native (and web when implementation is different) for my feature.
- [x] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

Changes only for Android

| Before | After |
| :-: | :-: |
| <img width="292" alt="Capture d’écran 2023-06-13 à 23 47 21" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/4db5c131-0d25-4779-b9ef-5606b1447154"> | <img width="284" alt="Capture d’écran 2023-06-13 à 23 46 29" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/64484b24-276c-4a0c-91c2-a415d8c3709d"> |
|<img width="1512" alt="Capture d’écran 2023-06-15 à 13 47 29" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/753777c7-47a1-409a-9df2-4c486cbd1876">|<img width="1512" alt="Capture d’écran 2023-06-15 à 13 53 02" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/a6768268-a00c-4ced-a0e3-2950d51f743d">|
|![simulator_screenshot_5CF40152-63FB-4976-9843-1C41B9547FA6](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/002d6a7a-5b27-4f1e-8c79-2a2f68c14990)|![simulator_screenshot_18E51B50-27E5-4001-AA1F-67ACAB8744A8](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/4301c0aa-69ca-4e05-aeb3-cd8385872d75)|

2023-06-14 14:09 UTC, bruno-ebstein-pass-culture approved these changes

2023-06-14 14:09 UTC, bruno-ebstein-pass-culture commented on src/features/venue/components/VenueHeader/VenueHeader.tsx
> +        }
peut etre que ça pourrait etre extrait dans un composant qui render `false` sur android ?

2023-06-14 14:21 UTC, voisinhugo commented on src/features/venue/components/VenueHeader/VenueHeader.tsx
> +        }
En vrai si, surtout que c'est exactement le même composant pour les 4 : je peux les mettre en commun directement, et gérer la disjonction là-bas 👍

2023-06-15 08:18 UTC, bruno-ebstein-pass-culture requested changes

2023-06-15 08:18 UTC, bruno-ebstein-pass-culture commented on src/ui/components/headers/BlurHeader.tsx
> +  if (Platform.OS !== 'android') return null
```suggestion
  if (Platform.OS === 'android') return false
```

2023-06-15 09:58 UTC, tanguyprache commented on src/ui/components/headers/BlurHeader.tsx
> +  if (Platform.OS !== 'android') return null
@bruno-ebstein-pass-culture Je suis d'accord pour la condition par contre je ne peux pas retourner un booléen pour un élément JSX non ?

2023-06-15 10:42 UTC, tanguyprache commented on src/ui/components/headers/BlurHeader.tsx
> +  if (Platform.OS !== 'android') return null
Ok je ne savais pas - mais oui du coup il n'y a pas de risque d'effets de bord avec `null`

2023-06-15 10:43 UTC, tanguyprache commented on src/features/offer/components/OfferHeader/OfferHeader.tsx
> +const HeaderContainer = styled(Animated.View)<{ height: number }>(({ theme, height }) => ({
Oui on le retrouve 3 fois il me semble ca pourrait être embarqué plus tard

2023-06-15 12:08 UTC, bruno-ebstein-pass-culture approved these changes

2023-06-15 12:17 UTC, merged