(PC-22693) feat(MultivenueOptionDisplayed): add new tracker
pass-culture/pass-culture-app-native pull request #4915
Opened 2023-06-16 13:01 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22693

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-06-16 14:06 UTC, YassinL commented
Concernant les deux bugs remontés par Sonar est ce que vous avez une idée sur la possible correction. je sais que Cédric avait corrigé cela de cette manière exemple : (ce qui nous semblait assez bizarre de devoir faire ça)
```jsx
    void (async () => {
      await openStore()
    })()
```

2023-06-16 14:43 UTC, dbenfouzari-pass requested changes

2023-06-16 14:43 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx
> +}))
J'ai vraiment la sensation que ces lignes sont inutiles. Tu peux essayer en les supprimant ?

2023-06-16 14:43 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx
> +}))
Ce serait plus simple de faire :

```suggestion
const mockUseOffer = jest.fn().mockReturnValue({
  data: offerResponseSnap,
})
```

2023-06-16 14:43 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx
> +}
Ce sont des constantes. Par définition ça veut dire que tu ne les changeras pas.
Dans ce cas je te conseille de les intégrer directement.

2023-06-16 14:43 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx
> +}))
Tu aurais donc

```suggestion
jest.mock('api/useSearchVenuesOffer/useSearchVenueOffers', () => ({
  useSearchVenueOffers: () => ({
    hasNextPage: true,
    fetchNextPage: jest.fn(),
    data: {
      pages: [
        {
          nbHits: 0,
          hits: [],
          page: 0,
        },
      ],
    },
    venueList: mockVenueList,
    nbVenueItems: mockNbVenueItems,
    isFetching: false,
  }),
}))
```

2023-06-16 14:43 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx
> +      }))
Idem que plus haut, je pense que tu peux faire plus simple
```suggestion
      mockUseOffer.mockReturnValue({
        data: {
          ...offerResponseSnap,
          subcategoryId: SubcategoryIdEnum.LIVRE_PAPIER,
          extraData: {
            ean: '2765410054',
          },
        },
      })
```

2023-06-16 14:43 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx
> +      useFeatureFlagSpy.mockImplementation(() => true)
```suggestion
      useFeatureFlagSpy.mockReturnValue(true)
```

2023-06-16 14:45 UTC, dbenfouzari-pass commented
J'ai également la sensation que puisque tu fais `mockReturnValue` ou `mockImplementation` tes tests fonctionnent un peu par change.
Par exemple, si tu mettais tes tests au début de la suite de tests je pense que les suivants casseraient.

Donc j'ai l'impression qu'il manque un/des `afterAll` dans ton describe.

2023-06-19 07:55 UTC, YassinL commented on src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx
> +}))
J'en ai besoin car si je le retire il ne trouve pas le mock du useOffer

2023-06-19 08:46 UTC, YassinL commented on src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx
> +}))
Il me semblait que oui mais maintenant je ne suis plus sur car si je le retire il ne trouve plus le bouton `Voir d’autres lieux disponibles`. Si je retire le mock du useOffer, `isMultivenueCompatibleOffer` dans `OfferBody` passe à false ça veut dire que c'est plus mocké et il ne retrouve pas ce que je lui ai demandé de changer dans le beforeEach : 
```jsx
mockUseOffer.mockReturnValue({
        data: {
          ...offerResponseSnap,
          subcategoryId: SubcategoryIdEnum.LIVRE_PAPIER,
          extraData: {
            ean: '2765410054',
          },
        },
      })
```

2023-06-19 14:23 UTC, merged