(PC-22552) feat(useSortedSearchCategories): sorted categories by desired order
pass-culture/pass-culture-app-native pull request #4931
Opened 2023-06-20 10:01 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22552

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-06-20 13:48 UTC, dbenfouzari-pass requested changes
Tel que tu l'as fait, si le back ajoute une catégorie elle disparaît du front.

2023-06-20 14:06 UTC, dbenfouzari-pass commented
> @dbenfouzari-pass C'est vrai vu que la réorganisation est désormais statique, je ne voyais pas comment j'aurai pu faire autrement ? si tu as une suggestion je suis preneur

Déjà il faut que tu fasses en sorte que la catégorie ne disparaisse pas. Dans l'idéal il faudrait aussi que tu n'aies pas à répéter le nom des catégories. J'en parlais au daily ce matin, et hier aussi.
Ensuite il faudrait que les catégories "inconnues" puissent êtres inclues à la fin.

2023-06-20 15:18 UTC, YassinL commented
@dbenfouzari-pass  Tu en penses quoi de ces changements ? j'ai géré le cas des catégories "inconnues" et il seront en fin de liste. 
Concernant l'ordre je ne vois pas comment je pourrai faire autrement de réécrire les catégories dans le bon ordre. 
Si tu veux on peut voir ça ensemble demain si vois autre choses ?

2023-06-21 09:13 UTC, dbenfouzari-pass requested changes

2023-06-21 09:13 UTC, dbenfouzari-pass commented on src/features/search/helpers/useSortedSearchCategories/useSortedSearchCategories.tsx
> +    .sort((a, b) => a.position - b.position)
Puisque `position` peut être `undefined`, surtout si l'API ajoute des catégories.

```suggestion
    .sort((a, b) => {
      if (a.position === undefined) return 0
      if (b.position === undefined) return 0
      return a.position - b.position
    })
```

Je ne sais pas si ça ferait le taf précisément mais il faut jouer avec pour trouver quelque chose qui marche.

2023-06-21 09:15 UTC, dbenfouzari-pass commented on src/features/search/helpers/useSortedSearchCategories/useSortedSearchCategories.tsx
> +    .sort((a, b) => a.position - b.position)
Après peut-être que ce que tu avais fait fonctionnait. Mais je veux bien voir le test du genre

```
const items = {
  toto: { position: 1 },
  tata: { position: undefined },
  titi: { position: 2 }
}
```

et vérifier qu'on a bien `["toto", "titi", "tata"]`

2023-06-23 13:58 UTC, dbenfouzari-pass approved these changes

2023-06-23 14:02 UTC, merged