(PC-21177) upgrade react-native to 0.71.12
pass-culture/pass-culture-app-native pull request #5136
Opened 2023-08-09 14:20 UTC by Lucasbeneston

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21177

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-09-07 12:49 UTC, Lucasbeneston commented
> # Performance Comparison Report
> * **Current**: HEAD ([db917e1](https://github.com/pass-culture/pass-culture-app-native/commit/db917e1cbe05212a14fd8808b417a95efab10571))
> * **Baseline**: master ([9264bc0](https://github.com/pass-culture/pass-culture-app-native/commit/9264bc0ec113656211d94fadb2b3ad95adabd03f))
> 
> ### Significant Changes To Render Duration
> Name	Render Duration	Render Count
> Performance test for Offer page	494.0 ms → 563.6 ms (+69.6 ms, +14.1%) 🔴	12 → 12
> Performance test for Venue page	371.3 ms → 407.3 ms (+36.0 ms, +9.7%) 🔴	9 → 9
> Performance test for Favorites page	118.7 ms → 147.3 ms (+28.6 ms, +24.1%) 🔴	8 → 9 (+1, +12.5%) 🔴
> Performance test for Profile page	118.2 ms → 132.1 ms (+13.9 ms, +11.8%) 🔴	8 → 8
> Search Results - Performance test for Search Results page	106.6 ms → 116.4 ms (+9.8 ms, +9.2%) 🔴	11 → 11
> Search Landing Page - Performance test for Search Landing page	84.4 ms → 89.8 ms (+5.4 ms, +6.4%) 🔴	6 → 6
> Search Suggestions - Performance test for Search Suggestions page	35.0 ms → 40.0 ms (+5.0 ms, +14.3%) 🔴	7 → 7
> Show details
> ### Meaningless Changes To Render Duration
> Show entries
> Show details
> ### Changes To Render Count
> Name	Render Duration	Render Count
> Performance test for Favorites page	118.7 ms → 147.3 ms (+28.6 ms, +24.1%) 🔴	8 → 9 (+1, +12.5%) 🔴
> Performance test for Bookings page	49.2 ms → 52.8 ms (+3.6 ms, +7.3%)	7 → 8 (+1, +14.3%) 🔴
> Show details
> ### Added Scenarios
> _There are no entries_
> 
> ### Removed Scenarios
> _There are no entries_
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [45a5833](https://github.com/pass-culture/pass-culture-app-native/commit/45a5833b24be09285a1ee658ce20bfdf70e91de9)

Je ne sais pas pourquoi il y a un render de plus sur Favorites et Bookings :(

2023-09-08 08:07 UTC, aliraiki reviewed
Je dois encore tester : 

- [ ] Build iOS, Android et Web
- [x] [Déploiement hard](https://github.com/pass-culture/pass-culture-app-native/actions/runs/6118870121/job/16607719323?pr=5136)
- [x] [Déploiement soft](https://github.com/pass-culture/pass-culture-app-native/actions/runs/6119360138/job/16609135833?pr=5136)
- [ ] App iOS et Android **en mode Release**
- [x]  Téléchargement et installation des codepush
- [x] Notifications Batch
- [ ] Flipper

2023-09-08 08:07 UTC, aliraiki commented on src/features/offer/api/useSimilarOffers.native.test.ts
> +        })
Vu que c'est un `not.toHaveBeenCalled()`, je préfère utiliser `act` plutôt que `waitFor` : 
```
        await act(async () => {})
        expect(getRelatedProductsSpy).not.toHaveBeenCalled()
```

2023-09-08 08:07 UTC, aliraiki commented on src/features/offer/api/useSimilarOffers.native.test.ts
> +      await act(async () => {})
Vu le test est skip : 
- Est-ce que c'est mieux de pas le modifier ?
- Est-ce que c'est possible d'ajouter une TODO ou FIXME avec le ticket pour unskip le test ?

2023-09-08 08:07 UTC, aliraiki commented on src/features/offer/api/useSimilarOffers.native.test.ts
> +      await act(async () => {})
Tu peux le mettre avant le `expect`, c'est plus "logique" et ça marchera très bien

2023-09-08 11:01 UTC, aliraiki commented
Ca serait top d'avoir le lien vers la doc suivie dans les commits

2023-09-08 12:31 UTC, Lucasbeneston commented on src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
> +const FixedBottomChildrenView = styled(View)({
Oui c'est lorsqu'on utilise un `onLayout` il y une erreur de typing : 

```
src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx:203:32 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Omit<Omit<ViewProps & RefAttributes<View>, never> & Partial<Pick<ViewProps & RefAttributes<View>, never>>, "theme"> & { ...; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type '(event: import("/Users/lucasbeneston/Desktop/pass-culture-app-native/node_modules/react-native/Libraries/Types/CoreEventTypes").LayoutChangeEvent) => void' is not assignable to type '(event: import("/Users/lucasbeneston/Desktop/pass-culture-app-native/node_modules/@types/styled-components-react-native/node_modules/@types/react-native/index").LayoutChangeEvent) => void'.
      Types of parameters 'event' and 'event' are incompatible.
        Type 'import("/Users/lucasbeneston/Desktop/pass-culture-app-native/node_modules/@types/styled-components-react-native/node_modules/@types/react-native/index").LayoutChangeEvent' is not assignable to type 'import("/Users/lucasbeneston/Desktop/pass-culture-app-native/node_modules/react-native/Libraries/Types/CoreEventTypes").LayoutChangeEvent'.
          Types of property 'currentTarget' are incompatible.
            Type 'Component<unknown, {}, any> & Readonly<NativeMethods>' is not assignable to type 'number'.
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<typeof View, DefaultTheme, {}, never, typeof View, typeof View>): ReactElement<StyledComponentPropsWithAs<typeof View, DefaultTheme, {}, never, typeof View, typeof View>, string | JSXElementConstructor<...>>', gave the following error.
    Type '(event: import("/Users/lucasbeneston/Desktop/pass-culture-app-native/node_modules/react-native/Libraries/Types/CoreEventTypes").LayoutChangeEvent) => void' is not assignable to type '(event: import("/Users/lucasbeneston/Desktop/pass-culture-app-native/node_modules/@types/styled-components-react-native/node_modules/@types/react-native/index").LayoutChangeEvent) => void'.

203       <FixedBottomChildrenView onLayout={onFixedBottomChildrenViewLayout}>
                                   ~~~~~~~~

  node_modules/@types/styled-components-react-native/node_modules/@types/react-native/index.d.ts:2586:5
    2586     onLayout?: ((event: LayoutChangeEvent) => void) | undefined;
             ~~~~~~~~
    The expected type comes from property 'onLayout' which is declared here on type 'IntrinsicAttributes & Omit<Omit<ViewProps & RefAttributes<View>, never> & Partial<Pick<ViewProps & RefAttributes<...>, never>>, "theme"> & { ...; } & { ...; } & { ...; }'
  node_modules/@types/styled-components-react-native/node_modules/@types/react-native/index.d.ts:2586:5
    2586     onLayout?: ((event: LayoutChangeEvent) => void) | undefined;
             ~~~~~~~~
    The expected type comes from property 'onLayout' which is declared here on type 'IntrinsicAttributes & Omit<Omit<ViewProps & RefAttributes<View>, never> & Partial<Pick<ViewProps & RefAttributes<...>, never>>, "theme"> & { ...; } & { ...; } & { ...; }'


Found 1 error in src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx:203
```

2023-09-08 12:41 UTC, Lucasbeneston commented on src/features/offer/api/useSimilarOffers.native.test.ts
> +      await act(async () => {})
Oui tu as raison, c'est mieux de ne pas le modifier

2023-09-08 14:17 UTC, Lucasbeneston commented
> Ca serait top d'avoir le lien vers la doc suivie dans les commits

Yes je viens de l'ajouter !

2023-09-11 07:45 UTC, aliraiki commented on src/features/offer/api/useSimilarOffers.native.test.ts
> +      await act(async () => {})
Le test est toujours modifié j'ai l'impression

2023-09-11 12:25 UTC, Lucasbeneston commented
Le problème du bouton favoris est fix ! 

| ios                        | web mobile                         | android          |       web desktop |
| ---------------- | ----------------- | ------- | -------- |
|  ![image (1)](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/e0bf80b1-0e98-4444-bb84-ad78a93a3a94) | ![image (3)](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/39651efe-3eff-4052-9f29-590aebc4a0b0)  | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/b3a128c5-6893-4f36-9fe7-499ce7a5b15c) |   ![image (2)](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/a72f196e-a9af-4173-b067-64ef56b4f0fb) |

2023-09-11 16:43 UTC, aliraiki approved these changes
J'ai un warning sur Metro quand je lance l'app `Expected style "elevation: ...px" to be unitless`, je sais pas si c'est nouveau sur master ou si c'est à cause de la MAJ

2023-09-12 09:13 UTC, aliraiki requested changes
Faut mettre à jour le `Podfile.lock` vu que t'as remis à jour react-native

2023-09-12 10:13 UTC, aliraiki approved these changes

2023-09-12 10:14 UTC, aliraiki commented on ios/Podfile.lock
> +COCOAPODS: 1.12.1
Je suis toujours en 1.12.0 perso je sais pas quelle version il faut

2023-09-12 10:27 UTC, Lucasbeneston commented on ios/Podfile.lock
> +COCOAPODS: 1.12.1
Anouk et Yassin sont en 1.12.1, ça ne pose pas de problème je pense. Surtout que lors de la dernière MaJ de react-native, il me semble qu'on est passé de 1.11.x à 1.12.0

2023-09-14 13:03 UTC, merged

2024-06-26 12:51 UTC, Lucasbeneston commented
> Je dois encore tester :
> 
> ✅ Apps iOS et Android fonctionnelles **en mode Debug** ✅ Apps iOS et Android fonctionnelles **en mode Release** ✅ [Déploiement hard iOS/Android](https://github.com/pass-culture/pass-culture-app-native/actions/runs/6118870121/job/16607719323?pr=5136) ✅ [Déploiement soft iOS/Android](https://github.com/pass-culture/pass-culture-app-native/actions/runs/6119360138/job/16609135833?pr=5136) ❌ Déploiement Web : erreur au build `Duplicate Sources / Packages - Duplicates found! ⚠️` ([plus d'infos ici](https://github.com/pass-culture/pass-culture-app-native/actions/runs/6119360138/job/16609558748?pr=5136)) ✅ Téléchargement et installation des codepush sur iOS et Android ✅ Notifications Batch iOS et Android ✅ Flipper iOS et Android ❌ Régressions visuelles (petit tour dans l'app) :
> 
> * Icône favori dans la tabbar KO (pas de chiffre sur iOS et Android, OK pour Web) :
>   <img alt="" width="200" src="https://private-user-images.githubusercontent.com/46637324/266555791-09304cda-8337-47a0-ae2a-c81cab2d7add.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDY1ODYsIm5iZiI6MTcxOTQwNjI4NiwicGF0aCI6Ii80NjYzNzMyNC8yNjY1NTU3OTEtMDkzMDRjZGEtODMzNy00N2EwLWFlMmEtYzgxY2FiMmQ3YWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEyNTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMmEyMzYyM2MyMWFkOTU0ZmRkMTMzYTQ2OTA0MmQ5MGFiZGE5NjUxODQ3MmI2NDJjNmI0Y2FjMTE3NTQxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.548udQyncSzrd5T_Z_25PmCZT0GtZ3DSzavdEe926Eg"> <img alt="" width="200" src="https://private-user-images.githubusercontent.com/46637324/266555866-e557fef8-6350-48e4-8b44-7fa4ee842391.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDY1ODYsIm5iZiI6MTcxOTQwNjI4NiwicGF0aCI6Ii80NjYzNzMyNC8yNjY1NTU4NjYtZTU1N2ZlZjgtNjM1MC00OGU0LThiNDQtN2ZhNGVlODQyMzkxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEyNTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZTBlMWY3MTY4NDFmNDNmOGM2MDFlZmEzOTRhNTIwZDVkM2NhZmUzM2E2MDI5N2RlMDZjMTQ4M2I5YjdlODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kFLWO5AbEeudA4d13zcRfY0zdS8hG_U6jjQ_oW9dmcY">

@tanguyprache