(PC-23559) feat(seo): De-index search pages
pass-culture/pass-culture-app-native pull request #5155
Opened 2023-08-14 08:00 UTC by aliraiki

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23559

## Checklist

I have:

- [x] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [x] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-08-16 13:51 UTC, bruno-ebstein-pass-culture commented
si dans un futur (proche ou lointain) on change l'URL de résultat de recherche (sans changer dans le proxy [oublie, méconnaissance ...])

les tests actuels continuerons de passer

ça serait bien que quelqu'un de la squadix (lead dev?) soit informé de ce changement

2023-08-16 15:18 UTC, aliraiki commented on server/src/middlewares/webAppProxyMiddleware.ts
> +const searchResultsPageRegex = /\/recherche\?.*view=("|%22)Results("|%22)/
@bruno-ebstein-pass-culture Est-ce que les urls qu'on reçoit côté proxy sont toujours encodées ? Histoire de simplifier à ça :
```suggestion
const searchResultsPageRegex = /\/recherche\?.*view=%22Results%22/
```

2023-08-16 15:21 UTC, aliraiki commented
@cedricls1 On désindexe les résultats de la recherche dans le proxy maintenant. Si dans un futur vous changez change l'URL de résultat de recherche (ou les paramètres), pensez à faire ce changement côté proxy aussi :)

2023-08-17 07:02 UTC, aliraiki commented
Solution retenue : 
- Désindexer les pages de recherche dès qu'elles contiennent un paramètre
- Indexer la page de filtres de recherche

2023-08-17 07:12 UTC, bruno-ebstein-pass-culture approved these changes

2023-08-17 07:12 UTC, bruno-ebstein-pass-culture commented on server/src/middlewares/webAppProxyMiddleware.ts
> +const searchPageWithParamsRegex = /\/recherche\?/
question(non-blocking): pourquoi une RegExp et pas URL ?

2023-08-17 07:46 UTC, bruno-ebstein-pass-culture requested changes

2023-08-17 07:46 UTC, bruno-ebstein-pass-culture commented on server/src/middlewares/webAppProxyMiddleware.ts
> +    if (req.url.match(searchPageWithParamsRegex)) {
les regex c'est pas le mieux niveau perf, là on recherche une chaine statique

2023-08-17 08:53 UTC, bruno-ebstein-pass-culture approved these changes

2023-08-17 08:53 UTC, bruno-ebstein-pass-culture commented on server/src/middlewares/webAppProxyMiddleware.ts
> +const searchPageWithParamsRegex = /\/recherche\?/
💀 code

2023-08-17 09:53 UTC, merged