(PC-23999) feat(search): use user position when location filter is everywhere to build search query
pass-culture/pass-culture-app-native pull request #5206
Opened 2023-08-24 15:08 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23999

## Checklist

I have:

- [x] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [x] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-08-25 12:58 UTC, dbenfouzari-pass requested changes

2023-08-25 12:58 UTC, dbenfouzari-pass commented on src/features/search/components/SearchResults/SearchResults.tsx
> +  }, [refetch, userPosition])
C'est pas terrible, ça risque de refetch si l'utilisateur marche ou que sa géoloc fasse des dingueries.
Il faudrait soit avoir un `prevUserPosition` et comparer qu'ils sont différents, soit c'est ce qu'on veut mais je trouve ça étonnant.

2023-08-28 07:23 UTC, cedricls1 commented on src/features/search/components/SearchResults/SearchResults.tsx
> +  }, [refetch, userPosition])
Après comparer systématiquement que la précédente position est différente ça revient au même je pense sauf si on refetch uniquement si la précédente position est non définie.
Je regarde

2023-08-28 08:07 UTC, dbenfouzari-pass commented on src/features/search/components/SearchResults/SearchResults.tsx
> +  }, [refetch, userPosition])
Oui je veux dire `prevHasUserPosition` plutôt pardon. En somme vérifier que la position est passée de "je n'existe pas" à "j'existe" ou l'inverse.

2023-08-28 11:55 UTC, dbenfouzari-pass commented on src/features/search/components/SearchResults/SearchResults.tsx
> +  }, [previousUserPosition, refetch, userPosition])
Quitte à le mettre dans une variable, tu aurais pu alors sortir la variable pour te débarasser d'une dépendance, ç'aurait peut-être été plus clair. Mais pas de souci.

```suggestion
  const shouldRefetchResults = Boolean(
    (userPosition && !previousUserPosition) || (!userPosition && previousUserPosition)
  ) // ou useMemo mais pas nécessaire

  useEffect(() => {
    if (shouldRefetchResults) {
      refetch()
    }
  }, [refetch, shouldRefetchResults])
```

2023-08-28 11:55 UTC, dbenfouzari-pass approved these changes

2023-08-28 12:58 UTC, merged