(PC-24431) fix(SelectableListItem): fix the height when we have a distance tag
pass-culture/pass-culture-app-native pull request #5286
Opened 2023-09-13 15:18 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-09-13 15:34 UTC, dbenfouzari-pass commented
Je n’aime pas deux choses :
* je trouve ça horrible de passer ce genre de `boolean`. Aujourd’hui c’est ça et demain il y aura peut-être 10 conditions.
* même si ça marche, si demain on souhaitait modifier la font size ou autre tout serait cassé.

Ma préconisation c’est donc de ne pas afficher une hauteur fixe mais plutôt tricher pour avoir un composant qui a la hauteur souhaitée. A base par exemple de `<View style={{ height: getSpacing(2) }} />` intermédiaire tu vois l’idée ?
De cette façon ton composant fait la bonne hauteur mais s’agrandit au besoin.

En tous cas là je ne peux pas donner un approve sur cette solution. Vous en pensez quoi @cedricls1  et @pierrecanthelou  ?

2023-09-13 15:35 UTC, dbenfouzari-pass requested changes
Je n’aime pas deux choses :
* je trouve ça horrible de passer ce genre de `boolean`. Aujourd’hui c’est ça et demain il y aura peut-être 10 conditions.
* même si ça marche, si demain on souhaitait modifier la font size ou autre tout serait cassé.

Ma préconisation c’est donc de ne pas afficher une hauteur fixe mais plutôt tricher pour avoir un composant qui a la hauteur souhaitée. A base par exemple de `<View style={{ height: getSpacing(2) }} />` intermédiaire tu vois l’idée ?
De cette façon ton composant fait la bonne hauteur mais s’agrandit au besoin.

En tous cas là je ne peux pas donner un approve sur cette solution. Vous en pensez quoi @cedricls1  et @pierrecanthelou  ?

2023-09-13 15:47 UTC, pierrecanthelou commented
> A base par exemple de `<View style={{ height: getSpacing(2) }} />` i

Il y a déjà un composant spacer dans le code que nous utilisons pour espacer les composants sans inclure les marges ou autre espaces vides DANS un composant.

Cela permet de mettre la condition vers ce Space.column(getSpacing(2)) spécifique.

2023-09-14 12:46 UTC, dbenfouzari-pass commented
> > A base par exemple de `<View style={{ height: getSpacing(2) }} />` i
> 
> Il y a déjà un composant spacer dans le code que nous utilisons pour espacer les composants sans inclure les marges ou autre espaces vides DANS un composant.
> 
> Cela permet de mettre la condition vers ce Space.column(getSpacing(2)) spécifique.

Oui effectivement. Mais je te demandais plutôt si t’étais d’accord avec ma proposition :P

2023-09-14 14:12 UTC, pierrecanthelou commented
> Oui effectivement. Mais je te demandais plutôt si t’étais d’accord avec ma proposition :P

Nous avons traité un problème identique dans un bout de code, et nous avons bien tous conclus qu'il était préférable de laisser les composants libres et sans information de marge par rapport à l'espace qui l'environne. C'est à son conteneur de définir l'espace.

On est ok ?

2023-09-15 15:00 UTC, YassinL commented
Vu avec @dbenfouzari-pass et Aline. Dans ce cas là nous sommes obligé de mettre une taille fix mais nous avons opté pour une différente approche.

2023-09-15 15:19 UTC, pierrecanthelou approved these changes
Ok si vu avec Aline et Donovan :)

2023-09-18 08:16 UTC, dbenfouzari-pass approved these changes

2023-09-18 08:16 UTC, dbenfouzari-pass commented on src/features/offer/components/VenueDetails/VenueDetails.tsx
> +const Wrapper = styled(View)<{ height: Size }>((props) => ({
Je préfèrerai que tu appelles la prop `size` plutôt que `height`.
Et aussi dans mon idée je n’imaginais pas cette solution (qui est de compute `distance ? Size.Large : Size.Small`) mais tout compte fait je pense que c’est pas trop mal.

Je t’approuve quand même la PR parce que c’est un détail mais je te laisse choisir ce que tu fais.

2023-09-18 12:24 UTC, merged