WIP
pass-culture/pass-culture-app-native pull request #5314
Opened 2023-09-21 08:07 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** *if no UI change*

| Platform         | Before | After |
| :--------------- | :----: | :---: |
| iOS              |        |       |
| Android          |        |       |
| Phone - Chrome   |        |       |
| Tablet - Chrome  |        |       |
| Desktop - Chrome |        |       |
| Desktop - Safari |        |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-09-26 09:24 UTC, dbenfouzari-pass requested changes

2023-09-26 09:24 UTC, dbenfouzari-pass commented on src/features/search/api/useSearchResults/useSearchResults.native.test.ts
> +    it('should fetch offers, venues and all facets', async () => {
Mais du coup on ne voit pas les facets dans ton test ?

2023-09-26 09:24 UTC, dbenfouzari-pass commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
> +    return `+100 résultats`
```suggestion
    return '+100 résultats'
```

2023-09-26 09:24 UTC, dbenfouzari-pass commented on src/ui/components/radioButtons/RadioButton.tsx
>  interface RadioButtonProps {
C'est vraiment utile de modifier `RadioButton` ? J'ai pas l'impression qu'on l'utilise

2023-09-26 09:24 UTC, dbenfouzari-pass commented on src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.ts
> +    it('should return "{nbResultsFacet} résultat" for nbResultsFacet < 1', () => {
```suggestion
    it('should return "{nbResultsFacet} résultat" for nbResultsFacet = 0, () => {
```

2023-09-26 09:24 UTC, dbenfouzari-pass commented on src/features/search/helpers/categoriesHelpers/mapping-tree.ts
> +  facetsData?: Record<string, Record<string, number>>
Je n'aime pas du tout le type...
Tu peux essayer de mieux faire ? Genre 
```tsx
type FacetKeys = 'offer.nativeCategoryId' | '...'
type SingleFacetData = Record<NativeCategoryEnum, number>
type FacetData = Record<FacetKeys, SingleFacetData>
```

Ou même un truc mieux du genre 
```ts
type NativeCategoryFacets = Record<'offer.nativeCategoryId', Record<NativeCategoryEnum, number>>
...
type FacetData = NativeCategoryFacets | ...
```

pour que ce soit moins aléatoire.

2023-09-26 09:38 UTC, YassinL commented on src/features/search/api/useSearchResults/useSearchResults.native.test.ts
> +    it('should fetch offers, venues and all facets', async () => {
Si on les voit dans je mock bien les offers/venues/facets dans le spyOn, tu veux que je change le nom du spyOn ? 
```jsx
    offersResponse: mockedAlgoliaResponse,
    venuesResponse: mockedAlgoliaVenueResponse,
    facetsResponse: mockedFacets,
```

2023-09-26 09:41 UTC, dbenfouzari-pass commented on src/features/search/api/useSearchResults/useSearchResults.native.test.ts
> +    it('should fetch offers, venues and all facets', async () => {
Ah au temps pour moi, je m'attendais à voir quelque chose dans le test moi.

2023-09-26 09:43 UTC, YassinL commented on src/ui/components/radioButtons/RadioButton.tsx
>  interface RadioButtonProps {
Oui c'est vraiment nécessaire si on veut rajouter les `nbResultsFacet`, le `RadioButton` est utilisé principalement en mobile lorsqu'on veut sélectionnée une sous catégorie sinon c'est le `FilterRow` qui est utilisé en web. 
Du coup on a bien besoin de modifié les deux composants.
Dans ce cas on ajoute une props `complement` pour que ça reste assez générique.

2023-09-26 09:45 UTC, dbenfouzari-pass commented on src/ui/components/radioButtons/RadioButton.tsx
>  interface RadioButtonProps {
Effectivement pour le voir j'ai dû dérouler le code qui était caché.

2023-09-27 08:30 UTC, dbenfouzari-pass commented on src/features/search/components/FilterRow/FilterRow.tsx
> -      <Spacer.Flex />
Normal d'avoir supprimé le spacer ici ?

2023-09-27 08:36 UTC, YassinL commented on src/features/search/components/FilterRow/FilterRow.tsx
> -      <Spacer.Flex />
Oui on a du le supprimer car il cassait l'UI de composant avec l'ajout de la nouvelle props `complement`. 
Vu qu'on a changé la disposition des blocks du composant pour ajouter le nouveau block.

2023-09-27 09:34 UTC, dbenfouzari-pass commented on src/features/search/pages/modals/CategoriesModal/CategoriesSection.tsx
> +            const shouldHideArrow = !item.children
C'est cool mais dans ce cas, tu peux supprimer la ligne qui disable ESLint ? 🙏

2023-09-27 09:37 UTC, dbenfouzari-pass approved these changes

2023-09-27 10:15 UTC, merged