(PC-24896) fix(Slider): fix Slider infinite loop
pass-culture/pass-culture-app-native pull request #5413
Opened 2023-10-09 14:06 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24896

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** _if no UI change_

| Platform         | Mockup/Before | After |
| :--------------- | :-----------: | :---: |
| iOS              |               |       |
| Android          |               |       |
| Phone - Chrome   |               |       |
| Desktop - Chrome |               |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-10-09 15:59 UTC, dbenfouzari-pass requested changes

2023-10-09 15:59 UTC, dbenfouzari-pass commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +        <Typo.ButtonText>{`${internalValue?.[0]}\u00a0h et ${internalValue?.[1]}\u00a0h`}</Typo.ButtonText>
J'aurai plutôt créé des constantes 
```tsx
const [minHour, maxHour] = internalValue || [0, 24]

...

<Typo.ButtonText>{`${minHour}\u00a0h et ${maxHour}\u00a0h`}</Typo.ButtonText>
```

2023-10-09 16:01 UTC, Lucasbeneston commented on src/features/search/components/LocationSlider/LocationSlider.tsx
> +        <Typo.Body>{`Dans un rayon de\u00a0:`}</Typo.Body>
```suggestion
        <Typo.Body>Dans un rayon de&nbsp;:</Typo.Body>
```

2023-10-09 16:02 UTC, Lucasbeneston commented on src/features/search/components/LocationSlider/LocationSlider.tsx
> +        minMaxValuesComplement={`\u00a0km`}
```suggestion
        minMaxValuesComplement="&nbsp;km"
```

2023-10-09 16:46 UTC, Lucasbeneston commented
Il y a 3 issues Sonar :(

2023-10-10 10:01 UTC, dbenfouzari-pass approved these changes

2023-10-10 13:30 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +        minMaxValuesComplement="h"
pourquoi ça ne réutilise pas la propriété `formatValues` ?

2023-10-10 13:30 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +const hoursLabelId = uuidv4()
est-il possible d'avoir plusieurs cet input sur la page ?

2023-10-10 13:30 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +export function HoursSlider({ defaultValue, onChange }: Readonly<HoursSliderProps>) {
est-ce qu'il serait pertinent d'avoir des stories pour ce slider ?

2023-10-10 13:30 UTC, bruno-ebstein-pass-culture commented on src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx
> +                      <HoursSlider defaultValue={value ?? [0, 24]} onChange={onChange} />
pourquoi la valeur par défaut est gérée ici et pas dans les valeurs par défaut du formulaire ?

2023-10-10 13:30 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/LocationSlider/LocationSlider.tsx
> +  onChange: (nextAroundRadius: number[]) => void
il n'y a qu'une valeur en input, pourquoi il y peut y avoir plusieurs valeurs en output ?

2023-10-10 15:20 UTC, dbenfouzari-pass commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  defaultValue: number[]
Je crois que non, mais il faudrait changer le typage partout 
```ts
type SliderValue = [number] | [number, number]
```

Mais je crois que les nombres négatifs devraient être acceptés (pas pour l'heure ceci dit)

2023-10-10 15:21 UTC, dbenfouzari-pass commented on src/features/search/components/LocationSlider/LocationSlider.tsx
> +  onChange: (nextAroundRadius: number[]) => void
Et éviter les manipulations autour.

2023-10-11 07:50 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +        <Typo.ButtonText>{`${minHour}\u00a0h et ${maxHour}\u00a0h`}</Typo.ButtonText>
Je t'avoue qu'on a pas changé cette partie on a repris le code déjà existant qu'on a placé dans un composant à part. 
Ceci dit je peux demander si on améliore côté design ça sort un peu du cadre du ticket.

2023-10-11 07:50 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +const formatHour = (hour: number) => `${hour}h`
Pareil pour ici https://github.com/pass-culture/pass-culture-app-native/pull/5413#discussion_r1354334052

2023-10-12 08:29 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  defaultValue: number[]
que penses-tu de ce typage ?

```typescript
type Hour = 0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23

type HoursSliderProps = {
  defaultValue: [Hour, Hour]
  onChange: (nextHour: Hour) => void
}

2023-10-12 08:34 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +        minMaxValuesComplement="h"
Je ne sais pas pourquoi le composant a été fait tel quel, mais on utilise bien `formatValues` plus haut avec `formatHour`

2023-10-12 08:41 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +const hoursLabelId = uuidv4()
Je ne pense pas que ce soit le cas je peux retirer l'`uuid` par contre je remarque dans notre code lorsqu'on appelle la props `accessibilityLabelledBy` on la renseigne toujours pas un id qui provient de `uuid`

2023-10-12 09:21 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  defaultValue: number[]
Oui dans l'état c'est valide je vais changer le typage pour qu'on accepte `[number] | [number, number]` mais par contre avoir des valeurs tel que `-5` et `1_024` sont valide... 
faudrait-il qu'on gère que dans le cas du LocationSlider que la value doit être entre `0 et 100` et pour l'HoursSlider que la value doit être entre `0 et 24`

2023-10-12 09:22 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.native.test.tsx
> +      const slider = screen.getByTestId('slider').children[0] as ReactTestInstance
je ne vois pas comment, le `as` nous sert dans le typage du slider

2023-10-12 09:24 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  defaultValue: number[]
je comprendrais entre 0 et 23 ou entre 1 et 24

pourquoi entre 0 et 24 ?

2023-10-12 09:28 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.native.test.tsx
> +      const slider = screen.getByTestId('slider').children[0] as ReactTestInstance
l'`id` est mis sur l'élément parent du `MultiSlider`

est-ce qu'on pourrait mettre un attribut sur le `MultiSlider` afin de le cibler ?

2023-10-12 10:07 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  defaultValue: number[]
Oui plutôt entre 1 et 24, et oui j'aime bien ton typage de Hour je vais remplacer par cela

2023-10-12 10:58 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.stories.tsx
> +  onChange: action('value changed'),
il me semblait que ce n'était pas nécessaire

ça fait quoi si on ne le met pas ?

2023-10-12 10:58 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.stories.tsx
> +)
est-ce qu'il y a un cas dans cette story où on voudrait utiliser le `Template` sans passer par le `WrappedTemplate` ?

2023-10-12 10:58 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +const hoursLabelId = uuidv4()
c'est pas l'`uuid` qui me perturbe, c'est son emplacement

il est hors du composant donc il y aura toujours le meme id pour ce composant

s'il est utilisé plusieurs fois, ça va foutre le zbeul (je peux détailler si ce n'est pas clair)

2023-10-12 10:58 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +        minMaxValuesComplement="h"
> on utilise bien `formatValues` plus haut avec `formatHour`

je n'ai pas l'impression https://github.com/pass-culture/pass-culture-app-native/pull/5413/files#diff-b96747828025682fea8bd49746b773a1b4985cf14659514adaef673106300d45R170

2023-10-12 10:58 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.stories.tsx
> +  },
pourquoi est-il nécessaire de limiter la largeur du slider ?
il se passe quoi on utilise le slider dans un composant qui ne limite pas sa largeur ?

2023-10-12 14:21 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.native.test.tsx
> +      const slider = screen.getByTestId('slider').children[0] as ReactTestInstance
Alors j'ai essayé de mettre un id sur le MultiSlider et on ne peut pas le cibler lorsque je log la debugView il n'apparaît pas du tout...

2023-10-12 14:28 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.native.test.tsx
> +      const slider = screen.getByTestId('slider').children[0] as ReactTestInstance
étonnant

as-tu essayer de getBy quelque chose qui s'affiche à l'écran ?

2023-10-12 14:32 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.stories.tsx
> +)
Effectivement je peux le refacto

2023-10-12 14:37 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.stories.tsx
> +  onChange: action('value changed'),
il me semblait qu'il y avait une action par défaut avec le nom de la propriété comme nom d'action (ça a peut etre changé, ça ne s'applique peut etre pas dans ce cas)

2023-10-12 14:39 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.stories.tsx
> +  },
Le SLider n'a pas de taille, à l'endroit ou il est utilisé la modale de Location ou de Date il prend l'entiereté de la largeur, j'ai rajouté un taille pour que ce soit plus significatif ce qu'on a à l'écran dans storybook si je retire la taille il va prendre toute la largeur de la vue Canvas dans storybook : 
![Capture d’écran 2023-10-12 à 16 39 09](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/a1f6cddd-4834-4c5a-8881-5c21719b1f30)

2023-10-13 14:01 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +        minMaxValuesComplement="h"
Effectivement il n'est pas utilisé dans HoursSlider je le retire car l'affichage des heures est déjà géré dans le composant `Slider`

2023-10-13 14:02 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.native.test.tsx
> +      const slider = screen.getByTestId('slider').children[0] as ReactTestInstance
Oui j'ai essayé je peux récupérer le testID du parent comme c'est déjà fais ou bien je peux récupérer il me semble chaque curseur du Slider mais je n'arrive pas à récupérer le MultiSLider dans sa globalité

2023-10-13 14:09 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.stories.tsx
> +  },
j'ai essayé de toucher à la width pour qu'il prenne toute la largeur du viewport sans succès. Je ne comprend pas trop comment modifier la largeur de se composant fournit par la lib.
Je te propose donc que ce changement visuel se fasse dans un autre ticket car cela sort du scope du ticket qui était une erreur sentry. (je peux créer ce nouveau ticket si besoin)

2023-10-16 10:27 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  | 24
minuit = 0 OU minuit = 24 ?

avoir les deux valeurs me parait bizarre

2023-10-16 10:27 UTC, bruno-ebstein-pass-culture commented on src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx
> +  selectedHours: Range<number>
pourquoi ce n'est pas des `Hour` ?

```suggestion
  selectedHours: Range<Hour>
```

2023-10-16 10:27 UTC, bruno-ebstein-pass-culture commented on src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx
> +const DEFAULT_TIME_VALUE: Range<number> = [0, 24]
est-ce que cette valeur par défaut est la meme que celle-ci ? https://github.com/pass-culture/pass-culture-app-native/pull/5413/files#diff-21caa1cfbaf412eee0cbd0a8a6c06791c6918cf35a95aab0023d0e4b1807b6bbR47

2023-10-16 10:27 UTC, bruno-ebstein-pass-culture commented on src/ui/components/inputs/Slider.tsx
> +      props.onValuesChangeFinish?.(nextValues as ValuesType)
pourrait-on éviter ces `as` ?

2023-10-17 08:09 UTC, YassinL commented on src/ui/components/inputs/Slider.tsx
> +      props.onValuesChangeFinish?.(nextValues as ValuesType)
On ne peut pas vraiment malheureusement la lib qu'on utilise pour le MultiSlider attend un tableau de number comme c'était avant qu'on change le typage de nos composants.

2023-10-17 15:43 UTC, dbenfouzari-pass commented on src/ui/components/inputs/Slider.tsx
> +      props.onValuesChangeFinish?.(nextValues as ValuesType)
En effet la lib `MultiSlider` ne prend pas en compte un réel typage. Pour la lib, c'est `number[]`.
Donc il faut absolument un `as` si on veut que nous au moins, on aie un typage correct. Soit on met le `as` au niveau du callback comme c'est le cas actuellement, soit on remplace notre typage `[number, number]` par `number[]` (ce qui serait faux)

2023-10-17 15:44 UTC, dbenfouzari-pass commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  defaultValue: number[]
Je suis pas d'accord moi. Ca veut dire que tu ne peux pas participer à un évènement à 23h30 ?

2023-10-23 16:15 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +    onChange(newValues as [Hour, Hour])
je propose d'utiliser Yup plutot que `as`

2023-10-23 16:15 UTC, bruno-ebstein-pass-culture commented on src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.ts
> +      ])
ça pourrait etre chouette d'avoir un `hoursSchema`

2023-10-23 16:15 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  | 24
suite au commentaire précédent, on aurait **peut etre** la possibilité de récupérer le type depuis le `hoursSchema` (je ne sais pas comment)

2023-10-23 16:15 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +    onChange(newValues as [Hour, Hour])
il y a d'autres occurrences, mais je vais éviter de spammer le meme message

2023-10-23 16:15 UTC, bruno-ebstein-pass-culture commented on src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx
> +export const DEFAULT_TIME_VALUE: Range<Hour> = [0, 24]
je trouve les deux noms confusants et je ne comprends dans quel cas il faut utiliser l'un plutot que l'autre

2023-10-23 16:15 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  const [internalValue, setInternalValue] = useState<number[]>(defaultValue)
à quoi sert cet état interne ?

2023-10-23 16:15 UTC, bruno-ebstein-pass-culture commented on src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx
>                      )}
si on peut se passer de l'état interne de HoursSlider, on pourrait améliorer comme ça

```suggestion
                    render={HoursSlider}
```

2023-10-23 16:15 UTC, bruno-ebstein-pass-culture commented on src/ui/components/inputs/Slider.tsx
> +      setValues(nextValues as ValuesType)
on devrait pouvoir se passer des `as`

peut etre comme ça

```suggestion
    (nextValues: ValuesType) => {
      props.onValuesChange?.(nextValues)
      setValues(nextValues)
```

sinon en passant par Yup

2023-10-23 16:15 UTC, bruno-ebstein-pass-culture commented on src/ui/components/inputs/Slider.tsx
> +      setValues(nextValues as ValuesType)
il y a plusieurs occurrences de ce problème

2023-11-07 16:47 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +    onChange(newValues as [Hour, Hour])
Je n'ai pas réussis à faire en sorte de retirer les as même avec l'utilisation de Yup

2023-11-07 16:48 UTC, YassinL commented on src/ui/components/inputs/Slider.tsx
> +      setValues(nextValues as ValuesType)
https://github.com/pass-culture/pass-culture-app-native/pull/5413#discussion_r1362352341

2023-11-07 16:53 UTC, YassinL commented on src/features/search/components/HoursSlider/HoursSlider.tsx
> +  | 24
J'ai bien crée un hoursSchema mais cela risque d'être compliqué de réutiliser son type sauf en utilisant un nouveau `as`

2023-11-07 17:05 UTC, YassinL commented
@bruno-ebstein-pass-culture je te propose que le reste puisse se faire dans un prochain ticket, car je ne vois pas trop comment avancé sur le typage qui lié à la lib qu'on utilise. 
Le but de ce ticket était de corriger une erreur sentry, et qui corrige un bug à la fois.

2023-11-07 17:20 UTC, bruno-ebstein-pass-culture commented
@YassinL je suis d'accord, si [on s'occupe réellement du prochain ticket](https://youtu.be/JmghDKkeiik?t=72)

2023-11-16 14:57 UTC, bruno-ebstein-pass-culture commented on src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx
> +      selectedHours: (searchState.timeRange as [Hour, Hour]) ?? DEFAULT_TIME_VALUE,
```suggestion
      selectedHours: dateHoursSchema.isValid(searchState.timeRange) ? searchState.timeRange : DEFFAULT_TIME_VALUE,
```

2023-11-16 15:18 UTC, bruno-ebstein-pass-culture commented on src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.test.ts
> +    it('when value is not a valid hour', async () => {
it.each

2023-11-16 15:18 UTC, bruno-ebstein-pass-culture commented on src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.test.ts
> +        await expect(hourSchema.validate(value)).rejects.toEqual(
validateSync

2023-11-16 15:18 UTC, bruno-ebstein-pass-culture commented on src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.test.ts
> +      const validHours = [0, 1, 12, 23]
ajouter 24

2023-11-16 15:18 UTC, bruno-ebstein-pass-culture commented on src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.test.ts
> +      ]
[0, 24]

2023-11-16 16:56 UTC, YassinL commented on src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.test.ts
> +        await expect(hourSchema.validate(value)).rejects.toEqual(
J'ai pu l'appliquer sur les valeurs qui sont valide par contre lorsqu'elles ne le sont pas, `isValidSync` check les valeurs et me renvoie une erreur `Horaires incorrectes`. C'est embêtant par ce que effectivement elles le sont pas mais le check vient avant de finir le test... du coup j'ai laissé sur les `validate` et `async/await` sur les tests qui devraient m'afficher l'erreur.

2023-11-22 10:27 UTC, bruno-ebstein-pass-culture commented on src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.test.ts
> +  `('hourSchema should fail when value ($value) is not a valid hour', async ({ value }) => {
```suggestion
  it.each([
    25, -1, '8', null, undefined, false,
  ])('hourSchema should fail when value ($1) is not a valid hour', async (value) => {
```

2023-11-22 10:27 UTC, bruno-ebstein-pass-culture commented on src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.test.ts
> +    )
```suggestion
    expect(() => hourSchema.validateSync(value)).toThrow(
      new ValidationError('Horaire incorrecte')
    )
```

2023-11-22 10:27 UTC, bruno-ebstein-pass-culture commented on src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.test.ts
> +    ${[undefined, null]} | ${['8', '12']}
je propose d'ajouter un mélange d'un truc valide avec un truc invalide ; ex: `[2, false]`

et d'ajouter des cas montrant qu'on doit avoir uniquement 2 valeurs ex: `[1]` et `[1, 2, 3]`

2023-11-27 15:25 UTC, bruno-ebstein-pass-culture commented on src/features/search/components/LocationSlider/LocationSlider.native.test.tsx
> +    expect(screen.getByTestId(`value-radius`)).toBeOnTheScreen()
pourquoi est-ce qu'on passe par un testId ? est-ce qu'on pourrait chercher le texte affiché à l'écran à la place ?

2023-11-27 15:28 UTC, YassinL commented on src/features/search/components/LocationSlider/LocationSlider.native.test.tsx
> +    expect(screen.getByTestId(`value-radius`)).toBeOnTheScreen()
J'ai essayé dans un premier temps de récupérer par le texte mais dans ce cas là on a deux fois le même texte sur la page (100 km), du coup c'est la seule solution que j'ai trouvé pour récupérer cette valeur

2023-11-27 16:08 UTC, merged