(PC-24948) feat(Headers): harmonisation
pass-culture/pass-culture-app-native pull request #5537
Opened 2023-11-02 13:23 UTC by NolwenMajorFrances

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24948

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** _if no UI change_

| Platform         | Mockup/Before | After |
| :--------------- | :-----------: | :---: |
| iOS              |               |       |
| Android          |               |       |
| Phone - Chrome   |               |       |
| Desktop - Chrome |               |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-11-02 16:04 UTC, pierrecanthelou requested changes
Juste une correction et quelques question :)

2023-11-02 16:04 UTC, pierrecanthelou commented on src/features/search/components/SearchCustomModalHeader.tsx
> +  titleId,
[proposition] est-ce que ça se fait de mettre des params par défaut aux valeurs optionnelles ?

2023-11-02 16:04 UTC, pierrecanthelou commented on src/features/search/components/SearchCustomModalHeader.tsx
> +      <View style={{ height: HEIGHT_CONTAINER + top }} />
Attention style inline

2023-11-02 16:04 UTC, pierrecanthelou commented on src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
> +      isUpToStatusBar
[question] C'est quoi isUpToStatusBar ?

2023-11-02 16:32 UTC, NolwenMajorFrances commented on src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
> +      isUpToStatusBar
c'est en opposition au paramètre full screen. ca fait des modales qui vont pas jusqu'en haut ( ce que m'a demandé Agathe )

2023-11-02 16:32 UTC, NolwenMajorFrances commented on src/features/search/components/SearchCustomModalHeader.tsx
> +      <View style={{ height: HEIGHT_CONTAINER + top }} />
yep, j'ai bêtement copié comment etait fait l'appmodal, je vais modifier cela

2023-11-02 16:44 UTC, NolwenMajorFrances commented on src/features/search/components/SearchCustomModalHeader.tsx
> +      <View style={{ height: HEIGHT_CONTAINER + top }} />
en fait ça permettait je ne sais pas trop comment d"éviter une erreur de typage puisque HEIGHTCONTAINER est un number alors que top est de type Window ou null donc ne devraient pas être additionnables

2023-11-02 17:11 UTC, NolwenMajorFrances commented on src/features/search/components/SearchCustomModalHeader.tsx
> +      <View style={{ height: HEIGHT_CONTAINER + top }} />
finalement, difficilement modifiable : la variable 'top' utilise un hook qui ne peut pas être appelé en dehors d'une fonction composant. Hors si elle est initialisée dans cette fonction, elle n'est pas accessible en dehors de la fonction pour pouvoir créer un composant de Style à l'exterieur.

2023-11-02 17:33 UTC, pierrecanthelou reviewed
Retour sur le 'style'

2023-11-02 17:33 UTC, pierrecanthelou commented on src/features/search/components/SearchCustomModalHeader.tsx
> +      <View style={{ height: HEIGHT_CONTAINER + top }} />
Est-il possible de sortir le style dans un componentstyle ?

2023-11-06 15:32 UTC, pierrecanthelou reviewed
Une seule remarque, on imbrique pas les créations de composants :)
Je laisse à Tanguy le soin de valider le reste ?

2023-11-06 15:32 UTC, pierrecanthelou commented on src/features/search/components/SearchCustomModalHeader.tsx
> +  let HeaderHeight = styled.View({ height: HEIGHT_CONTAINER })
Il faut définir ce composant hors de SearchCustomModalHeader. Ce n'est pas une bonne pratique de définir un composant au sein de la définition d'un autre composant.

2023-11-06 15:32 UTC, pierrecanthelou commented on src/features/search/components/SearchCustomModalHeader.tsx
> +  let HeaderHeight = styled.View({ height: HEIGHT_CONTAINER })
[suggestion]
`let HeaderHeight = styled.View({ height: HEIGHT_CONTAINER + isDesktopViewport * top })`
`let HeaderHeight = styled.View({ height: HEIGHT_CONTAINER + isDesktopViewport ? top : 0 })`

2023-11-06 15:32 UTC, pierrecanthelou commented on src/features/search/components/SearchCustomModalHeader.tsx
> +              {!!shouldDisplayCloseButton && (
[question] Pourquoi ne pas inclure `ButtonContainer` dans `{!!shouldDisplayCloseButton && (` ?

2023-11-06 16:29 UTC, NolwenMajorFrances commented on src/features/search/components/SearchCustomModalHeader.tsx
> +  let HeaderHeight = styled.View({ height: HEIGHT_CONTAINER })
mais j'ai besoin du hook useCustomSafeInsets ( qui doit être dans mon SearchCustomHeader) pour éditer mon composant HeaderHeight, du coup je vois pas d'autre solution qu'inliner comme c'était fait dans AppModale.

2023-11-07 15:40 UTC, pierrecanthelou approved these changes
Nice

2023-11-08 14:17 UTC, tanguyprache commented on src/features/search/components/SearchCustomModalHeader.tsx
> +  testID,
Pourquoi tu ajoutes le testId en props ? C'est toujours "pageHeader" au niveau du `SearchCustomModalHeader` non ?

2023-11-08 15:44 UTC, merged