(PC-25469) feat(offer): add tags component
pass-culture/pass-culture-app-native pull request #5563
Opened 2023-11-08 08:26 UTC by cedricls1

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25469

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** _if no UI change_

| Platform         | Mockup/Before | After |
| :--------------- | :-----------: | :---: |
| iOS              |               |       |
| Android          |               |       |
| Phone - Chrome   |               |       |
| Desktop - Chrome |               |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-11-08 08:51 UTC, cedricls1 commented on src/features/search/components/SearchHeader/SearchHeader.web.test.tsx
> +jest.spyOn(useFeatureFlagAPI, 'useFeatureFlag').mockReturnValue(false)
ça n'a rien à voir avec ma PR mais vu que ça casse `master`et que c'est pas grand chose je l'ai inclus

2023-11-08 10:11 UTC, YassinL approved these changes
LGTM

2023-11-08 13:57 UTC, dbenfouzari-pass requested changes

2023-11-08 13:57 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +export function OfferTags({ tags }: Readonly<Props>) {
Est-ce que tu peux ajouter un commentaire pour préciser à quoi sert ce composant ?
Dire qu'on comprenne pourquoi utiliser celui-ci et pas créer simplement un wrapper.

2023-11-08 13:57 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const maxContainerHeight = tagHeight * TAGS_LINES + MARGIN_BOTTOM_TAGS
C'est cool mais ta formule est fausse. Elle fonctionne avec 2 lignes, mais si tu en affichais 3 tu aurais un problème de taille. Je te propose d'ailleurs de créer une story qui le démontre.

2023-11-08 13:57 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const tagRef = useRef<View>(null)
Tu peux écrire un commentaire qui indique que ce n'est utilise que pour calculer dynamiquement la hauteur d'un tag, et qu'on ne l'utilise d'ailleurs que sur le premier tag render pour éviter les computings inutiles ?

2023-11-08 13:57 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +})
Tu te sers du `TagContainer` pour rajouter une marge en bas de chaque tag mais tu ajoutes une marge à droite de chaque tag grâce aux `StyledTag`. C'est bizarre, il faudrait mettre les 2 marges sur un seul composant.

Je te propose de ne le faire que sur `StyledTag` et de supprimer `TagContainer` et tout wrapper du tag.

2023-11-08 13:57 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.native.test.tsx
> +})
C'est vachement léger. Est-ce que tu peux créer un test qui démontre que `OfferTags` ne fait bien que X pixels de hauteur ?

2023-11-08 13:57 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +const TAGS_LINES = 2
Est-ce que tu n'en ferais pas une prop ? Qui serait par défaut à `2` mais qu'on peut augmenter ou réduire au besoin ? Ca ne doit pas être compliqué à faire et ça apporte de la flexibilité pour l'avenir.

2023-11-08 13:57 UTC, dbenfouzari-pass commented on src/features/offer/helpers/getOfferTags/getOfferTags.ts
> +}
```suggestion

export function getOfferTags(subcategoryLabel: string, extraData?: OfferExtraData) {
  const tags: string[] = [subcategoryLabel]

  const maybePushTag = (tag: string | null | undefined) => {
    if (tag) tags.push(tag)
  }

  maybePushTag(extraData?.musicType)
  maybePushTag(extraData?.musicSubType)
  maybePushTag(extraData?.showType)
  maybePushTag(extraData?.showSubType)

  return tags
}
```

Je te propose ça : plus simple, plus flat, et pas besoin d'autant de conditions.

En poussant un peu, on peut même faire mieux

```suggestion
export function getOfferTags(subcategoryLabel: string, extraData?: OfferExtraData) {
  return [
    subcategoryLabel,
    extraData?.musicType,
    extraData?.musicSubType,
    extraData?.showType,
    extraData?.showSubType,
  ].filter(Boolean)
}
```

Et là tu enlèves toute la complexité inutile.

2023-11-08 13:57 UTC, dbenfouzari-pass commented on src/features/offer/helpers/getOfferTags/getOfferTags.ts
> +import { OfferExtraData } from 'api/gen'
Initialement j'imaginais que `getOfferTags` (comme son nom l'indique) prenait en argument une `offer` et sortait des `tags`.

Si demain tu devais afficher des tags venus d'ailleurs tu devrait modifier le composant qui appelle `getOfferTags` et non directement `getOfferTags`. C'est un problème d'après moi.

2023-11-08 14:06 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState<number>(0)
J'avais oublié :
```suggestion
  const [tagHeight, setTagHeight] = useState(0)
```
autant laisser TypeScript faire ce qu'il sait faire :D

2023-11-08 14:10 UTC, cedricls1 commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +})
Alors j'ai essayé mais la ref ne fonctionne pas si j'utilise que `Tag`, j'ai aussi essayé `forwardRef` sans succès.
Du coup si t'as une idée, je suis preneur sinon je passe tout le style sur le container.

2023-11-08 14:15 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +})
Normalement `forwardRef` devrait fonctionner. On peut regarder ensemble si besoin.

2023-11-08 14:17 UTC, cedricls1 commented on src/features/offer/helpers/getOfferTags/getOfferTags.ts
> +import { OfferExtraData } from 'api/gen'
Alors le problème si on passe l'offre complète ici (ce que j'avais fait à la base) c'est que l'on a besoin du mapping des sous-catégories en paramètre supplémentaire pour aller chercher le libellé correspondant à l'enum.

2023-11-08 14:20 UTC, cedricls1 commented on src/features/offer/helpers/getOfferTags/getOfferTags.ts
> +}
J'aime bien la 2ème proposition

2023-11-08 14:26 UTC, dbenfouzari-pass commented on src/features/offer/helpers/getOfferTags/getOfferTags.ts
> +import { OfferExtraData } from 'api/gen'
Hm, tu as raison. C'est emmerdant... Ok alors, je peux resolve ce point

2023-11-08 14:27 UTC, dbenfouzari-pass commented on src/features/offer/helpers/getOfferTags/getOfferTags.ts
> +}
Il va peut-être falloir que tu overrides le typage qui ne va pas comprendre et dire `<string | undefined>[]`

2023-11-08 16:27 UTC, cedricls1 commented on src/features/offer/helpers/getOfferTags/getOfferTags.ts
> +  ].filter(Boolean) as string[]
Je n'ai pas eu le choix que de rajoute le `as string[]` parce que les données de l'API sont `string | null | undefined` sinon j'avais une erreur de typing

2023-11-09 15:52 UTC, cedricls1 commented on src/features/offer/helpers/getOfferTags/getOfferTags.test.ts
> +  })
Je ne comprends pas bien où tu veux en venir. Tu imagines comment les tests ?
Pour ta question on aurait `'une valeur'` mais vu que ça dépend du mapping des sous-catégories logiquement pas possible. Tu passerais le mapping directement dans la fonction ? Et `uneNouvelleExtraData` on l'aurait que si on l'ajoute aux extraData qu'on traite donc là elle ne ressortirait pas.

2023-11-09 15:53 UTC, cedricls1 commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
Du design ^^, je ne vois pas où tu veux en venir ?

2023-11-09 16:02 UTC, bruno-ebstein-pass-culture commented on src/features/offer/helpers/getOfferTags/getOfferTags.test.ts
> +  })
ma question (mal formulée) c'est : 
comment voudrait-on gérer les nouvelles `extraData` dans les tags ?
est-ce que voudrait afficher tout les `extraData` ?

si oui, peut etre qu'on pourrait rendre l'implem plus générique

si non, j'aimerais bien qu'on ajoute un test avec une `extraData` inconnue qui serait ignorée

2023-11-09 16:04 UTC, bruno-ebstein-pass-culture commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
on ajoute de la complexité qui sera exécutée au runtime pour calculer la hauteur d'un tag

de ce que j'en comprends, la hauteur d'un tag dépend d'aucune donnée dynamique et seulement du design

a-t-on vraiment besoin d'ajouter cette complexité ?

2023-11-09 16:10 UTC, cedricls1 commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
Ah yes je vois où tu veux en venir, effectivement on pourrait avoir une constante avec la taille souhaitée du tag mais l'idée c'était de ne pas forcément revenir sur ce composant si la hauteur du tag venait à changer mais c'est peut être too much.
J'appelle @dbenfouzari ici :)

2023-11-09 16:17 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
En effet ça ajoute "un peu" de complexité et de calcul.
Dans ce cas, pour que ce soit OK, il faudrait :
- exporter la `lineHeight`
- exporter le `padding` d'un tag

De cette façon tu peux deviner que `tagHeight = lineHeight + padding * 2`

2023-11-09 16:19 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
On ne peut pas juste se dire qu'on sait aujourd'hui qu'un tag fait 24px de hauteur et se baser sur cette info qui sera peut-être erronée demain. Si on peut s'éviter de la dette à venir c'est pas mal :)

2023-11-09 16:23 UTC, cedricls1 commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
A choisir j'aimerai autant le garder comme ça, c'est bien expliqué et je ne pense pas que ça explose les perf

2023-11-09 16:26 UTC, bruno-ebstein-pass-culture commented on src/features/offer/helpers/getOfferTags/getOfferTags.test.ts
> +  })
je n'ai pas d'avis sur l'enum

2023-11-09 16:28 UTC, dbenfouzari-pass commented on src/features/offer/helpers/getOfferTags/getOfferTags.ts
> +  ].filter(Boolean) as string[]
Je suis curieux de faire partie de la boucle @cedricls1

2023-11-09 16:29 UTC, bruno-ebstein-pass-culture commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
j'aurais aimé avoir une constante `TAG_HEIGHT` exportée depuis le fichier qui contient le composant `Tag`

je trouve la solution trop complexe par rapport au besoin

je vous laisse choisir

2023-11-09 16:31 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
Oui mais `TAG_HEIGHT=24` est vrai aujourd'hui mais on crée une fausse source de donnée ?
Je ne comprends pas pourquoi tu préfèrerais ça à un calcul qui lui retournerait toujours la vraie donnée (que ce soit le compute du `tagHeight` ou alors un mélange de constantes) ?

2023-11-09 16:47 UTC, bruno-ebstein-pass-culture commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
parce que c'est moins complexe, donc plus facile à maintenir et moins source potentielle de bugs

si dans le fichier `Tag`, on a un truc du genre :

```ts
const PADDING_VERTICAL = getSpacing(1)

const Wrapper = styled(View)(({ theme }) => ({
  borderRadius: 6,
  backgroundColor: theme.colors.greyLight,
  paddingVertical: PADDING_VERTICAL,
  paddingHorizontal: getSpacing(2),
  alignSelf: 'baseline',
}))

const LINE_HEIGHT = getSpacing(4)

const LabelText = styled(Typo.Caption)(({ theme }) => ({
  color: theme.colors.black,
  lineHeight: LINE_HEIGHT,
}))

export const TAG_HEIGHT = PADDING_VERTICAL + LINE_HEIGHT + PADDING_VERTICAL
```

ça devrait etre facile à maintenir

2023-11-09 16:48 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
Ah mais dans ce cas c'est ce que je proposais https://github.com/pass-culture/pass-culture-app-native/pull/5563#discussion_r1388240479
Ca me va ça

2023-11-13 08:35 UTC, cedricls1 commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const [tagHeight, setTagHeight] = useState(0)
Ok je vais update

2023-11-13 08:42 UTC, cedricls1 commented on src/features/offer/helpers/getOfferTags/getOfferTags.test.ts
> +  })
ça marche, dans ce cas je laisse comme ça

2023-11-13 08:59 UTC, cedricls1 commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +})
Plus de besoin avec l'utilisation du tag height vu [ici](https://github.com/pass-culture/pass-culture-app-native/pull/5563#discussion_r1388280075)

2023-11-13 09:42 UTC, bruno-ebstein-pass-culture approved these changes

2023-11-13 09:42 UTC, bruno-ebstein-pass-culture commented on src/features/offer/components/OfferTags/OfferTags.native.test.tsx
> +      maxHeight: (TAG_HEIGHT + MARGIN_BOTTOM_TAGS) * tagsLines,
la vérification me parait trop proche de l'implem, je préfèrerais voir la valeur réelle

```suggestion
      maxHeight: 42,
```

ça fait probablement pas 42, j'ai pas compté, mais tu as l'idée

2023-11-13 10:32 UTC, cedricls1 commented on src/features/offer/components/OfferTags/OfferTags.native.test.tsx
> +})
Finalement en changeant la logique, j'ai réussi à faire le test

2023-11-13 13:27 UTC, dbenfouzari-pass commented on src/features/offer/components/OfferTags/OfferTags.tsx
> +  const maxContainerHeight = (TAG_HEIGHT + MARGIN_BOTTOM_TAGS) * tagsLines
Hm... Je ne pense pas que ton calcul soit bon.
Je pense qu'il doit être 
```suggestion
  const maxContainerHeight = (TAG_HEIGHT * tagsLines) + (MARGIN_BOTTOM_TAGS * (tagsLines - 1))
```

Si on admet que `TAG_HEIGHT = 24` et que `MARGIN_BOTTOM_TAGS = 4` alors on peut convertir :
- si `tagsLines = 0`, alors `maxContainerHeight = 0` (ça n'arrivera jamais)
- si `tagsLines = 1`, alors `maxContainerHeight = 24 (TAG_HEIGHT * 1 /* 24 */ + (MARGIN_BOTTOM_TAGS * 0 /* 0 */)`
- si `tagsLines = 2`, alors `maxContainerHeight = 52 (TAG_HEIGHT * 2 /* 48 */ + (MARGIN_BOTTOM_TAGS * 1 /* 4 */)`
- ...

De cette façon tu ne crées pas de marge qui ne dois pas exister et qui pourrait créer des glitches. Tu pourrais en créer une fonction que tu testes pour t'en assurer peut-être ?

2023-11-13 14:05 UTC, dbenfouzari-pass approved these changes

2023-11-14 09:15 UTC, dbenfouzari-pass approved these changes

2023-11-14 09:40 UTC, bruno-ebstein-pass-culture approved these changes

2023-11-14 09:40 UTC, bruno-ebstein-pass-culture commented on src/features/offer/helpers/getOfferTags/getOfferTags.ts
> +function filterByString(value: string | null | undefined): value is string {
👏

2023-11-14 10:12 UTC, bruno-ebstein-pass-culture commented on scripts/dead_code_snapshot.txt
> +src/features/offer/components/OfferTags/OfferTags.tsx:12 - MARGIN_BOTTOM_TAGS (used in module)
pourquoi ajoutons cette ligne ?

2023-11-14 10:15 UTC, cedricls1 commented on scripts/dead_code_snapshot.txt
> +src/features/offer/components/OfferTags/OfferTags.tsx:12 - MARGIN_BOTTOM_TAGS (used in module)
Yes en regardant de plus près, l'export est inutile, je rectifie (à la base j'utilisais la variable dans le fichier de test)

2023-11-14 11:05 UTC, merged