(PC-26238) Refactor(LocationWrapper): refacto geolocation lib
pass-culture/pass-culture-app-native pull request #5702
Opened 2023-12-15 10:13 UTC by TristanMaurier98

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXXXX

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** _if no UI change_

| Platform         | Mockup/Before | After |
| :--------------- | :-----------: | :---: |
| iOS              |               |       |
| Android          |               |       |
| Phone - Chrome   |               |       |
| Desktop - Chrome |               |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2023-12-15 14:02 UTC, Lucasbeneston commented
> ## [![Quality Gate Passed](https://camo.githubusercontent.com/ccc33529577e0665e83694096acf06d898d9ea073282df17959b2a9d67290051/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d7061737365642d323070782e706e67)](https://sonarcloud.io/dashboard?id=pass-culture_pass-culture-app-native&pullRequest=5702) **Quality Gate passed**
> The SonarCloud Quality Gate passed, but some issues were introduced.
> 
> [11 New issues](https://sonarcloud.io/project/issues?id=pass-culture_pass-culture-app-native&pullRequest=5702&resolved=false&inNewCodePeriod=true) [3 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=pass-culture_pass-culture-app-native&pullRequest=5702&resolved=false&inNewCodePeriod=true) [88.2% Coverage on New Code](https://sonarcloud.io/component_measures?id=pass-culture_pass-culture-app-native&pullRequest=5702&metric=new_coverage&view=list) [0.2% Duplication on New Code](https://sonarcloud.io/component_measures?id=pass-culture_pass-culture-app-native&pullRequest=5702&metric=new_duplicated_lines_density&view=list)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=pass-culture_pass-culture-app-native&pullRequest=5702)

Je n'ai pas le temps de relire cette PR mais attention au 11 code smells ! 🫠
Je viens de faire une modification pour que la CI soit rouge dès qu'il y a un code smell, parce que la c'est pas visible du tout 😪

2023-12-18 08:08 UTC, pierrecanthelou requested changes
Les fichiers sont longs, je crois que ce serait un avantage pour le lecteur que soient expliqués les actions des "refacto" plutôt qu'il ait a les deviner comme ça cela accélérerait la lecture en sachant quoi regarder.
Il y a les sonars à reprendre donc j'appuie sur Request changes

2023-12-18 15:46 UTC, pierrecanthelou approved these changes

2023-12-18 15:46 UTC, pierrecanthelou commented
@tanguyprache @TristanMaurier98 @NolwenMajorFrances FYI validate

2023-12-18 16:06 UTC, merged