(PC-26023) feat(Offer): free digital events are bookable instead of d…
pass-culture/pass-culture-app-native pull request #6421
Opened 2024-05-16 10:29 UTC by NolwenMajorFrances

…irectly redirected to zoom

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26023

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** _if no UI change_

| Platform         | Mockup/Before | After |
| :--------------- | :-----------: | :---: |
| iOS              |               |       |
| Android          |               |       |
| Phone - Chrome   |               |       |
| Desktop - Chrome |               |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2024-05-17 08:06 UTC, inesmouandjolobe commented
@NolwenMajorFrances il m'avait semblé sur ce ticket qu'il fallait arriver directement sur la modale de confirmation ?

2024-05-17 08:16 UTC, inesmouandjolobe requested changes
Il m'avait semblé que sur ce ticket on voulait afficher directement la modale de réservation au clic sur réserver l'offre et donc skip la modale calendrier ?

2024-05-20 07:31 UTC, NolwenMajorFrances commented
@inesmouandjolobe mais si y a plusieurs dates proposées pour l'event, faut bien pouvoir choisir à un moment non ? Je redemande à Clément !

2024-05-22 11:35 UTC, inesmouandjolobe approved these changes

2024-05-22 14:43 UTC, merged