(PC-29756) feat(VenueListModule): add new venue list module app V2
pass-culture/pass-culture-app-native pull request #6436
Opened 2024-05-20 14:17 UTC by YassinL

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29756

## Checklist

I have:

- [ ] Made sure my feature is working on the relevant real / virtual devices (native and web).
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** _if no UI change_

| Platform         | Mockup/Before | After |
| :--------------- | :-----------: | :---: |
| iOS              |               |       |
| Android          |               |       |
| Phone - Chrome   |               |       |
| Desktop - Chrome |               |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a

2024-05-20 14:36 UTC, pierrecanthelou requested changes
Quelques questions d'optimisation.
Ce serait intéressant d'avoir quelques calculs de rendus via why-did-you-render ou reassure ;)

2024-05-20 14:36 UTC, pierrecanthelou commented on src/ui/theme/colors.ts
> -  GOLD = '#B85901',
Si le composant est à jeter est-ce que changer les valeurs Gold et Gold_light existantes est un soucis ?

2024-05-20 14:36 UTC, pierrecanthelou commented on src/features/home/components/modules/VenueListModule.tsx
> +    <StyledTouchableHeader navigateTo={{ screen: 'VenueMap' }}>
Que faire pour éviter le fragment et le spacer ?

2024-05-20 14:36 UTC, pierrecanthelou commented on src/features/home/components/modules/VenueListModule.tsx
> +      ItemSeparatorComponent={() => (
Est-ce qu'on peut améliorer ça ?

2024-05-20 15:05 UTC, YassinL commented on src/features/home/components/modules/VenueListModule.tsx
> +      ItemSeparatorComponent={() => (
[2caaf37](https://github.com/pass-culture/pass-culture-app-native/pull/6436/commits/2caaf376f47c10a3f113d9e9e0f832cdb890b221)

2024-05-20 15:15 UTC, YassinL commented on src/ui/theme/colors.ts
> -  GOLD = '#B85901',
Ce n'est pas un soucis comme c'est un variant de couleur qui existe côté design on a juste réapproprier correctement le nom des couleurs

2024-05-20 15:17 UTC, YassinL commented on src/features/home/components/modules/VenueListModule.tsx
> +    <StyledTouchableHeader navigateTo={{ screen: 'VenueMap' }}>
Dans ce cas on peut mettre une View à la place avec un marginBottom si on préfère cette solution ? ça me très bien aussi

2024-05-20 15:52 UTC, pierrecanthelou approved these changes

2024-05-21 08:56 UTC, cedricls1 approved these changes

2024-05-21 09:36 UTC, merged