(PC-29881) feat(a11yFooter): Added to Home and Profile
pass-culture/pass-culture-app-native pull request #6647
Opened 2024-07-05 15:05 UTC by vikingprank

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29881

## Flakiness

If I had to re-run tests in the CI due to flakiness, I add the incident [on Notion][2]

## Checklist

I have:

- [ ] Made sure my feature is working on web.
- [ ] Made sure my feature is working on mobile (depending on relevance : real or virtual devices)
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** _if no UI change_

| Platform         | Mockup/Before | After |
| :--------------- | :-----------: | :---: |
| iOS              |               |       |
| Android          |               |       |
| Phone - Chrome   |               |       |
| Desktop - Chrome |               |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25bb04cfee&pvs=4

2024-07-08 08:42 UTC, Lucasbeneston commented on src/features/navigation/RootNavigator/Header/Header.web.tsx
> +      <QuickAccess href={`#${FOOTER_ID}`} title="Aller au footer" />
```suggestion
      <QuickAccess href={`#${FOOTER_ID}`} title="Aller au pied de page" />
```

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.tsx
> +            )}
C'est voulu d'avoir la redirection que en desktop ?

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.tsx
> +})
Commentaire / changement oublié ?

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.tsx
> +export default AccessibilityFooter
Pas d'export default

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.tsx
> +const AccessibilityFooter = () => {
```suggestion
export const AccessibilityFooter = () => {
```

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +jest.mock('libs/firebase/analytics/analytics')
Commentaire ou mock à supprimer ?

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
```suggestion
    expect(openUrl).toHaveBeenCalledWith('https://passculture.app/accueil')
  })
```

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
```suggestion
    expect(openUrl).toHaveBeenCalledWith('https://passculture.cgu')
  })
```

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  it('should go to web app when "pass Culture" link is pressed (only web mobile)', () => {
Peut-être qu'avec la condition en moins il faudra changer ce test

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
```suggestion
    expect(openUrl).toHaveBeenCalledWith('https://passculture.data-privacy-chart')
  })
```

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
```suggestion
    expect(navigate).toHaveBeenCalledWith('Accessibility')
  })
```

2024-07-08 08:42 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
```suggestion
    expect(navigate).toHaveBeenCalledWith('LegalNotices')
  })
```

2024-07-08 08:42 UTC, Lucasbeneston commented on src/ui/theme/constants.ts
> +export const FOOTER_ID = 'footer_id_for_quick_access'
Je pense que ce n'est pas la bonne place, dans ce fichier ce sont surtout des valeurs numériques. Peut-être l'exporter depuis AccessibilityFooter ?

2024-07-08 08:44 UTC, Lucasbeneston commented on src/features/navigation/RootNavigator/RootNavigator.tsx
> +}
Je me demande si ça serait pas plus propre d'extraire cette fonction ?

2024-07-08 09:16 UTC, vikingprank commented on src/shared/AccessibilityFooter/AccessibilityFooter.tsx
> +            )}
Sur la maquette le lien "pass culture" n'est affiché qu'en flex direction row, du coup je l'ai caché en web mobile, qu'en penses tu?

2024-07-08 09:25 UTC, vikingprank commented on src/shared/AccessibilityFooter/AccessibilityFooter.tsx
> +const AccessibilityFooter = () => {
Je vire le export default AccessibilityFooter du coup?

2024-07-08 09:25 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.tsx
> +            )}
J'ai pas compris désolé :D

2024-07-08 09:26 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.tsx
> +const AccessibilityFooter = () => {
Yes ! 👍

2024-07-08 09:29 UTC, vikingprank commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
Le test fail si je retire le undefined :(

2024-07-08 09:29 UTC, vikingprank commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
Le test fail si je retire le undefined :(

2024-07-08 09:30 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
Ça marche !

2024-07-08 09:31 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
Ça marche !

2024-07-08 09:31 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +  })
Ça marche !

2024-07-08 13:21 UTC, Lucasbeneston commented on src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx
> +jest.mock('libs/firebase/analytics/analytics')
@vikingprank

2024-07-08 14:07 UTC, Lucasbeneston approved these changes

2024-07-09 07:21 UTC, aliraiki requested changes
- J'ai pas de `main` quand je vais sur la home
- Sur le profile, le main ne contient qu'une partie de la page : 
<img width="896" alt="Capture d’écran 2024-07-09 à 09 21 26" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/846fd553-aaa6-40d5-ad74-d13a661ea7c7">

2024-07-09 07:21 UTC, aliraiki commented on src/features/home/pages/GenericHome.tsx
> +      </AccessibilityFooterContainer>
Est-ce qu'on ne veut pas afficher le footer que dans le cas où toutes les playlists ont été affichées (`hasShownAll`) ?

2024-07-09 07:21 UTC, aliraiki commented on src/features/navigation/RootNavigator/determineAccessibilityRole.ts
> +    // this might create issues when entering the app from other places then home
T'es sûr de ça ? J'arrive pas à reproduire perso (en tout cas sur la Home et le Profile j'ai direct le paramètre screen)

2024-07-09 07:21 UTC, aliraiki commented on src/features/navigation/RootNavigator/determineAccessibilityRole.ts
> +      (currentRouteParams?.screen as ScreenNames) === undefined)
```suggestion
    currentRouteParams &&
    'screen' in currentRouteParams &&
    (pageWithFooter.includes(currentRouteParams?.screen as ScreenNames) ||
      (currentRouteParams?.screen as ScreenNames) === undefined)
```

2024-07-09 07:21 UTC, aliraiki commented on src/features/navigation/RootNavigator/determineAccessibilityRole.ts
> +      (currentRouteParams?.screen as ScreenNames) === undefined)
Tu peux extraire cette condition dans une variable, et utiliser cette variable pour définir `mainAccessibilityRole`. Ca permet d'utiliser `const` au lieu de `let` : 
```
const mainAccessibilityRole = myVariable ? undefined : AccessibilityRole.MAIN
```

2024-07-09 13:23 UTC, vikingprank commented on src/features/navigation/RootNavigator/determineAccessibilityRole.ts
> +    // this might create issues when entering the app from other places then home
Pour moi, currentRoute?.params est undefined quand j'arrive sur l'app

2024-07-10 07:49 UTC, aliraiki requested changes
Si jamais si je vais sur la home, puis sur le profile, puis sur la home, et que j'inspecte le code, je me retrouve avec plusieurs `main`, il ne faut en avoir qu'un seul.
C'est parce qu'on "push" le html de la page à chaque fois qu'on navigue en utilisant la navbar.
Ce comportement a été mis en place il y a longtemps par la squad Recherche pour avoir une cohérence de navigation mais je ne sais pas si c'est encore nécessaire. Vous pouvez peut-être voir avec Bruno pour trouver une solution, je reste disponible si besoin ofc.

2024-07-10 07:49 UTC, aliraiki commented on src/features/navigation/RootNavigator/determineAccessibilityRole.ts
> +  // this might create issues when entering the app from other places then home
Peut-être bouger le commentaire au dessus de la condition

2024-07-23 13:56 UTC, vikingprank commented
> Si jamais si je vais sur la home, puis sur le profile, puis sur la home, et que j'inspecte le code, je me retrouve avec plusieurs `main`, il ne faut en avoir qu'un seul. C'est parce qu'on "push" le html de la page à chaque fois qu'on navigue en utilisant la navbar. Ce comportement a été mis en place il y a longtemps par la squad Recherche pour avoir une cohérence de navigation mais je ne sais pas si c'est encore nécessaire. Vous pouvez peut-être voir avec Bruno pour trouver une solution, je reste disponible si besoin ofc.

Suite au point DINUM (voir [notes ici](https://www.notion.so/passcultureapp/Suivi-accessibilit-dc824d767c41487b88b539c6899a2f95)), nous allons retenir la solution d’avoir plusieurs balises avec l’accessibilityRole main. Cela ne serait pas un problème à partir du moment qu'il n'y ai qu'une d'entre elles avec display: flex (alors que les autres seront display: none et ne gênerait pas les lecteurs d'écran).

2024-07-23 14:27 UTC, vikingprank commented on src/features/home/pages/GenericHome.tsx
> +          <AccessibilityFooterContainer>
Si l'utilisateur veut accder au footer par le quick access, peut-il le faire s'il n'est pas encore render?

2024-07-25 08:26 UTC, vikingprank commented on src/features/home/pages/GenericHome.tsx
> +          <AccessibilityFooterContainer>
Corrigé dans le dernier commit

2024-07-25 09:33 UTC, merged