(PC-31871) feat(XpCine): display cinema
pass-culture/pass-culture-app-native pull request #6978
Opened 2024-10-08 09:44 UTC by xlecunff-pass

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31871

## Flakiness

If I had to re-run tests in the CI due to flakiness, I add the incident [on Notion][2]

## Checklist

I have:

- [ ] Made sure my feature is working on web.
- [ ] Made sure my feature is working on mobile (depending on relevance : real or virtual devices)
- [ ] Written **unit tests** native (and web when implementation is different) for my feature.
- [ ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [ ] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]

## Screenshots

**delete** _if no UI change_

| Platform         | Mockup/Before | After |
| :--------------- | :-----------: | :---: |
| iOS              |               |       |
| Android          |               |       |
| Phone - Chrome   |               |       |
| Desktop - Chrome |               |       |

[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d0a
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25bb04cfee&pvs=4

2024-10-09 16:06 UTC, tanguyprache commented on src/tests/utils.tsx
> +export const mockFunction = <
Est-ce que c'est encore utile suite au retour de Bruno ?

2024-10-10 09:37 UTC, NolwenMajorFrances commented on src/features/offer/components/OfferNewXPCine/OfferNewXPCineBlock.tsx
> +        {isEnd ? null : (
pourquoi malgré une position à la boétie avec un rayon 50 je peux avoir des offres ciné super populaires avec seulement trois cinémas autour de moi ? J’ai l’impression que le rayon n’est plus pris en compte dans la sélection des cinémas, non ?

2024-10-10 12:40 UTC, tanguyprache commented on src/features/offer/helpers/useOfferSubcategory/useOfferSubcategory.ts
> +export const useOfferSubcategory = (offer: OfferResponseV2) => {
Possible de rajouter un test sur ce petit hook ?

2024-10-10 12:48 UTC, tanguyprache commented on src/features/offer/components/OfferNewXPCine/OfferNewXPCineBlock.tsx
> +        {isLoading ? <CineBlockSkeleton /> : null}
Pareil ici, on peut ajouter des tests sur le comportement de l'affichage

2024-10-11 08:09 UTC, NolwenMajorFrances requested changes

2024-10-11 08:09 UTC, NolwenMajorFrances commented on src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.ts
> +  radiusKm: number
je. pense que ce serait plus efficace de récupérer le radius depuis useLocation juste en dessous, non ? Et je suis pas chaude du radiusKm :distanceKm car ça ne veut pas dire la même chose radius et distance.

2024-10-11 08:19 UTC, xlecunff-pass commented on src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.ts
> +  radiusKm: number
Le radius est un paramètre à passer et non configurable depuis l'app de base, le radius était de 100km dans le ticket et on avait convenu hier à 50.
Je fais la modif pour radiusKm :distanceKm, un oubli au renaming, merci

2024-10-11 08:24 UTC, tanguyprache commented on src/features/offer/components/OfferNewXPCine/CineBlockSkeleton.native.test.tsx
> +describe('<CineBlockSkeleton />', () => {
Pour le skeleton ce que l'on veut tester c'est plus le fait qu'il s'affiche bien lorsque la requête est au statut `loading` dans `OfferNewXPCineBlock`. Là le test sur un render simple n'apporte rien d'intéressant. C'est pareil pour le venue skeleton, du coup si il est déjà testé avec `OfferNewXPCineBlock` pas besoin d'avoir ce genre de test

2024-10-11 09:28 UTC, inesmouandjolobe approved these changes
GG pour l'augmentation du coverage 🚀🚀🚀

2024-10-11 09:29 UTC, NolwenMajorFrances approved these changes

2024-10-11 09:53 UTC, tanguyprache approved these changes
Top ! Bien joué Xavier ! Il faudrait juste penser à se noter dans un ticket de remplacer les tests sur les skeleton par des stories :)

2024-10-11 09:57 UTC, merged