(PC-7428) réservations terminées: affichage du header et du nombre de résas terminées
pass-culture/pass-culture-app-native pull request #738
Opened 2021-03-23 19:05 UTC by AnoukHello

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7428

## Checklist

I have:

- [ ] Made sure the title of my PR follows the convention `[PC-XXX] <summary>`.
- [ ] Made sure my feature is working on the relevant real / virtual devices.
- [ ] Written **unit tests** for my feature.
- [ ] Added new reusable components to the AppComponents page and communicate to the team on slack
- [ ] Added a **screenshot** for UI tickets.
- [ ] Attached a **ticket number** for any added TODO/FIXME \
       (for tech tasks, give the best context about the TODO resolution: what/who/when).

## Screenshots

| \*iOS - [Phone name] | \*Android - [Phone name] | Tablet - [Phone name] | Little - [Phone name] |
| -------------------- | :----------------------: | --------------------: | --------------------: |
|![Simulator Screen Shot - iPhone 12 - 2021-03-23 at 20 03 13](https://user-images.githubusercontent.com/22886846/112203599-028d1600-8c13-11eb-8df7-1d477b8afe8c.png)
|                          |                       |                       |

## Deploy hard

If native code (ios/android) was modified, **after** the PR is merged, on the master branch, upgrade the **app version** (+1 patch):

- if you want an hard deployment of the testing environment, use `yarn trigger:testing:deploy`

2021-03-24 11:26 UTC, kopax-polyconseil commented
@AnoukHello j'ai corrigé le test de `Booking.test.tsx` ici https://github.com/pass-culture/pass-culture-app-native/pull/742 si tu veux rebase

2021-03-24 14:47 UTC, kopax-polyconseil requested changes

2021-03-24 14:47 UTC, kopax-polyconseil commented on src/features/bookings/pages/EndedBookings.tsx
> +  plural ? _(t`réservations terminées`) : _(t`réservation terminée`)
https://js-lingui-git-stable-2x-lingui-js.vercel.app/guides/plurals.html#using-plural-forms

2021-03-25 10:46 UTC, kopax-polyconseil commented on src/features/bookings/pages/Bookings.tsx
> +  const endedBookingsLabel = i18n.plural({
Est-ce qu'on peut utiliser le plural avec _(t`string`) (plutôt que via i18n.plural ?

2021-03-25 11:32 UTC, AnoukHello commented on src/features/bookings/pages/Bookings.tsx
> +  const endedBookingsLabel = i18n.plural({
`_` est un raccourci de la méthode `i18n._` qui ne gère pas le pluriel. Ensuite, la méthode `i18n.plural` n'accepte que des string en arguments, donc pas possible de lui passer `t` paramètre https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ded200ae9ed56f5e258d32f94e4aaf48578b8584/types/lingui__core/i18n.d.ts#L52

2021-03-25 11:38 UTC, AnoukHello commented on src/features/bookings/pages/Bookings.tsx
> +  const endedBookingsLabel = i18n.plural({
Je n'ai pas l'impression que ça pose souci au niveau du fichier de trad généré, mais peut-être que je me trompe, t'en penses quoi @justinemignot ?

2021-03-25 11:41 UTC, kopax-polyconseil approved these changes

2021-03-25 11:41 UTC, kopax-polyconseil commented on src/features/bookings/pages/Bookings.tsx
> +  const endedBookingsLabel = i18n.plural({
OK pour moi

2021-03-25 12:03 UTC, justinemignot commented on src/features/bookings/pages/Bookings.tsx
> +  const endedBookingsLabel = i18n.plural({
Ok pour moi, ce que tu as fait est aligné avec la doc de lingui

2021-03-25 12:14 UTC, merged