(PC-7847) App Native - Tunnel de résa - Tracking - Clic sur une date disponible
pass-culture/pass-culture-app-native pull request #812
Opened 2021-03-31 09:16 UTC by kopax-polyconseil

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7847

Pareil que #811 : **vérifier que l'intégration correspond à ce qui est demandé**

## Checklist

I have:

- [ ] Made sure the title of my PR follows the convention `[PC-XXX] <summary>`.
- [ ] Made sure my feature is working on the relevant real / virtual devices.
- [ ] Written **unit tests** for my feature.
- [ ] Added new reusable components to the AppComponents page and communicate to the team on slack
- [ ] Added a **screenshot** for UI tickets.
- [ ] Attached a **ticket number** for any added TODO/FIXME \
       (for tech tasks, give the best context about the TODO resolution: what/who/when).

## Screenshots

| \*iOS - [Phone name] | \*Android - [Phone name] | Tablet - [Phone name] | Little - [Phone name] |
| -------------------- | :----------------------: | --------------------: | --------------------: |
|                      |                          |                       |                       |

## Deploy hard

If native code (ios/android) was modified, **after** the PR is merged, on the master branch, upgrade the **app version** (+1 patch):

- if you want an hard deployment of the testing environment, use `yarn trigger:testing:deploy`

2021-03-31 13:02 UTC, antoinewg requested changes
il manque un test

2021-03-31 13:02 UTC, antoinewg commented on src/features/bookOffer/components/Calendar/Calendar.tsx
> +          analytics.logClickBookOffer(offerId)
c'est celui là qu'on veut ?

2021-03-31 13:03 UTC, kopax commented on src/features/bookOffer/components/Calendar/Calendar.tsx
> +          analytics.logClickBookOffer(offerId)
Tu veux dire ce `offerId` ? Car les créneaux sont pour 
le même `offerId`.

2021-03-31 13:06 UTC, kopax commented
> il manque un test

Pour le test, encore un fichier ou il n'y en avait pas au départ. Le composant a un flow atypique, mais ça doit être testable, je regarde.

2021-03-31 15:02 UTC, kopax-polyconseil commented on src/features/bookOffer/components/Calendar/Calendar.tsx
> +          analytics.logClickBookOffer(offerId)
OK

2021-04-01 12:29 UTC, antoinewg approved these changes

2021-04-01 12:32 UTC, merged