(PC-4371) Ajout des inputs "texte" et "mot de passe" à l'UI de l'app
pass-culture/pass-culture-app-native pull request #90
Opened 2020-11-04 12:20 UTC by BenStirrup

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4371

## Checklist

I have:

- [x] Made sure the title of my PR follows the convention `[PC-XXX] <summary>`.
- [x] Made sure my feature is working on the relevant real / virtual devices.
- [ ] Written **unit tests** for my feature.
- [x] Added a **screenshot** for UI tickets.
- [ ] ~Explained my technical strategy below if feature is complex.~

## Deploy hard

If native code (ios/android) was modified, **after** the PR is merged, on the master branch, upgrade the **app version** (+1 patch):

- if you want an hard deployment of the testing environment, use `yarn version:testing` (this will create a commit with a tag)
- then run `git push --follow-tags`

## Screenshot 
| Page des composants |
| ------------------------------ |
| ![image](https://user-images.githubusercontent.com/22399093/98111141-71561680-1ea0-11eb-8ee1-b9cd9047eac1.png) |

2020-11-04 13:38 UTC, blixit requested changes

2020-11-04 13:38 UTC, blixit commented on src/features/cheatcodes/pages/AppComponents.tsx
> +        value={''}
value="" marche aussi. pourquoi s'embêter avec des accolades quand on peut s'entasser ?

2020-11-04 13:38 UTC, blixit commented on src/features/cheatcodes/pages/AppComponents.tsx
> +        onChangeText={() => {
flag performance de la page

Cette page va contenir potentiellement plusieurs composants. il faudra surveiller la durée de chargement au fur à mesure qu'on avance

2020-11-04 13:38 UTC, blixit commented on src/ui/components/inputs/TextInput.tsx
> +  keyboardType?: RNTextInputProps['keyboardType']
pourquoi tu ne prends que certaines Props de RN et pas toutes ?

```ts
export interface TextInputProps extends RNTextInputProps {
// custom props
}
```

sinon, si tu veux à tout prix sélectionner que certaines props:
```ts
type TextInputProps2 = Pick<RNTextInputProps, 'onChangeText' | 'placeholder' | ... > & {
  // custom props
  isError?: boolean
  // ...
}
```

alternativement à Pick tu peux utiliser Omit en fonction de ce qui est plus facile

2020-11-04 13:38 UTC, blixit commented on src/ui/components/inputs/TextInput.tsx
> +        autoFocus={props.autoFocus}
tu ne déstructure pas les props ? c'est pour les différencier des States ?

2020-11-04 13:38 UTC, blixit commented on src/ui/components/inputs/InputContainer.tsx
> +const DEFAULT_INPUT_WIDTH = 320
pourquoi 320 ?

t'as testé sur petit device ? SE, S5, iPod touch ?

2020-11-04 13:38 UTC, blixit commented on src/ui/components/inputs/PasswordInput.tsx
> +  flex: 0.1,
sur une tablette est-ce que le ratio 0.1 / 0.9 est suffisant ? ne faut-il pas contraindre l'espace de l'icône par une with-max ?

2020-11-04 13:39 UTC, blixit requested changes

2020-11-04 13:39 UTC, blixit commented on src/ui/components/inputs/PasswordInput.tsx
> +        {shouldHidePassword ? <ViewHide /> : <ViewShow />}
j'ai pas compris à quoi servait l'icône avant de voir où tu l'utilises.
je ne suis pas à l'aise avec le naming.
je propose de suivre le nomade de FontAwesome: **Eye** et **EyeSlash** https://fontawesome.com/icons?d=gallery&q=eye

2020-11-04 13:42 UTC, BenStirrup commented on src/ui/components/inputs/TextInput.tsx
> +        autoFocus={props.autoFocus}
Je ne suis pas fan du destructuring à outrance : cela peut apporter de la confusion et peut ajouter des blocks de déclaration quand trop de variables sont destructurées.

2020-11-04 13:43 UTC, BenStirrup commented on src/ui/components/inputs/PasswordInput.tsx
> +        {shouldHidePassword ? <ViewHide /> : <ViewShow />}
Ok pour moi

2020-11-04 13:43 UTC, BenStirrup commented on src/ui/components/inputs/PasswordInput.tsx
> +  flex: 0.1,
J'ai aucune idée de comment tester sur tablette. Mais on peut mettre une width max oui.

2020-11-04 13:44 UTC, BenStirrup commented on src/ui/components/inputs/InputContainer.tsx
> +const DEFAULT_INPUT_WIDTH = 320
Parceque c'est la valeur spécifiée sur la maquette.

2020-11-04 13:45 UTC, BenStirrup commented on src/ui/components/inputs/TextInput.tsx
> +  keyboardType?: RNTextInputProps['keyboardType']
Ok pour moi

2020-11-04 13:45 UTC, BenStirrup commented on src/features/cheatcodes/pages/AppComponents.tsx
> +        onChangeText={() => {
yes

2020-11-04 13:45 UTC, BenStirrup commented on src/features/cheatcodes/pages/AppComponents.tsx
> +        value={''}
yes

2020-11-04 13:50 UTC, AnoukHello commented on src/ui/components/inputs/InputContainer.tsx
> +    }),
Il y a un truc que je comprend pas: à quel endroit on sait qu'on tourne sous android ou iOS ? Comment cette fonction sait si elle doit appeler le getShadow d'android ou d'iOS ?

2020-11-04 13:54 UTC, BenStirrup commented on src/ui/components/inputs/InputContainer.tsx
> +    }),
Tu as oublié notre discussion d'il y a 3 semaines^^

2020-11-04 13:57 UTC, BenStirrup commented on src/ui/components/inputs/InputContainer.tsx
> +    }),
My bad, je pensais que c'était Alain qui avait commenté :facepalm: .
Je t'expliquerai Anouk.

2020-11-04 14:30 UTC, BenStirrup commented on src/ui/components/inputs/InputContainer.tsx
> +    }),
Voilà : https://reactnative.dev/docs/platform-specific-code#platform-specific-extensions

2020-11-04 15:11 UTC, blixit commented on src/ui/components/inputs/PasswordInput.tsx
> +  flex: 0.1,
je veux bien, parce que 0.1 ne rendra pas de la même façon sur les différents Devices

2020-11-05 12:58 UTC, blixit approved these changes

2020-11-05 13:03 UTC, merged