[sentry] revisit how we set use id
pass-culture/pass-culture-app-native pull request #960
Opened 2021-04-28 11:27 UTC by antoinewg

2021-04-28 12:35 UTC, kopax-polyconseil requested changes

2021-04-28 12:35 UTC, kopax-polyconseil commented on src/features/auth/AuthContext.tsx
> +    errorMonitoring.configureScope((scope) => scope.setUser(null))
Alexis souhaitais qu'on garde le dernier id de l'utilisateur connecté du device, comme sur la webapp.

2021-04-28 13:01 UTC, antoinewg commented on src/features/auth/AuthContext.tsx
> +    errorMonitoring.configureScope((scope) => scope.setUser(null))
donc je supprime cette ligne?

2021-04-29 08:41 UTC, kopax-polyconseil approved these changes

2021-04-29 10:15 UTC, merged